/*
 * Created on 2026-02-11 ( 11:29:05 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.entities.tooling;

import javax.persistence.EntityManager;

import com.organizame.reportes.entities.LogCargaJpaTest;
import com.organizame.reportes.entities.VhcAnioJpaTest;
import com.organizame.reportes.entities.VhcBoletinprecioJpaTest;
import com.organizame.reportes.entities.VhcBoletinpreciogastoJpaTest;
import com.organizame.reportes.entities.VhcDaacuotaJpaTest;
import com.organizame.reportes.entities.VhcIncentivoJpaTest;
import com.organizame.reportes.entities.VhcMarcaJpaTest;
import com.organizame.reportes.entities.VhcModeloJpaTest;
import com.organizame.reportes.entities.VhcReembolsoJpaTest;
import com.organizame.reportes.entities.VhcVersionJpaTest;

/**
 * Database initialization before unit tests
 * 
 * @author Telosys
 *
 */
public class DatabaseInit {

    /**
     * Set database initial state
     * @param em
     */
    public static void initializeTablesData(EntityManager em) {

		// Disable referential integrity
    	execNativeQuery(em, "SET REFERENTIAL_INTEGRITY FALSE");

		// Initialize each table with one entity
		initTableWithEntity(em, LogCargaJpaTest.getInitEntity());	
		initTableWithEntity(em, VhcAnioJpaTest.getInitEntity());	
		initTableWithEntity(em, VhcBoletinprecioJpaTest.getInitEntity());	
		initTableWithEntity(em, VhcBoletinpreciogastoJpaTest.getInitEntity());	
		initTableWithEntity(em, VhcDaacuotaJpaTest.getInitEntity());	
		initTableWithEntity(em, VhcIncentivoJpaTest.getInitEntity());	
		initTableWithEntity(em, VhcMarcaJpaTest.getInitEntity());	
		initTableWithEntity(em, VhcModeloJpaTest.getInitEntity());	
		initTableWithEntity(em, VhcReembolsoJpaTest.getInitEntity());	
		initTableWithEntity(em, VhcVersionJpaTest.getInitEntity());	

		// Enable referential integrity
    	execNativeQuery(em, "SET REFERENTIAL_INTEGRITY TRUE");
    }

	private static void execNativeQuery(EntityManager em, String sql) {
    	em.getTransaction().begin();
    	em.createNativeQuery(sql).executeUpdate();
    	em.getTransaction().commit();
    }
    
    private static void initTableWithEntity(EntityManager em, Object entity) {
		execQuery(em, "DELETE FROM " + entity.getClass().getSimpleName());
		initEntity(em, entity);
    }
    
    private static void execQuery(EntityManager em, String sql) {
    	em.getTransaction().begin();
    	em.createQuery(sql).executeUpdate();
    	em.getTransaction().commit();
    }
    
    private static void initEntity(EntityManager em, Object entity) {
        em.getTransaction().begin();
        em.merge(entity);
        em.getTransaction().commit();		
    }

}