package com.organizame.reportes.entity;
// Generated 6 nov 2025 15:47:18 by Hibernate Tools 6.6.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import java.util.HashSet;
import java.util.Set;

/**
 * VhcAnio generated by hbm2java
 */
@Entity
@Table(name="vhc_anio"
    , uniqueConstraints = @UniqueConstraint(columnNames={"IDVERSION", "NOMBRE"}) 
)
public class VhcAnio  implements java.io.Serializable {


     private byte[] idanio;
     private VhcVersion vhcVersion;
     private String nombre;
     private Set vhcPeriodos = new HashSet(0);

    public VhcAnio() {
    }

	
    public VhcAnio(byte[] idanio, String nombre) {
        this.idanio = idanio;
        this.nombre = nombre;
    }
    public VhcAnio(byte[] idanio, VhcVersion vhcVersion, String nombre, Set vhcPeriodos) {
       this.idanio = idanio;
       this.vhcVersion = vhcVersion;
       this.nombre = nombre;
       this.vhcPeriodos = vhcPeriodos;
    }
   
     @Id 

    
    @Column(name="IDANIO", unique=true, nullable=false)
    public byte[] getIdanio() {
        return this.idanio;
    }
    
    public void setIdanio(byte[] idanio) {
        this.idanio = idanio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDVERSION")
    public VhcVersion getVhcVersion() {
        return this.vhcVersion;
    }
    
    public void setVhcVersion(VhcVersion vhcVersion) {
        this.vhcVersion = vhcVersion;
    }

    
    @Column(name="NOMBRE", nullable=false, length=255)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vhcAnio")
    public Set getVhcPeriodos() {
        return this.vhcPeriodos;
    }
    
    public void setVhcPeriodos(Set vhcPeriodos) {
        this.vhcPeriodos = vhcPeriodos;
    }




}


