package com.organizame.reportes.entity;
// Generated 6 nov 2025 15:47:18 by Hibernate Tools 6.6.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * VhcFabricantemarca generated by hbm2java
 */
@Entity
@Table(name="vhc_fabricantemarca"
)
public class VhcFabricantemarca  implements java.io.Serializable {


     private byte[] idfabricantemarca;
     private VhcFabricante vhcFabricante;
     private byte[] idmarca;

    public VhcFabricantemarca() {
    }

	
    public VhcFabricantemarca(byte[] idfabricantemarca) {
        this.idfabricantemarca = idfabricantemarca;
    }
    public VhcFabricantemarca(byte[] idfabricantemarca, VhcFabricante vhcFabricante, byte[] idmarca) {
       this.idfabricantemarca = idfabricantemarca;
       this.vhcFabricante = vhcFabricante;
       this.idmarca = idmarca;
    }
   
     @Id 

    
    @Column(name="IDFABRICANTEMARCA", unique=true, nullable=false)
    public byte[] getIdfabricantemarca() {
        return this.idfabricantemarca;
    }
    
    public void setIdfabricantemarca(byte[] idfabricantemarca) {
        this.idfabricantemarca = idfabricantemarca;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDFABRICANTE")
    public VhcFabricante getVhcFabricante() {
        return this.vhcFabricante;
    }
    
    public void setVhcFabricante(VhcFabricante vhcFabricante) {
        this.vhcFabricante = vhcFabricante;
    }

    
    @Column(name="IDMARCA")
    public byte[] getIdmarca() {
        return this.idmarca;
    }
    
    public void setIdmarca(byte[] idmarca) {
        this.idmarca = idmarca;
    }




}


