package com.organizame.reportes.entity;
// Generated 6 nov 2025 15:47:18 by Hibernate Tools 6.6.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import java.util.HashSet;
import java.util.Set;

/**
 * VhcFabricante generated by hbm2java
 */
@Entity
@Table(name="vhc_fabricante"
    , uniqueConstraints = {@UniqueConstraint(columnNames="CLAVE"), @UniqueConstraint(columnNames="NOMBRE")} 
)
public class VhcFabricante  implements java.io.Serializable {


     private byte[] idfabricante;
     private String nombre;
     private String clave;
     private int orden;
     private Set vhcFabricantemarcas = new HashSet(0);

    public VhcFabricante() {
    }

	
    public VhcFabricante(byte[] idfabricante, String nombre, String clave, int orden) {
        this.idfabricante = idfabricante;
        this.nombre = nombre;
        this.clave = clave;
        this.orden = orden;
    }
    public VhcFabricante(byte[] idfabricante, String nombre, String clave, int orden, Set vhcFabricantemarcas) {
       this.idfabricante = idfabricante;
       this.nombre = nombre;
       this.clave = clave;
       this.orden = orden;
       this.vhcFabricantemarcas = vhcFabricantemarcas;
    }
   
     @Id 

    
    @Column(name="IDFABRICANTE", unique=true, nullable=false)
    public byte[] getIdfabricante() {
        return this.idfabricante;
    }
    
    public void setIdfabricante(byte[] idfabricante) {
        this.idfabricante = idfabricante;
    }

    
    @Column(name="NOMBRE", unique=true, nullable=false, length=255)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="CLAVE", unique=true, nullable=false, length=255)
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }

    
    @Column(name="ORDEN", nullable=false)
    public int getOrden() {
        return this.orden;
    }
    
    public void setOrden(int orden) {
        this.orden = orden;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vhcFabricante")
    public Set getVhcFabricantemarcas() {
        return this.vhcFabricantemarcas;
    }
    
    public void setVhcFabricantemarcas(Set vhcFabricantemarcas) {
        this.vhcFabricantemarcas = vhcFabricantemarcas;
    }




}


