package com.organizame.reportes.entity;
// Generated 6 nov 2025 15:47:18 by Hibernate Tools 6.6.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * VhcGrupomarca generated by hbm2java
 */
@Entity
@Table(name="vhc_grupomarca"
)
public class VhcGrupomarca  implements java.io.Serializable {


     private byte[] idgrupomarca;
     private VhcGrupo vhcGrupo;
     private byte[] idmarca;

    public VhcGrupomarca() {
    }

	
    public VhcGrupomarca(byte[] idgrupomarca) {
        this.idgrupomarca = idgrupomarca;
    }
    public VhcGrupomarca(byte[] idgrupomarca, VhcGrupo vhcGrupo, byte[] idmarca) {
       this.idgrupomarca = idgrupomarca;
       this.vhcGrupo = vhcGrupo;
       this.idmarca = idmarca;
    }
   
     @Id 

    
    @Column(name="IDGRUPOMARCA", unique=true, nullable=false)
    public byte[] getIdgrupomarca() {
        return this.idgrupomarca;
    }
    
    public void setIdgrupomarca(byte[] idgrupomarca) {
        this.idgrupomarca = idgrupomarca;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDGRUPO")
    public VhcGrupo getVhcGrupo() {
        return this.vhcGrupo;
    }
    
    public void setVhcGrupo(VhcGrupo vhcGrupo) {
        this.vhcGrupo = vhcGrupo;
    }

    
    @Column(name="IDMARCA")
    public byte[] getIdmarca() {
        return this.idmarca;
    }
    
    public void setIdmarca(byte[] idmarca) {
        this.idmarca = idmarca;
    }




}


