package com.organizame.reportes.entity;
// Generated 6 nov 2025 15:47:18 by Hibernate Tools 6.6.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import java.util.HashSet;
import java.util.Set;

/**
 * VhcGrupo generated by hbm2java
 */
@Entity
@Table(name="vhc_grupo"
    , uniqueConstraints = {@UniqueConstraint(columnNames="CLAVE"), @UniqueConstraint(columnNames="NOMBRE")} 
)
public class VhcGrupo  implements java.io.Serializable {


     private byte[] idgrupo;
     private String nombre;
     private String clave;
     private int orden;
     private Set vhcGrupomarcas = new HashSet(0);
     private Set vhcGrupoperiodoventausas = new HashSet(0);

    public VhcGrupo() {
    }

	
    public VhcGrupo(byte[] idgrupo, String nombre, String clave, int orden) {
        this.idgrupo = idgrupo;
        this.nombre = nombre;
        this.clave = clave;
        this.orden = orden;
    }
    public VhcGrupo(byte[] idgrupo, String nombre, String clave, int orden, Set vhcGrupomarcas, Set vhcGrupoperiodoventausas) {
       this.idgrupo = idgrupo;
       this.nombre = nombre;
       this.clave = clave;
       this.orden = orden;
       this.vhcGrupomarcas = vhcGrupomarcas;
       this.vhcGrupoperiodoventausas = vhcGrupoperiodoventausas;
    }
   
     @Id 

    
    @Column(name="IDGRUPO", unique=true, nullable=false)
    public byte[] getIdgrupo() {
        return this.idgrupo;
    }
    
    public void setIdgrupo(byte[] idgrupo) {
        this.idgrupo = idgrupo;
    }

    
    @Column(name="NOMBRE", unique=true, nullable=false, length=255)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="CLAVE", unique=true, nullable=false, length=255)
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }

    
    @Column(name="ORDEN", nullable=false)
    public int getOrden() {
        return this.orden;
    }
    
    public void setOrden(int orden) {
        this.orden = orden;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vhcGrupo")
    public Set getVhcGrupomarcas() {
        return this.vhcGrupomarcas;
    }
    
    public void setVhcGrupomarcas(Set vhcGrupomarcas) {
        this.vhcGrupomarcas = vhcGrupomarcas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vhcGrupo")
    public Set getVhcGrupoperiodoventausas() {
        return this.vhcGrupoperiodoventausas;
    }
    
    public void setVhcGrupoperiodoventausas(Set vhcGrupoperiodoventausas) {
        this.vhcGrupoperiodoventausas = vhcGrupoperiodoventausas;
    }




}


