package com.organizame.reportes.entity;
// Generated 6 nov 2025 15:47:18 by Hibernate Tools 6.6.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * VhcGrupoperiodoventausa generated by hbm2java
 */
@Entity
@Table(name="vhc_grupoperiodoventausa"
)
public class VhcGrupoperiodoventausa  implements java.io.Serializable {


     private byte[] idgrupoperiodoventausa;
     private VhcGrupo vhcGrupo;
     private int periodoanio;
     private int periodotrimestre;
     private int cantidad;

    public VhcGrupoperiodoventausa() {
    }

	
    public VhcGrupoperiodoventausa(byte[] idgrupoperiodoventausa, int periodoanio, int periodotrimestre, int cantidad) {
        this.idgrupoperiodoventausa = idgrupoperiodoventausa;
        this.periodoanio = periodoanio;
        this.periodotrimestre = periodotrimestre;
        this.cantidad = cantidad;
    }
    public VhcGrupoperiodoventausa(byte[] idgrupoperiodoventausa, VhcGrupo vhcGrupo, int periodoanio, int periodotrimestre, int cantidad) {
       this.idgrupoperiodoventausa = idgrupoperiodoventausa;
       this.vhcGrupo = vhcGrupo;
       this.periodoanio = periodoanio;
       this.periodotrimestre = periodotrimestre;
       this.cantidad = cantidad;
    }
   
     @Id 

    
    @Column(name="IDGRUPOPERIODOVENTAUSA", unique=true, nullable=false)
    public byte[] getIdgrupoperiodoventausa() {
        return this.idgrupoperiodoventausa;
    }
    
    public void setIdgrupoperiodoventausa(byte[] idgrupoperiodoventausa) {
        this.idgrupoperiodoventausa = idgrupoperiodoventausa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDGRUPO")
    public VhcGrupo getVhcGrupo() {
        return this.vhcGrupo;
    }
    
    public void setVhcGrupo(VhcGrupo vhcGrupo) {
        this.vhcGrupo = vhcGrupo;
    }

    
    @Column(name="PERIODOANIO", nullable=false)
    public int getPeriodoanio() {
        return this.periodoanio;
    }
    
    public void setPeriodoanio(int periodoanio) {
        this.periodoanio = periodoanio;
    }

    
    @Column(name="PERIODOTRIMESTRE", nullable=false)
    public int getPeriodotrimestre() {
        return this.periodotrimestre;
    }
    
    public void setPeriodotrimestre(int periodotrimestre) {
        this.periodotrimestre = periodotrimestre;
    }

    
    @Column(name="CANTIDAD", nullable=false)
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }




}


