package com.organizame.reportes.entity;
// Generated 6 nov 2025 15:47:18 by Hibernate Tools 6.6.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * VhcModeloalias generated by hbm2java
 */
@Entity
@Table(name="vhc_modeloalias"
    , uniqueConstraints = @UniqueConstraint(columnNames={"IDMODELO", "NOMBRE"}) 
)
public class VhcModeloalias  implements java.io.Serializable {


     private byte[] idmodeloalias;
     private VhcModelo vhcModelo;
     private String nombre;

    public VhcModeloalias() {
    }

	
    public VhcModeloalias(byte[] idmodeloalias, String nombre) {
        this.idmodeloalias = idmodeloalias;
        this.nombre = nombre;
    }
    public VhcModeloalias(byte[] idmodeloalias, VhcModelo vhcModelo, String nombre) {
       this.idmodeloalias = idmodeloalias;
       this.vhcModelo = vhcModelo;
       this.nombre = nombre;
    }
   
     @Id 

    
    @Column(name="IDMODELOALIAS", unique=true, nullable=false)
    public byte[] getIdmodeloalias() {
        return this.idmodeloalias;
    }
    
    public void setIdmodeloalias(byte[] idmodeloalias) {
        this.idmodeloalias = idmodeloalias;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDMODELO")
    public VhcModelo getVhcModelo() {
        return this.vhcModelo;
    }
    
    public void setVhcModelo(VhcModelo vhcModelo) {
        this.vhcModelo = vhcModelo;
    }

    
    @Column(name="NOMBRE", nullable=false, length=255)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


