package com.organizame.reportes.entity;
// Generated 6 nov 2025 15:47:18 by Hibernate Tools 6.6.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import java.util.HashSet;
import java.util.Set;

/**
 * VhcMarca generated by hbm2java
 */
@Entity
@Table(name="vhc_marca"
    , uniqueConstraints = @UniqueConstraint(columnNames="NOMBRE") 
)
public class VhcMarca  implements java.io.Serializable {


     private byte[] idmarca;
     private String nombre;
     private int orden;
     private Set vhcMarcaplantillas = new HashSet(0);
     private Set vhcMarcaarchivos = new HashSet(0);
     private Set vhcMarcaperiodos = new HashSet(0);
     private Set vhcModelos = new HashSet(0);

    public VhcMarca() {
    }

	
    public VhcMarca(byte[] idmarca, String nombre, int orden) {
        this.idmarca = idmarca;
        this.nombre = nombre;
        this.orden = orden;
    }
    public VhcMarca(byte[] idmarca, String nombre, int orden, Set vhcMarcaplantillas, Set vhcMarcaarchivos, Set vhcMarcaperiodos, Set vhcModelos) {
       this.idmarca = idmarca;
       this.nombre = nombre;
       this.orden = orden;
       this.vhcMarcaplantillas = vhcMarcaplantillas;
       this.vhcMarcaarchivos = vhcMarcaarchivos;
       this.vhcMarcaperiodos = vhcMarcaperiodos;
       this.vhcModelos = vhcModelos;
    }
   
     @Id 

    
    @Column(name="IDMARCA", unique=true, nullable=false)
    public byte[] getIdmarca() {
        return this.idmarca;
    }
    
    public void setIdmarca(byte[] idmarca) {
        this.idmarca = idmarca;
    }

    
    @Column(name="NOMBRE", unique=true, nullable=false, length=255)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="ORDEN", nullable=false)
    public int getOrden() {
        return this.orden;
    }
    
    public void setOrden(int orden) {
        this.orden = orden;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vhcMarca")
    public Set getVhcMarcaplantillas() {
        return this.vhcMarcaplantillas;
    }
    
    public void setVhcMarcaplantillas(Set vhcMarcaplantillas) {
        this.vhcMarcaplantillas = vhcMarcaplantillas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vhcMarca")
    public Set getVhcMarcaarchivos() {
        return this.vhcMarcaarchivos;
    }
    
    public void setVhcMarcaarchivos(Set vhcMarcaarchivos) {
        this.vhcMarcaarchivos = vhcMarcaarchivos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vhcMarca")
    public Set getVhcMarcaperiodos() {
        return this.vhcMarcaperiodos;
    }
    
    public void setVhcMarcaperiodos(Set vhcMarcaperiodos) {
        this.vhcMarcaperiodos = vhcMarcaperiodos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vhcMarca")
    public Set getVhcModelos() {
        return this.vhcModelos;
    }
    
    public void setVhcModelos(Set vhcModelos) {
        this.vhcModelos = vhcModelos;
    }




}


