package com.organizame.reportes.entity;
// Generated 6 nov 2025 15:47:18 by Hibernate Tools 6.6.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * VhcModeloperiodoindustria generated by hbm2java
 */
@Entity
@Table(name="vhc_modeloperiodoindustria"
)
public class VhcModeloperiodoindustria  implements java.io.Serializable {


     private byte[] idmodeloperiodoindustria;
     private VhcModelo vhcModelo;
     private int periodoanio;
     private int periodomes;
     private String segmentoarchivo;
     private String modeloarchivo;
     private String fabricantearchivo;
     private String origenarchivo;
     private String marcaarchivo;
     private int cantidad;

    public VhcModeloperiodoindustria() {
    }

	
    public VhcModeloperiodoindustria(byte[] idmodeloperiodoindustria, int periodoanio, int periodomes, int cantidad) {
        this.idmodeloperiodoindustria = idmodeloperiodoindustria;
        this.periodoanio = periodoanio;
        this.periodomes = periodomes;
        this.cantidad = cantidad;
    }
    public VhcModeloperiodoindustria(byte[] idmodeloperiodoindustria, VhcModelo vhcModelo, int periodoanio, int periodomes, String segmentoarchivo, String modeloarchivo, String fabricantearchivo, String origenarchivo, String marcaarchivo, int cantidad) {
       this.idmodeloperiodoindustria = idmodeloperiodoindustria;
       this.vhcModelo = vhcModelo;
       this.periodoanio = periodoanio;
       this.periodomes = periodomes;
       this.segmentoarchivo = segmentoarchivo;
       this.modeloarchivo = modeloarchivo;
       this.fabricantearchivo = fabricantearchivo;
       this.origenarchivo = origenarchivo;
       this.marcaarchivo = marcaarchivo;
       this.cantidad = cantidad;
    }
   
     @Id 

    
    @Column(name="IDMODELOPERIODOINDUSTRIA", unique=true, nullable=false)
    public byte[] getIdmodeloperiodoindustria() {
        return this.idmodeloperiodoindustria;
    }
    
    public void setIdmodeloperiodoindustria(byte[] idmodeloperiodoindustria) {
        this.idmodeloperiodoindustria = idmodeloperiodoindustria;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDMODELO")
    public VhcModelo getVhcModelo() {
        return this.vhcModelo;
    }
    
    public void setVhcModelo(VhcModelo vhcModelo) {
        this.vhcModelo = vhcModelo;
    }

    
    @Column(name="PERIODOANIO", nullable=false)
    public int getPeriodoanio() {
        return this.periodoanio;
    }
    
    public void setPeriodoanio(int periodoanio) {
        this.periodoanio = periodoanio;
    }

    
    @Column(name="PERIODOMES", nullable=false)
    public int getPeriodomes() {
        return this.periodomes;
    }
    
    public void setPeriodomes(int periodomes) {
        this.periodomes = periodomes;
    }

    
    @Column(name="SEGMENTOARCHIVO", length=255)
    public String getSegmentoarchivo() {
        return this.segmentoarchivo;
    }
    
    public void setSegmentoarchivo(String segmentoarchivo) {
        this.segmentoarchivo = segmentoarchivo;
    }

    
    @Column(name="MODELOARCHIVO", length=255)
    public String getModeloarchivo() {
        return this.modeloarchivo;
    }
    
    public void setModeloarchivo(String modeloarchivo) {
        this.modeloarchivo = modeloarchivo;
    }

    
    @Column(name="FABRICANTEARCHIVO", length=255)
    public String getFabricantearchivo() {
        return this.fabricantearchivo;
    }
    
    public void setFabricantearchivo(String fabricantearchivo) {
        this.fabricantearchivo = fabricantearchivo;
    }

    
    @Column(name="ORIGENARCHIVO", length=255)
    public String getOrigenarchivo() {
        return this.origenarchivo;
    }
    
    public void setOrigenarchivo(String origenarchivo) {
        this.origenarchivo = origenarchivo;
    }

    
    @Column(name="MARCAARCHIVO", length=255)
    public String getMarcaarchivo() {
        return this.marcaarchivo;
    }
    
    public void setMarcaarchivo(String marcaarchivo) {
        this.marcaarchivo = marcaarchivo;
    }

    
    @Column(name="CANTIDAD", nullable=false)
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }




}


