package com.organizame.reportes.entity;
// Generated 6 nov 2025 15:47:18 by Hibernate Tools 6.6.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import java.util.HashSet;
import java.util.Set;

/**
 * VhcMarcaplantillatipo generated by hbm2java
 */
@Entity
@Table(name="vhc_marcaplantillatipo"
    , uniqueConstraints = {@UniqueConstraint(columnNames="CLAVE"), @UniqueConstraint(columnNames="NOMBRE")} 
)
public class VhcMarcaplantillatipo  implements java.io.Serializable {


     private byte[] idmarcaplantillatipo;
     private String nombre;
     private String descripcion;
     private String clave;
     private int orden;
     private Set vhcMarcaplantillatipobases = new HashSet(0);

    public VhcMarcaplantillatipo() {
    }

	
    public VhcMarcaplantillatipo(byte[] idmarcaplantillatipo, String nombre, String clave, int orden) {
        this.idmarcaplantillatipo = idmarcaplantillatipo;
        this.nombre = nombre;
        this.clave = clave;
        this.orden = orden;
    }
    public VhcMarcaplantillatipo(byte[] idmarcaplantillatipo, String nombre, String descripcion, String clave, int orden, Set vhcMarcaplantillatipobases) {
       this.idmarcaplantillatipo = idmarcaplantillatipo;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.clave = clave;
       this.orden = orden;
       this.vhcMarcaplantillatipobases = vhcMarcaplantillatipobases;
    }
   
     @Id 

    
    @Column(name="IDMARCAPLANTILLATIPO", unique=true, nullable=false)
    public byte[] getIdmarcaplantillatipo() {
        return this.idmarcaplantillatipo;
    }
    
    public void setIdmarcaplantillatipo(byte[] idmarcaplantillatipo) {
        this.idmarcaplantillatipo = idmarcaplantillatipo;
    }

    
    @Column(name="NOMBRE", unique=true, nullable=false, length=255)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="DESCRIPCION", length=2000)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="CLAVE", unique=true, nullable=false, length=255)
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }

    
    @Column(name="ORDEN", nullable=false)
    public int getOrden() {
        return this.orden;
    }
    
    public void setOrden(int orden) {
        this.orden = orden;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vhcMarcaplantillatipo")
    public Set getVhcMarcaplantillatipobases() {
        return this.vhcMarcaplantillatipobases;
    }
    
    public void setVhcMarcaplantillatipobases(Set vhcMarcaplantillatipobases) {
        this.vhcMarcaplantillatipobases = vhcMarcaplantillatipobases;
    }




}


