package com.organizame.reportes.entity;
// Generated 6 nov 2025 15:47:18 by Hibernate Tools 6.6.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * VhcMarcaplantilla generated by hbm2java
 */
@Entity
@Table(name="vhc_marcaplantilla"
)
public class VhcMarcaplantilla  implements java.io.Serializable {


     private byte[] idmarcaplantilla;
     private VhcMarca vhcMarca;
     private int orden;
     private String archivo;
     private byte[] idmarcaplantillatipo;

    public VhcMarcaplantilla() {
    }

	
    public VhcMarcaplantilla(byte[] idmarcaplantilla, int orden) {
        this.idmarcaplantilla = idmarcaplantilla;
        this.orden = orden;
    }
    public VhcMarcaplantilla(byte[] idmarcaplantilla, VhcMarca vhcMarca, int orden, String archivo, byte[] idmarcaplantillatipo) {
       this.idmarcaplantilla = idmarcaplantilla;
       this.vhcMarca = vhcMarca;
       this.orden = orden;
       this.archivo = archivo;
       this.idmarcaplantillatipo = idmarcaplantillatipo;
    }
   
     @Id 

    
    @Column(name="IDMARCAPLANTILLA", unique=true, nullable=false)
    public byte[] getIdmarcaplantilla() {
        return this.idmarcaplantilla;
    }
    
    public void setIdmarcaplantilla(byte[] idmarcaplantilla) {
        this.idmarcaplantilla = idmarcaplantilla;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDMARCA")
    public VhcMarca getVhcMarca() {
        return this.vhcMarca;
    }
    
    public void setVhcMarca(VhcMarca vhcMarca) {
        this.vhcMarca = vhcMarca;
    }

    
    @Column(name="ORDEN", nullable=false)
    public int getOrden() {
        return this.orden;
    }
    
    public void setOrden(int orden) {
        this.orden = orden;
    }

    
    @Column(name="ARCHIVO", length=255)
    public String getArchivo() {
        return this.archivo;
    }
    
    public void setArchivo(String archivo) {
        this.archivo = archivo;
    }

    
    @Column(name="IDMARCAPLANTILLATIPO")
    public byte[] getIdmarcaplantillatipo() {
        return this.idmarcaplantillatipo;
    }
    
    public void setIdmarcaplantillatipo(byte[] idmarcaplantillatipo) {
        this.idmarcaplantillatipo = idmarcaplantillatipo;
    }




}


