package com.organizame.reportes.entity;
// Generated 6 nov 2025 15:47:18 by Hibernate Tools 6.6.3.Final


import jakarta.persistence.*;
import lombok.Data;

import java.util.HashSet;
import java.util.Set;

/**
 * VhcModelo generated by hbm2java
 */
@Data
@Entity
@Table(name="vhc_modelo"
    , uniqueConstraints = @UniqueConstraint(columnNames={"IDMARCA", "NOMBRE"}) 
)
public class VhcModelo  implements java.io.Serializable {


    @Id
    @Column(name="IDMODELO", unique=true, nullable=false, columnDefinition = "BINARY(255)")
     private byte[] idmodelo;
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDMARCA")
     private VhcMarca vhcMarca;
    @Column(name="NOMBRE", nullable=false, length=255)
     private String nombre;





}


