package com.organizame.reportes.entity;
// Generated 6 nov 2025 15:47:18 by Hibernate Tools 6.6.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * VhcMarcaplantillatipobase generated by hbm2java
 */
@Entity
@Table(name="vhc_marcaplantillatipobase"
)
public class VhcMarcaplantillatipobase  implements java.io.Serializable {


     private byte[] idmarcaplantillatipobase;
     private VhcMarcaplantillatipo vhcMarcaplantillatipo;
     private String descripcion;
     private int orden;
     private String archivo;
     private String fechainicio;

    public VhcMarcaplantillatipobase() {
    }

	
    public VhcMarcaplantillatipobase(byte[] idmarcaplantillatipobase, int orden) {
        this.idmarcaplantillatipobase = idmarcaplantillatipobase;
        this.orden = orden;
    }
    public VhcMarcaplantillatipobase(byte[] idmarcaplantillatipobase, VhcMarcaplantillatipo vhcMarcaplantillatipo, String descripcion, int orden, String archivo, String fechainicio) {
       this.idmarcaplantillatipobase = idmarcaplantillatipobase;
       this.vhcMarcaplantillatipo = vhcMarcaplantillatipo;
       this.descripcion = descripcion;
       this.orden = orden;
       this.archivo = archivo;
       this.fechainicio = fechainicio;
    }
   
     @Id 

    
    @Column(name="IDMARCAPLANTILLATIPOBASE", unique=true, nullable=false)
    public byte[] getIdmarcaplantillatipobase() {
        return this.idmarcaplantillatipobase;
    }
    
    public void setIdmarcaplantillatipobase(byte[] idmarcaplantillatipobase) {
        this.idmarcaplantillatipobase = idmarcaplantillatipobase;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDMARCAPLANTILLATIPO")
    public VhcMarcaplantillatipo getVhcMarcaplantillatipo() {
        return this.vhcMarcaplantillatipo;
    }
    
    public void setVhcMarcaplantillatipo(VhcMarcaplantillatipo vhcMarcaplantillatipo) {
        this.vhcMarcaplantillatipo = vhcMarcaplantillatipo;
    }

    
    @Column(name="DESCRIPCION", length=2000)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="ORDEN", nullable=false)
    public int getOrden() {
        return this.orden;
    }
    
    public void setOrden(int orden) {
        this.orden = orden;
    }

    
    @Column(name="ARCHIVO", length=255)
    public String getArchivo() {
        return this.archivo;
    }
    
    public void setArchivo(String archivo) {
        this.archivo = archivo;
    }

    
    @Column(name="FECHAINICIO", length=255)
    public String getFechainicio() {
        return this.fechainicio;
    }
    
    public void setFechainicio(String fechainicio) {
        this.fechainicio = fechainicio;
    }




}


