package com.organizame.reportes.entity;
// Generated 6 nov 2025 15:47:18 by Hibernate Tools 6.6.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * VhcModeloperiodo generated by hbm2java
 */
@Entity
@Table(name="vhc_modeloperiodo"
)
public class VhcModeloperiodo  implements java.io.Serializable {


     private byte[] idmodeloperiodo;
     private VhcModelo vhcModelo;
     private int periodoanio;
     private int periodomes;
     private int menudeoflotillanormal;
     private int flotillaespecial;
     private int inventariocambio;
     private int inventarionivel;

    public VhcModeloperiodo() {
    }

	
    public VhcModeloperiodo(byte[] idmodeloperiodo, int periodoanio, int periodomes, int menudeoflotillanormal, int flotillaespecial, int inventariocambio, int inventarionivel) {
        this.idmodeloperiodo = idmodeloperiodo;
        this.periodoanio = periodoanio;
        this.periodomes = periodomes;
        this.menudeoflotillanormal = menudeoflotillanormal;
        this.flotillaespecial = flotillaespecial;
        this.inventariocambio = inventariocambio;
        this.inventarionivel = inventarionivel;
    }
    public VhcModeloperiodo(byte[] idmodeloperiodo, VhcModelo vhcModelo, int periodoanio, int periodomes, int menudeoflotillanormal, int flotillaespecial, int inventariocambio, int inventarionivel) {
       this.idmodeloperiodo = idmodeloperiodo;
       this.vhcModelo = vhcModelo;
       this.periodoanio = periodoanio;
       this.periodomes = periodomes;
       this.menudeoflotillanormal = menudeoflotillanormal;
       this.flotillaespecial = flotillaespecial;
       this.inventariocambio = inventariocambio;
       this.inventarionivel = inventarionivel;
    }
   
     @Id 

    
    @Column(name="IDMODELOPERIODO", unique=true, nullable=false)
    public byte[] getIdmodeloperiodo() {
        return this.idmodeloperiodo;
    }
    
    public void setIdmodeloperiodo(byte[] idmodeloperiodo) {
        this.idmodeloperiodo = idmodeloperiodo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDMODELO")
    public VhcModelo getVhcModelo() {
        return this.vhcModelo;
    }
    
    public void setVhcModelo(VhcModelo vhcModelo) {
        this.vhcModelo = vhcModelo;
    }

    
    @Column(name="PERIODOANIO", nullable=false)
    public int getPeriodoanio() {
        return this.periodoanio;
    }
    
    public void setPeriodoanio(int periodoanio) {
        this.periodoanio = periodoanio;
    }

    
    @Column(name="PERIODOMES", nullable=false)
    public int getPeriodomes() {
        return this.periodomes;
    }
    
    public void setPeriodomes(int periodomes) {
        this.periodomes = periodomes;
    }

    
    @Column(name="MENUDEOFLOTILLANORMAL", nullable=false)
    public int getMenudeoflotillanormal() {
        return this.menudeoflotillanormal;
    }
    
    public void setMenudeoflotillanormal(int menudeoflotillanormal) {
        this.menudeoflotillanormal = menudeoflotillanormal;
    }

    
    @Column(name="FLOTILLAESPECIAL", nullable=false)
    public int getFlotillaespecial() {
        return this.flotillaespecial;
    }
    
    public void setFlotillaespecial(int flotillaespecial) {
        this.flotillaespecial = flotillaespecial;
    }

    
    @Column(name="INVENTARIOCAMBIO", nullable=false)
    public int getInventariocambio() {
        return this.inventariocambio;
    }
    
    public void setInventariocambio(int inventariocambio) {
        this.inventariocambio = inventariocambio;
    }

    
    @Column(name="INVENTARIONIVEL", nullable=false)
    public int getInventarionivel() {
        return this.inventarionivel;
    }
    
    public void setInventarionivel(int inventarionivel) {
        this.inventarionivel = inventarionivel;
    }




}


