package com.organizame.reportes.entity;
// Generated 6 nov 2025 15:47:18 by Hibernate Tools 6.6.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;
import java.util.Arrays;

/**
 * VhcModeloaliasViewId generated by hbm2java
 */
@Embeddable
public class VhcModeloaliasViewId  implements java.io.Serializable {


     private String alias;
     private byte[] idmodelo;
     private String nombre;

    public VhcModeloaliasViewId() {
    }

    public VhcModeloaliasViewId(String alias, byte[] idmodelo, String nombre) {
       this.alias = alias;
       this.idmodelo = idmodelo;
       this.nombre = nombre;
    }
   


    @Column(name="ALIAS", nullable=false, length=255)
    public String getAlias() {
        return this.alias;
    }
    
    public void setAlias(String alias) {
        this.alias = alias;
    }


    @Column(name="IDMODELO", nullable=false)
    public byte[] getIdmodelo() {
        return this.idmodelo;
    }
    
    public void setIdmodelo(byte[] idmodelo) {
        this.idmodelo = idmodelo;
    }


    @Column(name="NOMBRE", nullable=false, length=255)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VhcModeloaliasViewId) ) return false;
		 VhcModeloaliasViewId castOther = ( VhcModeloaliasViewId ) other; 
         
		 return ( (this.getAlias()==castOther.getAlias()) || ( this.getAlias()!=null && castOther.getAlias()!=null && this.getAlias().equals(castOther.getAlias()) ) )
 && ( (this.getIdmodelo()==castOther.getIdmodelo()) || ( this.getIdmodelo()!=null && castOther.getIdmodelo()!=null && Arrays.equals(this.getIdmodelo(), castOther.getIdmodelo()) ) )
 && ( (this.getNombre()==castOther.getNombre()) || ( this.getNombre()!=null && castOther.getNombre()!=null && this.getNombre().equals(castOther.getNombre()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + ( getAlias() == null ? 0 : this.getAlias().hashCode() );
        int idmodeloHashcode = 0;
         byte[] idmodeloProperty = this.getIdmodelo();
         if(idmodeloProperty != null) {
             idmodeloHashcode = 1;
             for (int i=0; i<idmodeloProperty.length; i++) {
                 idmodeloHashcode = 37 * idmodeloHashcode + idmodeloProperty[i];
             }
         }

         result = 37 * result + idmodeloHashcode;

        result = 37 * result + ( getNombre() == null ? 0 : this.getNombre().hashCode() );
         return result;
   }   


}


