package com.organizame.reportes.entity;
// Generated 6 nov 2025 15:47:18 by Hibernate Tools 6.6.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * VhcModeloperiodoventausa generated by hbm2java
 */
@Entity
@Table(name="vhc_modeloperiodoventausa"
)
public class VhcModeloperiodoventausa  implements java.io.Serializable {


     private byte[] idmodeloperiodoventausa;
     private VhcModelo vhcModelo;
     private int periodoanio;
     private int periodotrimestre;
     private int cantidad;

    public VhcModeloperiodoventausa() {
    }

	
    public VhcModeloperiodoventausa(byte[] idmodeloperiodoventausa, int periodoanio, int periodotrimestre, int cantidad) {
        this.idmodeloperiodoventausa = idmodeloperiodoventausa;
        this.periodoanio = periodoanio;
        this.periodotrimestre = periodotrimestre;
        this.cantidad = cantidad;
    }
    public VhcModeloperiodoventausa(byte[] idmodeloperiodoventausa, VhcModelo vhcModelo, int periodoanio, int periodotrimestre, int cantidad) {
       this.idmodeloperiodoventausa = idmodeloperiodoventausa;
       this.vhcModelo = vhcModelo;
       this.periodoanio = periodoanio;
       this.periodotrimestre = periodotrimestre;
       this.cantidad = cantidad;
    }
   
     @Id 

    
    @Column(name="IDMODELOPERIODOVENTAUSA", unique=true, nullable=false)
    public byte[] getIdmodeloperiodoventausa() {
        return this.idmodeloperiodoventausa;
    }
    
    public void setIdmodeloperiodoventausa(byte[] idmodeloperiodoventausa) {
        this.idmodeloperiodoventausa = idmodeloperiodoventausa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDMODELO")
    public VhcModelo getVhcModelo() {
        return this.vhcModelo;
    }
    
    public void setVhcModelo(VhcModelo vhcModelo) {
        this.vhcModelo = vhcModelo;
    }

    
    @Column(name="PERIODOANIO", nullable=false)
    public int getPeriodoanio() {
        return this.periodoanio;
    }
    
    public void setPeriodoanio(int periodoanio) {
        this.periodoanio = periodoanio;
    }

    
    @Column(name="PERIODOTRIMESTRE", nullable=false)
    public int getPeriodotrimestre() {
        return this.periodotrimestre;
    }
    
    public void setPeriodotrimestre(int periodotrimestre) {
        this.periodotrimestre = periodotrimestre;
    }

    
    @Column(name="CANTIDAD", nullable=false)
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }




}


