package com.organizame.reportes.entity;
// Generated 6 nov 2025 15:47:18 by Hibernate Tools 6.6.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * VhcMarcaarchivo generated by hbm2java
 */
@Entity
@Table(name="vhc_marcaarchivo"
)
public class VhcMarcaarchivo  implements java.io.Serializable {


     private byte[] idmarcaarchivo;
     private VhcMarca vhcMarca;
     private String archivo;
     private byte[] idmarcaarchivotipo;

    public VhcMarcaarchivo() {
    }

	
    public VhcMarcaarchivo(byte[] idmarcaarchivo) {
        this.idmarcaarchivo = idmarcaarchivo;
    }
    public VhcMarcaarchivo(byte[] idmarcaarchivo, VhcMarca vhcMarca, String archivo, byte[] idmarcaarchivotipo) {
       this.idmarcaarchivo = idmarcaarchivo;
       this.vhcMarca = vhcMarca;
       this.archivo = archivo;
       this.idmarcaarchivotipo = idmarcaarchivotipo;
    }
   
     @Id 

    
    @Column(name="IDMARCAARCHIVO", unique=true, nullable=false)
    public byte[] getIdmarcaarchivo() {
        return this.idmarcaarchivo;
    }
    
    public void setIdmarcaarchivo(byte[] idmarcaarchivo) {
        this.idmarcaarchivo = idmarcaarchivo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDMARCA")
    public VhcMarca getVhcMarca() {
        return this.vhcMarca;
    }
    
    public void setVhcMarca(VhcMarca vhcMarca) {
        this.vhcMarca = vhcMarca;
    }

    
    @Column(name="ARCHIVO", length=255)
    public String getArchivo() {
        return this.archivo;
    }
    
    public void setArchivo(String archivo) {
        this.archivo = archivo;
    }

    
    @Column(name="IDMARCAARCHIVOTIPO")
    public byte[] getIdmarcaarchivotipo() {
        return this.idmarcaarchivotipo;
    }
    
    public void setIdmarcaarchivotipo(byte[] idmarcaarchivotipo) {
        this.idmarcaarchivotipo = idmarcaarchivotipo;
    }




}


