package com.organizame.reportes.entity;
// Generated 6 nov 2025 15:47:18 by Hibernate Tools 6.6.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import lombok.Data;

/**
 * VhcMarca generated by hbm2java
 */
@Data
@Entity
@Table(name="vhc_marca"
    , uniqueConstraints = @UniqueConstraint(columnNames="NOMBRE") 
)
public class VhcMarca  implements java.io.Serializable {

    @Id
    @Column(name="IDMARCA", unique=true, nullable=false,columnDefinition = "BINARY(255)")
     private byte[] idmarca;
    @Column(name="NOMBRE", unique=true, nullable=false, length=255)
     private String nombre;
    @Column(name="ORDEN", nullable=false)
     private int orden;
}


