package com.organizame.reportes.entity;
// Generated 6 nov 2025 15:47:18 by Hibernate Tools 6.6.3.Final


import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

/**
 * VhcModeloaliasView generated by hbm2java
 */
@Entity
@Table(name="vhc_modeloalias_view"
)
public class VhcModeloaliasView  implements java.io.Serializable {


     private VhcModeloaliasViewId id;

    public VhcModeloaliasView() {
    }

    public VhcModeloaliasView(VhcModeloaliasViewId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="alias", column=@Column(name="ALIAS", nullable=false, length=255) ), 
        @AttributeOverride(name="idmodelo", column=@Column(name="IDMODELO", nullable=false) ), 
        @AttributeOverride(name="nombre", column=@Column(name="NOMBRE", nullable=false, length=255) ) } )
    public VhcModeloaliasViewId getId() {
        return this.id;
    }
    
    public void setId(VhcModeloaliasViewId id) {
        this.id = id;
    }




}


