package com.organizame.reportes.entity;
// Generated 6 nov 2025 15:47:18 by Hibernate Tools 6.6.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import java.util.HashSet;
import java.util.Set;

/**
 * VhcModelo generated by hbm2java
 */
@Entity
@Table(name="vhc_modelo"
    , uniqueConstraints = @UniqueConstraint(columnNames={"IDMARCA", "NOMBRE"}) 
)
public class VhcModelo  implements java.io.Serializable {


     private byte[] idmodelo;
     private VhcMarca vhcMarca;
     private String nombre;
     private Set vhcVersions = new HashSet(0);
     private Set vhcModeloperiodoventausas = new HashSet(0);
     private Set vhcModeloaliases = new HashSet(0);
     private Set vhcModeloperiodos = new HashSet(0);
     private Set vhcModeloperiodoindustrias = new HashSet(0);
     private Set vhcModeloperiodoinegis = new HashSet(0);

    public VhcModelo() {
    }

	
    public VhcModelo(byte[] idmodelo, String nombre) {
        this.idmodelo = idmodelo;
        this.nombre = nombre;
    }
    public VhcModelo(byte[] idmodelo, VhcMarca vhcMarca, String nombre, Set vhcVersions, Set vhcModeloperiodoventausas, Set vhcModeloaliases, Set vhcModeloperiodos, Set vhcModeloperiodoindustrias, Set vhcModeloperiodoinegis) {
       this.idmodelo = idmodelo;
       this.vhcMarca = vhcMarca;
       this.nombre = nombre;
       this.vhcVersions = vhcVersions;
       this.vhcModeloperiodoventausas = vhcModeloperiodoventausas;
       this.vhcModeloaliases = vhcModeloaliases;
       this.vhcModeloperiodos = vhcModeloperiodos;
       this.vhcModeloperiodoindustrias = vhcModeloperiodoindustrias;
       this.vhcModeloperiodoinegis = vhcModeloperiodoinegis;
    }
   
     @Id 

    
    @Column(name="IDMODELO", unique=true, nullable=false)
    public byte[] getIdmodelo() {
        return this.idmodelo;
    }
    
    public void setIdmodelo(byte[] idmodelo) {
        this.idmodelo = idmodelo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDMARCA")
    public VhcMarca getVhcMarca() {
        return this.vhcMarca;
    }
    
    public void setVhcMarca(VhcMarca vhcMarca) {
        this.vhcMarca = vhcMarca;
    }

    
    @Column(name="NOMBRE", nullable=false, length=255)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vhcModelo")
    public Set getVhcVersions() {
        return this.vhcVersions;
    }
    
    public void setVhcVersions(Set vhcVersions) {
        this.vhcVersions = vhcVersions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vhcModelo")
    public Set getVhcModeloperiodoventausas() {
        return this.vhcModeloperiodoventausas;
    }
    
    public void setVhcModeloperiodoventausas(Set vhcModeloperiodoventausas) {
        this.vhcModeloperiodoventausas = vhcModeloperiodoventausas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vhcModelo")
    public Set getVhcModeloaliases() {
        return this.vhcModeloaliases;
    }
    
    public void setVhcModeloaliases(Set vhcModeloaliases) {
        this.vhcModeloaliases = vhcModeloaliases;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vhcModelo")
    public Set getVhcModeloperiodos() {
        return this.vhcModeloperiodos;
    }
    
    public void setVhcModeloperiodos(Set vhcModeloperiodos) {
        this.vhcModeloperiodos = vhcModeloperiodos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vhcModelo")
    public Set getVhcModeloperiodoindustrias() {
        return this.vhcModeloperiodoindustrias;
    }
    
    public void setVhcModeloperiodoindustrias(Set vhcModeloperiodoindustrias) {
        this.vhcModeloperiodoindustrias = vhcModeloperiodoindustrias;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vhcModelo")
    public Set getVhcModeloperiodoinegis() {
        return this.vhcModeloperiodoinegis;
    }
    
    public void setVhcModeloperiodoinegis(Set vhcModeloperiodoinegis) {
        this.vhcModeloperiodoinegis = vhcModeloperiodoinegis;
    }




}


