package com.organizame.reportes.entity;
// Generated 6 nov 2025 15:47:18 by Hibernate Tools 6.6.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * VhcModeloperiodoinegi generated by hbm2java
 */
@Entity
@Table(name="vhc_modeloperiodoinegi"
)
public class VhcModeloperiodoinegi  implements java.io.Serializable {


     private byte[] idmodeloperiodoinegi;
     private VhcModelo vhcModelo;
     private int periodoanio;
     private int periodomes;
     private byte[] idorigen;
     private int cantidad;

    public VhcModeloperiodoinegi() {
    }

	
    public VhcModeloperiodoinegi(byte[] idmodeloperiodoinegi, int periodoanio, int periodomes, int cantidad) {
        this.idmodeloperiodoinegi = idmodeloperiodoinegi;
        this.periodoanio = periodoanio;
        this.periodomes = periodomes;
        this.cantidad = cantidad;
    }
    public VhcModeloperiodoinegi(byte[] idmodeloperiodoinegi, VhcModelo vhcModelo, int periodoanio, int periodomes, byte[] idorigen, int cantidad) {
       this.idmodeloperiodoinegi = idmodeloperiodoinegi;
       this.vhcModelo = vhcModelo;
       this.periodoanio = periodoanio;
       this.periodomes = periodomes;
       this.idorigen = idorigen;
       this.cantidad = cantidad;
    }
   
     @Id 

    
    @Column(name="IDMODELOPERIODOINEGI", unique=true, nullable=false)
    public byte[] getIdmodeloperiodoinegi() {
        return this.idmodeloperiodoinegi;
    }
    
    public void setIdmodeloperiodoinegi(byte[] idmodeloperiodoinegi) {
        this.idmodeloperiodoinegi = idmodeloperiodoinegi;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDMODELO")
    public VhcModelo getVhcModelo() {
        return this.vhcModelo;
    }
    
    public void setVhcModelo(VhcModelo vhcModelo) {
        this.vhcModelo = vhcModelo;
    }

    
    @Column(name="PERIODOANIO", nullable=false)
    public int getPeriodoanio() {
        return this.periodoanio;
    }
    
    public void setPeriodoanio(int periodoanio) {
        this.periodoanio = periodoanio;
    }

    
    @Column(name="PERIODOMES", nullable=false)
    public int getPeriodomes() {
        return this.periodomes;
    }
    
    public void setPeriodomes(int periodomes) {
        this.periodomes = periodomes;
    }

    
    @Column(name="IDORIGEN")
    public byte[] getIdorigen() {
        return this.idorigen;
    }
    
    public void setIdorigen(byte[] idorigen) {
        this.idorigen = idorigen;
    }

    
    @Column(name="CANTIDAD", nullable=false)
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }




}


