package com.organizame.reportes.entity;
// Generated 6 nov 2025 15:47:18 by Hibernate Tools 6.6.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * VhcMarcaperiodo generated by hbm2java
 */
@Entity
@Table(name="vhc_marcaperiodo"
)
public class VhcMarcaperiodo  implements java.io.Serializable {


     private byte[] idmarcaperiodo;
     private VhcMarca vhcMarca;
     private int periodoanio;
     private int periodomes;
     private int ventapuntos;

    public VhcMarcaperiodo() {
    }

	
    public VhcMarcaperiodo(byte[] idmarcaperiodo, int periodoanio, int periodomes, int ventapuntos) {
        this.idmarcaperiodo = idmarcaperiodo;
        this.periodoanio = periodoanio;
        this.periodomes = periodomes;
        this.ventapuntos = ventapuntos;
    }
    public VhcMarcaperiodo(byte[] idmarcaperiodo, VhcMarca vhcMarca, int periodoanio, int periodomes, int ventapuntos) {
       this.idmarcaperiodo = idmarcaperiodo;
       this.vhcMarca = vhcMarca;
       this.periodoanio = periodoanio;
       this.periodomes = periodomes;
       this.ventapuntos = ventapuntos;
    }
   
     @Id 

    
    @Column(name="IDMARCAPERIODO", unique=true, nullable=false)
    public byte[] getIdmarcaperiodo() {
        return this.idmarcaperiodo;
    }
    
    public void setIdmarcaperiodo(byte[] idmarcaperiodo) {
        this.idmarcaperiodo = idmarcaperiodo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDMARCA")
    public VhcMarca getVhcMarca() {
        return this.vhcMarca;
    }
    
    public void setVhcMarca(VhcMarca vhcMarca) {
        this.vhcMarca = vhcMarca;
    }

    
    @Column(name="PERIODOANIO", nullable=false)
    public int getPeriodoanio() {
        return this.periodoanio;
    }
    
    public void setPeriodoanio(int periodoanio) {
        this.periodoanio = periodoanio;
    }

    
    @Column(name="PERIODOMES", nullable=false)
    public int getPeriodomes() {
        return this.periodomes;
    }
    
    public void setPeriodomes(int periodomes) {
        this.periodomes = periodomes;
    }

    
    @Column(name="VENTAPUNTOS", nullable=false)
    public int getVentapuntos() {
        return this.ventapuntos;
    }
    
    public void setVentapuntos(int ventapuntos) {
        this.ventapuntos = ventapuntos;
    }




}


