package com.organizame.reportes.entity;
// Generated 6 nov 2025 15:47:18 by Hibernate Tools 6.6.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * VhcOrigen generated by hbm2java
 */
@Entity
@Table(name="vhc_origen"
    , uniqueConstraints = {@UniqueConstraint(columnNames="CLAVE"), @UniqueConstraint(columnNames="NOMBRE")} 
)
public class VhcOrigen  implements java.io.Serializable {


     private byte[] idorigen;
     private String nombre;
     private String clave;
     private int orden;

    public VhcOrigen() {
    }

    public VhcOrigen(byte[] idorigen, String nombre, String clave, int orden) {
       this.idorigen = idorigen;
       this.nombre = nombre;
       this.clave = clave;
       this.orden = orden;
    }
   
     @Id 

    
    @Column(name="IDORIGEN", unique=true, nullable=false)
    public byte[] getIdorigen() {
        return this.idorigen;
    }
    
    public void setIdorigen(byte[] idorigen) {
        this.idorigen = idorigen;
    }

    
    @Column(name="NOMBRE", unique=true, nullable=false, length=255)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="CLAVE", unique=true, nullable=false, length=255)
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }

    
    @Column(name="ORDEN", nullable=false)
    public int getOrden() {
        return this.orden;
    }
    
    public void setOrden(int orden) {
        this.orden = orden;
    }




}


