package com.organizame.reportes.entity;
// Generated 6 nov 2025 15:47:18 by Hibernate Tools 6.6.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.math.BigDecimal;
import java.sql.Timestamp;

/**
 * VhcPeriodo generated by hbm2java
 */
@Entity
@Table(name="vhc_periodo"
)
public class VhcPeriodo  implements java.io.Serializable {


     private byte[] idperiodo;
     private VhcAnio vhcAnio;
     private int periodoanio;
     private int periodomes;
     private Timestamp fechainicio;
     private Timestamp fechafin;
     private int sale;
     private int dealerstock;
     private int intransit;
     private int incountrystock;
     private BigDecimal preciolista;
     private BigDecimal contadodescuento;
     private BigDecimal contadoparticipaciondistribuidores;
     private BigDecimal contadototaldescuentos;
     private BigDecimal contadoprecio;
     private String contadosegurogratis;
     private BigDecimal financiamientodescuentopromocional;
     private BigDecimal financiamientoparticipaciondistribuidores;
     private BigDecimal financiamientototaldescuentos;
     private BigDecimal financiamientopreciopromocional;
     private String financiamientotasadesde;
     private String financiamientosegurogratis;
     private BigDecimal financiamientoalternodescuentopromocional;
     private BigDecimal financiamientoalternoparticipaciondistribuidores;
     private BigDecimal financiamientoalternototaldescuentos;
     private BigDecimal financiamientoalternopreciopromocional;
     private String financiamientoalternotasadesde;
     private String financiamientoalternosegurogratis;
     private String mesessinintereses;
     private BigDecimal totalmes12;
     private BigDecimal promediomes6;

    public VhcPeriodo() {
    }

	
    public VhcPeriodo(byte[] idperiodo, int periodoanio, int periodomes, int sale, int dealerstock, int intransit, int incountrystock, BigDecimal preciolista, BigDecimal contadodescuento, BigDecimal contadoparticipaciondistribuidores, BigDecimal contadototaldescuentos, BigDecimal contadoprecio, BigDecimal financiamientodescuentopromocional, BigDecimal financiamientoparticipaciondistribuidores, BigDecimal financiamientototaldescuentos, BigDecimal financiamientopreciopromocional, BigDecimal financiamientoalternodescuentopromocional, BigDecimal financiamientoalternoparticipaciondistribuidores, BigDecimal financiamientoalternototaldescuentos, BigDecimal financiamientoalternopreciopromocional, BigDecimal totalmes12, BigDecimal promediomes6) {
        this.idperiodo = idperiodo;
        this.periodoanio = periodoanio;
        this.periodomes = periodomes;
        this.sale = sale;
        this.dealerstock = dealerstock;
        this.intransit = intransit;
        this.incountrystock = incountrystock;
        this.preciolista = preciolista;
        this.contadodescuento = contadodescuento;
        this.contadoparticipaciondistribuidores = contadoparticipaciondistribuidores;
        this.contadototaldescuentos = contadototaldescuentos;
        this.contadoprecio = contadoprecio;
        this.financiamientodescuentopromocional = financiamientodescuentopromocional;
        this.financiamientoparticipaciondistribuidores = financiamientoparticipaciondistribuidores;
        this.financiamientototaldescuentos = financiamientototaldescuentos;
        this.financiamientopreciopromocional = financiamientopreciopromocional;
        this.financiamientoalternodescuentopromocional = financiamientoalternodescuentopromocional;
        this.financiamientoalternoparticipaciondistribuidores = financiamientoalternoparticipaciondistribuidores;
        this.financiamientoalternototaldescuentos = financiamientoalternototaldescuentos;
        this.financiamientoalternopreciopromocional = financiamientoalternopreciopromocional;
        this.totalmes12 = totalmes12;
        this.promediomes6 = promediomes6;
    }
    public VhcPeriodo(byte[] idperiodo, VhcAnio vhcAnio, int periodoanio, int periodomes, Timestamp fechainicio, Timestamp fechafin, int sale, int dealerstock, int intransit, int incountrystock, BigDecimal preciolista, BigDecimal contadodescuento, BigDecimal contadoparticipaciondistribuidores, BigDecimal contadototaldescuentos, BigDecimal contadoprecio, String contadosegurogratis, BigDecimal financiamientodescuentopromocional, BigDecimal financiamientoparticipaciondistribuidores, BigDecimal financiamientototaldescuentos, BigDecimal financiamientopreciopromocional, String financiamientotasadesde, String financiamientosegurogratis, BigDecimal financiamientoalternodescuentopromocional, BigDecimal financiamientoalternoparticipaciondistribuidores, BigDecimal financiamientoalternototaldescuentos, BigDecimal financiamientoalternopreciopromocional, String financiamientoalternotasadesde, String financiamientoalternosegurogratis, String mesessinintereses, BigDecimal totalmes12, BigDecimal promediomes6) {
       this.idperiodo = idperiodo;
       this.vhcAnio = vhcAnio;
       this.periodoanio = periodoanio;
       this.periodomes = periodomes;
       this.fechainicio = fechainicio;
       this.fechafin = fechafin;
       this.sale = sale;
       this.dealerstock = dealerstock;
       this.intransit = intransit;
       this.incountrystock = incountrystock;
       this.preciolista = preciolista;
       this.contadodescuento = contadodescuento;
       this.contadoparticipaciondistribuidores = contadoparticipaciondistribuidores;
       this.contadototaldescuentos = contadototaldescuentos;
       this.contadoprecio = contadoprecio;
       this.contadosegurogratis = contadosegurogratis;
       this.financiamientodescuentopromocional = financiamientodescuentopromocional;
       this.financiamientoparticipaciondistribuidores = financiamientoparticipaciondistribuidores;
       this.financiamientototaldescuentos = financiamientototaldescuentos;
       this.financiamientopreciopromocional = financiamientopreciopromocional;
       this.financiamientotasadesde = financiamientotasadesde;
       this.financiamientosegurogratis = financiamientosegurogratis;
       this.financiamientoalternodescuentopromocional = financiamientoalternodescuentopromocional;
       this.financiamientoalternoparticipaciondistribuidores = financiamientoalternoparticipaciondistribuidores;
       this.financiamientoalternototaldescuentos = financiamientoalternototaldescuentos;
       this.financiamientoalternopreciopromocional = financiamientoalternopreciopromocional;
       this.financiamientoalternotasadesde = financiamientoalternotasadesde;
       this.financiamientoalternosegurogratis = financiamientoalternosegurogratis;
       this.mesessinintereses = mesessinintereses;
       this.totalmes12 = totalmes12;
       this.promediomes6 = promediomes6;
    }
   
     @Id 

    
    @Column(name="IDPERIODO", unique=true, nullable=false)
    public byte[] getIdperiodo() {
        return this.idperiodo;
    }
    
    public void setIdperiodo(byte[] idperiodo) {
        this.idperiodo = idperiodo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDANIO")
    public VhcAnio getVhcAnio() {
        return this.vhcAnio;
    }
    
    public void setVhcAnio(VhcAnio vhcAnio) {
        this.vhcAnio = vhcAnio;
    }

    
    @Column(name="PERIODOANIO", nullable=false)
    public int getPeriodoanio() {
        return this.periodoanio;
    }
    
    public void setPeriodoanio(int periodoanio) {
        this.periodoanio = periodoanio;
    }

    
    @Column(name="PERIODOMES", nullable=false)
    public int getPeriodomes() {
        return this.periodomes;
    }
    
    public void setPeriodomes(int periodomes) {
        this.periodomes = periodomes;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECHAINICIO", length=19)
    public Timestamp getFechainicio() {
        return this.fechainicio;
    }
    
    public void setFechainicio(Timestamp fechainicio) {
        this.fechainicio = fechainicio;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FECHAFIN", length=19)
    public Timestamp getFechafin() {
        return this.fechafin;
    }
    
    public void setFechafin(Timestamp fechafin) {
        this.fechafin = fechafin;
    }

    
    @Column(name="SALE", nullable=false)
    public int getSale() {
        return this.sale;
    }
    
    public void setSale(int sale) {
        this.sale = sale;
    }

    
    @Column(name="DEALERSTOCK", nullable=false)
    public int getDealerstock() {
        return this.dealerstock;
    }
    
    public void setDealerstock(int dealerstock) {
        this.dealerstock = dealerstock;
    }

    
    @Column(name="INTRANSIT", nullable=false)
    public int getIntransit() {
        return this.intransit;
    }
    
    public void setIntransit(int intransit) {
        this.intransit = intransit;
    }

    
    @Column(name="INCOUNTRYSTOCK", nullable=false)
    public int getIncountrystock() {
        return this.incountrystock;
    }
    
    public void setIncountrystock(int incountrystock) {
        this.incountrystock = incountrystock;
    }

    
    @Column(name="PRECIOLISTA", nullable=false, precision=65, scale=2)
    public BigDecimal getPreciolista() {
        return this.preciolista;
    }
    
    public void setPreciolista(BigDecimal preciolista) {
        this.preciolista = preciolista;
    }

    
    @Column(name="CONTADODESCUENTO", nullable=false, precision=65, scale=2)
    public BigDecimal getContadodescuento() {
        return this.contadodescuento;
    }
    
    public void setContadodescuento(BigDecimal contadodescuento) {
        this.contadodescuento = contadodescuento;
    }

    
    @Column(name="CONTADOPARTICIPACIONDISTRIBUIDORES", nullable=false, precision=65, scale=2)
    public BigDecimal getContadoparticipaciondistribuidores() {
        return this.contadoparticipaciondistribuidores;
    }
    
    public void setContadoparticipaciondistribuidores(BigDecimal contadoparticipaciondistribuidores) {
        this.contadoparticipaciondistribuidores = contadoparticipaciondistribuidores;
    }

    
    @Column(name="CONTADOTOTALDESCUENTOS", nullable=false, precision=65, scale=2)
    public BigDecimal getContadototaldescuentos() {
        return this.contadototaldescuentos;
    }
    
    public void setContadototaldescuentos(BigDecimal contadototaldescuentos) {
        this.contadototaldescuentos = contadototaldescuentos;
    }

    
    @Column(name="CONTADOPRECIO", nullable=false, precision=65, scale=2)
    public BigDecimal getContadoprecio() {
        return this.contadoprecio;
    }
    
    public void setContadoprecio(BigDecimal contadoprecio) {
        this.contadoprecio = contadoprecio;
    }

    
    @Column(name="CONTADOSEGUROGRATIS", length=255)
    public String getContadosegurogratis() {
        return this.contadosegurogratis;
    }
    
    public void setContadosegurogratis(String contadosegurogratis) {
        this.contadosegurogratis = contadosegurogratis;
    }

    
    @Column(name="FINANCIAMIENTODESCUENTOPROMOCIONAL", nullable=false, precision=65, scale=2)
    public BigDecimal getFinanciamientodescuentopromocional() {
        return this.financiamientodescuentopromocional;
    }
    
    public void setFinanciamientodescuentopromocional(BigDecimal financiamientodescuentopromocional) {
        this.financiamientodescuentopromocional = financiamientodescuentopromocional;
    }

    
    @Column(name="FINANCIAMIENTOPARTICIPACIONDISTRIBUIDORES", nullable=false, precision=65, scale=2)
    public BigDecimal getFinanciamientoparticipaciondistribuidores() {
        return this.financiamientoparticipaciondistribuidores;
    }
    
    public void setFinanciamientoparticipaciondistribuidores(BigDecimal financiamientoparticipaciondistribuidores) {
        this.financiamientoparticipaciondistribuidores = financiamientoparticipaciondistribuidores;
    }

    
    @Column(name="FINANCIAMIENTOTOTALDESCUENTOS", nullable=false, precision=65, scale=2)
    public BigDecimal getFinanciamientototaldescuentos() {
        return this.financiamientototaldescuentos;
    }
    
    public void setFinanciamientototaldescuentos(BigDecimal financiamientototaldescuentos) {
        this.financiamientototaldescuentos = financiamientototaldescuentos;
    }

    
    @Column(name="FINANCIAMIENTOPRECIOPROMOCIONAL", nullable=false, precision=65, scale=2)
    public BigDecimal getFinanciamientopreciopromocional() {
        return this.financiamientopreciopromocional;
    }
    
    public void setFinanciamientopreciopromocional(BigDecimal financiamientopreciopromocional) {
        this.financiamientopreciopromocional = financiamientopreciopromocional;
    }

    
    @Column(name="FINANCIAMIENTOTASADESDE", length=255)
    public String getFinanciamientotasadesde() {
        return this.financiamientotasadesde;
    }
    
    public void setFinanciamientotasadesde(String financiamientotasadesde) {
        this.financiamientotasadesde = financiamientotasadesde;
    }

    
    @Column(name="FINANCIAMIENTOSEGUROGRATIS", length=255)
    public String getFinanciamientosegurogratis() {
        return this.financiamientosegurogratis;
    }
    
    public void setFinanciamientosegurogratis(String financiamientosegurogratis) {
        this.financiamientosegurogratis = financiamientosegurogratis;
    }

    
    @Column(name="FINANCIAMIENTOALTERNODESCUENTOPROMOCIONAL", nullable=false, precision=65, scale=2)
    public BigDecimal getFinanciamientoalternodescuentopromocional() {
        return this.financiamientoalternodescuentopromocional;
    }
    
    public void setFinanciamientoalternodescuentopromocional(BigDecimal financiamientoalternodescuentopromocional) {
        this.financiamientoalternodescuentopromocional = financiamientoalternodescuentopromocional;
    }

    
    @Column(name="FINANCIAMIENTOALTERNOPARTICIPACIONDISTRIBUIDORES", nullable=false, precision=65, scale=2)
    public BigDecimal getFinanciamientoalternoparticipaciondistribuidores() {
        return this.financiamientoalternoparticipaciondistribuidores;
    }
    
    public void setFinanciamientoalternoparticipaciondistribuidores(BigDecimal financiamientoalternoparticipaciondistribuidores) {
        this.financiamientoalternoparticipaciondistribuidores = financiamientoalternoparticipaciondistribuidores;
    }

    
    @Column(name="FINANCIAMIENTOALTERNOTOTALDESCUENTOS", nullable=false, precision=65, scale=2)
    public BigDecimal getFinanciamientoalternototaldescuentos() {
        return this.financiamientoalternototaldescuentos;
    }
    
    public void setFinanciamientoalternototaldescuentos(BigDecimal financiamientoalternototaldescuentos) {
        this.financiamientoalternototaldescuentos = financiamientoalternototaldescuentos;
    }

    
    @Column(name="FINANCIAMIENTOALTERNOPRECIOPROMOCIONAL", nullable=false, precision=65, scale=2)
    public BigDecimal getFinanciamientoalternopreciopromocional() {
        return this.financiamientoalternopreciopromocional;
    }
    
    public void setFinanciamientoalternopreciopromocional(BigDecimal financiamientoalternopreciopromocional) {
        this.financiamientoalternopreciopromocional = financiamientoalternopreciopromocional;
    }

    
    @Column(name="FINANCIAMIENTOALTERNOTASADESDE", length=255)
    public String getFinanciamientoalternotasadesde() {
        return this.financiamientoalternotasadesde;
    }
    
    public void setFinanciamientoalternotasadesde(String financiamientoalternotasadesde) {
        this.financiamientoalternotasadesde = financiamientoalternotasadesde;
    }

    
    @Column(name="FINANCIAMIENTOALTERNOSEGUROGRATIS", length=255)
    public String getFinanciamientoalternosegurogratis() {
        return this.financiamientoalternosegurogratis;
    }
    
    public void setFinanciamientoalternosegurogratis(String financiamientoalternosegurogratis) {
        this.financiamientoalternosegurogratis = financiamientoalternosegurogratis;
    }

    
    @Column(name="MESESSININTERESES", length=255)
    public String getMesessinintereses() {
        return this.mesessinintereses;
    }
    
    public void setMesessinintereses(String mesessinintereses) {
        this.mesessinintereses = mesessinintereses;
    }

    
    @Column(name="TOTALMES12", nullable=false, precision=65, scale=2)
    public BigDecimal getTotalmes12() {
        return this.totalmes12;
    }
    
    public void setTotalmes12(BigDecimal totalmes12) {
        this.totalmes12 = totalmes12;
    }

    
    @Column(name="PROMEDIOMES6", nullable=false, precision=65, scale=2)
    public BigDecimal getPromediomes6() {
        return this.promediomes6;
    }
    
    public void setPromediomes6(BigDecimal promediomes6) {
        this.promediomes6 = promediomes6;
    }




}


