package com.organizame.reportes.entity;
// Generated 6 nov 2025 15:47:18 by Hibernate Tools 6.6.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;
import java.math.BigInteger;

/**
 * VhcPeriodoModeloperiodoViewId generated by hbm2java
 */
@Embeddable
public class VhcPeriodoModeloperiodoViewId  implements java.io.Serializable {


     private int flotillaespecial;
     private String marca;
     private int menudeoflotillanormal;
     private String modelo;
     private String periodo;
     private int periodoanio;
     private int periodomes;
     private BigInteger sale;

    public VhcPeriodoModeloperiodoViewId() {
    }

	
    public VhcPeriodoModeloperiodoViewId(int flotillaespecial, String marca, int menudeoflotillanormal, String modelo, int periodoanio, int periodomes) {
        this.flotillaespecial = flotillaespecial;
        this.marca = marca;
        this.menudeoflotillanormal = menudeoflotillanormal;
        this.modelo = modelo;
        this.periodoanio = periodoanio;
        this.periodomes = periodomes;
    }
    public VhcPeriodoModeloperiodoViewId(int flotillaespecial, String marca, int menudeoflotillanormal, String modelo, String periodo, int periodoanio, int periodomes, BigInteger sale) {
       this.flotillaespecial = flotillaespecial;
       this.marca = marca;
       this.menudeoflotillanormal = menudeoflotillanormal;
       this.modelo = modelo;
       this.periodo = periodo;
       this.periodoanio = periodoanio;
       this.periodomes = periodomes;
       this.sale = sale;
    }
   


    @Column(name="FLOTILLAESPECIAL", nullable=false)
    public int getFlotillaespecial() {
        return this.flotillaespecial;
    }
    
    public void setFlotillaespecial(int flotillaespecial) {
        this.flotillaespecial = flotillaespecial;
    }


    @Column(name="marca", nullable=false, length=255)
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }


    @Column(name="MENUDEOFLOTILLANORMAL", nullable=false)
    public int getMenudeoflotillanormal() {
        return this.menudeoflotillanormal;
    }
    
    public void setMenudeoflotillanormal(int menudeoflotillanormal) {
        this.menudeoflotillanormal = menudeoflotillanormal;
    }


    @Column(name="modelo", nullable=false, length=255)
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }


    @Column(name="periodo", length=14)
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }


    @Column(name="PERIODOANIO", nullable=false)
    public int getPeriodoanio() {
        return this.periodoanio;
    }
    
    public void setPeriodoanio(int periodoanio) {
        this.periodoanio = periodoanio;
    }


    @Column(name="periodomes", nullable=false)
    public int getPeriodomes() {
        return this.periodomes;
    }
    
    public void setPeriodomes(int periodomes) {
        this.periodomes = periodomes;
    }


    @Column(name="sale", precision=32, scale=0)
    public BigInteger getSale() {
        return this.sale;
    }
    
    public void setSale(BigInteger sale) {
        this.sale = sale;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VhcPeriodoModeloperiodoViewId) ) return false;
		 VhcPeriodoModeloperiodoViewId castOther = ( VhcPeriodoModeloperiodoViewId ) other; 
         
		 return (this.getFlotillaespecial()==castOther.getFlotillaespecial())
 && ( (this.getMarca()==castOther.getMarca()) || ( this.getMarca()!=null && castOther.getMarca()!=null && this.getMarca().equals(castOther.getMarca()) ) )
 && (this.getMenudeoflotillanormal()==castOther.getMenudeoflotillanormal())
 && ( (this.getModelo()==castOther.getModelo()) || ( this.getModelo()!=null && castOther.getModelo()!=null && this.getModelo().equals(castOther.getModelo()) ) )
 && ( (this.getPeriodo()==castOther.getPeriodo()) || ( this.getPeriodo()!=null && castOther.getPeriodo()!=null && this.getPeriodo().equals(castOther.getPeriodo()) ) )
 && (this.getPeriodoanio()==castOther.getPeriodoanio())
 && (this.getPeriodomes()==castOther.getPeriodomes())
 && ( (this.getSale()==castOther.getSale()) || ( this.getSale()!=null && castOther.getSale()!=null && this.getSale().equals(castOther.getSale()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + this.getFlotillaespecial();
        result = 37 * result + ( getMarca() == null ? 0 : this.getMarca().hashCode() );
        result = 37 * result + this.getMenudeoflotillanormal();
        result = 37 * result + ( getModelo() == null ? 0 : this.getModelo().hashCode() );
        result = 37 * result + ( getPeriodo() == null ? 0 : this.getPeriodo().hashCode() );
        result = 37 * result + this.getPeriodoanio();
        result = 37 * result + this.getPeriodomes();
        result = 37 * result + ( getSale() == null ? 0 : this.getSale().hashCode() );
         return result;
   }   


}


