package com.organizame.reportes.entity;
// Generated 6 nov 2025 15:47:18 by Hibernate Tools 6.6.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * VhcPeriodoVentasId generated by hbm2java
 */
@Embeddable
public class VhcPeriodoVentasId  implements java.io.Serializable {


     private String anio;
     private String marca;
     private String modelo;
     private String periodo;
     private int periodoanio;
     private int periodomes;
     private int sale;
     private String version;

    public VhcPeriodoVentasId() {
    }

	
    public VhcPeriodoVentasId(String anio, String marca, String modelo, int periodoanio, int periodomes, int sale, String version) {
        this.anio = anio;
        this.marca = marca;
        this.modelo = modelo;
        this.periodoanio = periodoanio;
        this.periodomes = periodomes;
        this.sale = sale;
        this.version = version;
    }
    public VhcPeriodoVentasId(String anio, String marca, String modelo, String periodo, int periodoanio, int periodomes, int sale, String version) {
       this.anio = anio;
       this.marca = marca;
       this.modelo = modelo;
       this.periodo = periodo;
       this.periodoanio = periodoanio;
       this.periodomes = periodomes;
       this.sale = sale;
       this.version = version;
    }
   


    @Column(name="anio", nullable=false, length=255)
    public String getAnio() {
        return this.anio;
    }
    
    public void setAnio(String anio) {
        this.anio = anio;
    }


    @Column(name="marca", nullable=false, length=255)
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }


    @Column(name="modelo", nullable=false, length=255)
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }


    @Column(name="periodo", length=14)
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }


    @Column(name="PERIODOANIO", nullable=false)
    public int getPeriodoanio() {
        return this.periodoanio;
    }
    
    public void setPeriodoanio(int periodoanio) {
        this.periodoanio = periodoanio;
    }


    @Column(name="periodomes", nullable=false)
    public int getPeriodomes() {
        return this.periodomes;
    }
    
    public void setPeriodomes(int periodomes) {
        this.periodomes = periodomes;
    }


    @Column(name="sale", nullable=false)
    public int getSale() {
        return this.sale;
    }
    
    public void setSale(int sale) {
        this.sale = sale;
    }


    @Column(name="version", nullable=false, length=255)
    public String getVersion() {
        return this.version;
    }
    
    public void setVersion(String version) {
        this.version = version;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VhcPeriodoVentasId) ) return false;
		 VhcPeriodoVentasId castOther = ( VhcPeriodoVentasId ) other; 
         
		 return ( (this.getAnio()==castOther.getAnio()) || ( this.getAnio()!=null && castOther.getAnio()!=null && this.getAnio().equals(castOther.getAnio()) ) )
 && ( (this.getMarca()==castOther.getMarca()) || ( this.getMarca()!=null && castOther.getMarca()!=null && this.getMarca().equals(castOther.getMarca()) ) )
 && ( (this.getModelo()==castOther.getModelo()) || ( this.getModelo()!=null && castOther.getModelo()!=null && this.getModelo().equals(castOther.getModelo()) ) )
 && ( (this.getPeriodo()==castOther.getPeriodo()) || ( this.getPeriodo()!=null && castOther.getPeriodo()!=null && this.getPeriodo().equals(castOther.getPeriodo()) ) )
 && (this.getPeriodoanio()==castOther.getPeriodoanio())
 && (this.getPeriodomes()==castOther.getPeriodomes())
 && (this.getSale()==castOther.getSale())
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + ( getAnio() == null ? 0 : this.getAnio().hashCode() );
        result = 37 * result + ( getMarca() == null ? 0 : this.getMarca().hashCode() );
        result = 37 * result + ( getModelo() == null ? 0 : this.getModelo().hashCode() );
        result = 37 * result + ( getPeriodo() == null ? 0 : this.getPeriodo().hashCode() );
        result = 37 * result + this.getPeriodoanio();
        result = 37 * result + this.getPeriodomes();
        result = 37 * result + this.getSale();
        result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         return result;
   }   


}


