package com.organizame.reportes.entity;
// Generated 6 nov 2025 15:47:18 by Hibernate Tools 6.6.3.Final


import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

/**
 * VhcPeriodoVentas generated by hbm2java
 */
@Entity
@Table(name="vhc_periodo_ventas"
)
public class VhcPeriodoVentas  implements java.io.Serializable {


     private VhcPeriodoVentasId id;

    public VhcPeriodoVentas() {
    }

    public VhcPeriodoVentas(VhcPeriodoVentasId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="anio", column=@Column(name="anio", nullable=false, length=255) ), 
        @AttributeOverride(name="marca", column=@Column(name="marca", nullable=false, length=255) ), 
        @AttributeOverride(name="modelo", column=@Column(name="modelo", nullable=false, length=255) ), 
        @AttributeOverride(name="periodo", column=@Column(name="periodo", length=14) ), 
        @AttributeOverride(name="periodoanio", column=@Column(name="PERIODOANIO", nullable=false) ), 
        @AttributeOverride(name="periodomes", column=@Column(name="periodomes", nullable=false) ), 
        @AttributeOverride(name="sale", column=@Column(name="sale", nullable=false) ), 
        @AttributeOverride(name="version", column=@Column(name="version", nullable=false, length=255) ) } )
    public VhcPeriodoVentasId getId() {
        return this.id;
    }
    
    public void setId(VhcPeriodoVentasId id) {
        this.id = id;
    }




}


