package com.organizame.reportes.entity;
// Generated 6 nov 2025 15:47:18 by Hibernate Tools 6.6.3.Final


import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

/**
 * VhcPeriodoModeloperiodoView generated by hbm2java
 */
@Entity
@Table(name="vhc_periodo_modeloperiodo_view"
)
public class VhcPeriodoModeloperiodoView  implements java.io.Serializable {


     private VhcPeriodoModeloperiodoViewId id;

    public VhcPeriodoModeloperiodoView() {
    }

    public VhcPeriodoModeloperiodoView(VhcPeriodoModeloperiodoViewId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="flotillaespecial", column=@Column(name="FLOTILLAESPECIAL", nullable=false) ), 
        @AttributeOverride(name="marca", column=@Column(name="marca", nullable=false, length=255) ), 
        @AttributeOverride(name="menudeoflotillanormal", column=@Column(name="MENUDEOFLOTILLANORMAL", nullable=false) ), 
        @AttributeOverride(name="modelo", column=@Column(name="modelo", nullable=false, length=255) ), 
        @AttributeOverride(name="periodo", column=@Column(name="periodo", length=14) ), 
        @AttributeOverride(name="periodoanio", column=@Column(name="PERIODOANIO", nullable=false) ), 
        @AttributeOverride(name="periodomes", column=@Column(name="periodomes", nullable=false) ), 
        @AttributeOverride(name="sale", column=@Column(name="sale", precision=32, scale=0) ) } )
    public VhcPeriodoModeloperiodoViewId getId() {
        return this.id;
    }
    
    public void setId(VhcPeriodoModeloperiodoViewId id) {
        this.id = id;
    }




}


