package com.organizame.reportes.entity;
// Generated 6 nov 2025 15:47:18 by Hibernate Tools 6.6.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * VhcReddistribucionplantilla generated by hbm2java
 */
@Entity
@Table(name="vhc_reddistribucionplantilla"
)
public class VhcReddistribucionplantilla  implements java.io.Serializable {


     private byte[] idreddistribucionplantilla;
     private VhcReddistribucion vhcReddistribucion;
     private int orden;
     private String archivo;
     private byte[] idreddistribucionplantillatipo;

    public VhcReddistribucionplantilla() {
    }

	
    public VhcReddistribucionplantilla(byte[] idreddistribucionplantilla, int orden) {
        this.idreddistribucionplantilla = idreddistribucionplantilla;
        this.orden = orden;
    }
    public VhcReddistribucionplantilla(byte[] idreddistribucionplantilla, VhcReddistribucion vhcReddistribucion, int orden, String archivo, byte[] idreddistribucionplantillatipo) {
       this.idreddistribucionplantilla = idreddistribucionplantilla;
       this.vhcReddistribucion = vhcReddistribucion;
       this.orden = orden;
       this.archivo = archivo;
       this.idreddistribucionplantillatipo = idreddistribucionplantillatipo;
    }
   
     @Id 

    
    @Column(name="IDREDDISTRIBUCIONPLANTILLA", unique=true, nullable=false)
    public byte[] getIdreddistribucionplantilla() {
        return this.idreddistribucionplantilla;
    }
    
    public void setIdreddistribucionplantilla(byte[] idreddistribucionplantilla) {
        this.idreddistribucionplantilla = idreddistribucionplantilla;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDREDDISTRIBUCION")
    public VhcReddistribucion getVhcReddistribucion() {
        return this.vhcReddistribucion;
    }
    
    public void setVhcReddistribucion(VhcReddistribucion vhcReddistribucion) {
        this.vhcReddistribucion = vhcReddistribucion;
    }

    
    @Column(name="ORDEN", nullable=false)
    public int getOrden() {
        return this.orden;
    }
    
    public void setOrden(int orden) {
        this.orden = orden;
    }

    
    @Column(name="ARCHIVO", length=255)
    public String getArchivo() {
        return this.archivo;
    }
    
    public void setArchivo(String archivo) {
        this.archivo = archivo;
    }

    
    @Column(name="IDREDDISTRIBUCIONPLANTILLATIPO")
    public byte[] getIdreddistribucionplantillatipo() {
        return this.idreddistribucionplantillatipo;
    }
    
    public void setIdreddistribucionplantillatipo(byte[] idreddistribucionplantillatipo) {
        this.idreddistribucionplantillatipo = idreddistribucionplantillatipo;
    }




}


