package com.organizame.reportes.entity;
// Generated 6 nov 2025 15:47:18 by Hibernate Tools 6.6.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import java.util.HashSet;
import java.util.Set;

/**
 * VhcReddistribucion generated by hbm2java
 */
@Entity
@Table(name="vhc_reddistribucion"
    , uniqueConstraints = {@UniqueConstraint(columnNames="CLAVE"), @UniqueConstraint(columnNames="NOMBRE")} 
)
public class VhcReddistribucion  implements java.io.Serializable {


     private byte[] idreddistribucion;
     private String nombre;
     private String clave;
     private Set vhcReddistribucionplantillas = new HashSet(0);
     private Set vhcReddistribucionarchivos = new HashSet(0);
     private Set vhcReddistribucionversions = new HashSet(0);
     private Set vhcReddistribucionmodelos = new HashSet(0);

    public VhcReddistribucion() {
    }

	
    public VhcReddistribucion(byte[] idreddistribucion, String nombre, String clave) {
        this.idreddistribucion = idreddistribucion;
        this.nombre = nombre;
        this.clave = clave;
    }
    public VhcReddistribucion(byte[] idreddistribucion, String nombre, String clave, Set vhcReddistribucionplantillas, Set vhcReddistribucionarchivos, Set vhcReddistribucionversions, Set vhcReddistribucionmodelos) {
       this.idreddistribucion = idreddistribucion;
       this.nombre = nombre;
       this.clave = clave;
       this.vhcReddistribucionplantillas = vhcReddistribucionplantillas;
       this.vhcReddistribucionarchivos = vhcReddistribucionarchivos;
       this.vhcReddistribucionversions = vhcReddistribucionversions;
       this.vhcReddistribucionmodelos = vhcReddistribucionmodelos;
    }
   
     @Id 

    
    @Column(name="IDREDDISTRIBUCION", unique=true, nullable=false)
    public byte[] getIdreddistribucion() {
        return this.idreddistribucion;
    }
    
    public void setIdreddistribucion(byte[] idreddistribucion) {
        this.idreddistribucion = idreddistribucion;
    }

    
    @Column(name="NOMBRE", unique=true, nullable=false, length=255)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="CLAVE", unique=true, nullable=false, length=255)
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vhcReddistribucion")
    public Set getVhcReddistribucionplantillas() {
        return this.vhcReddistribucionplantillas;
    }
    
    public void setVhcReddistribucionplantillas(Set vhcReddistribucionplantillas) {
        this.vhcReddistribucionplantillas = vhcReddistribucionplantillas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vhcReddistribucion")
    public Set getVhcReddistribucionarchivos() {
        return this.vhcReddistribucionarchivos;
    }
    
    public void setVhcReddistribucionarchivos(Set vhcReddistribucionarchivos) {
        this.vhcReddistribucionarchivos = vhcReddistribucionarchivos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vhcReddistribucion")
    public Set getVhcReddistribucionversions() {
        return this.vhcReddistribucionversions;
    }
    
    public void setVhcReddistribucionversions(Set vhcReddistribucionversions) {
        this.vhcReddistribucionversions = vhcReddistribucionversions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vhcReddistribucion")
    public Set getVhcReddistribucionmodelos() {
        return this.vhcReddistribucionmodelos;
    }
    
    public void setVhcReddistribucionmodelos(Set vhcReddistribucionmodelos) {
        this.vhcReddistribucionmodelos = vhcReddistribucionmodelos;
    }




}


