package com.organizame.reportes.entity;
// Generated 6 nov 2025 15:47:18 by Hibernate Tools 6.6.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * VhcReddistribucionversion generated by hbm2java
 */
@Entity
@Table(name="vhc_reddistribucionversion"
)
public class VhcReddistribucionversion  implements java.io.Serializable {


     private byte[] idreddistribucionversion;
     private VhcReddistribucion vhcReddistribucion;
     private byte[] idversion;

    public VhcReddistribucionversion() {
    }

	
    public VhcReddistribucionversion(byte[] idreddistribucionversion) {
        this.idreddistribucionversion = idreddistribucionversion;
    }
    public VhcReddistribucionversion(byte[] idreddistribucionversion, VhcReddistribucion vhcReddistribucion, byte[] idversion) {
       this.idreddistribucionversion = idreddistribucionversion;
       this.vhcReddistribucion = vhcReddistribucion;
       this.idversion = idversion;
    }
   
     @Id 

    
    @Column(name="IDREDDISTRIBUCIONVERSION", unique=true, nullable=false)
    public byte[] getIdreddistribucionversion() {
        return this.idreddistribucionversion;
    }
    
    public void setIdreddistribucionversion(byte[] idreddistribucionversion) {
        this.idreddistribucionversion = idreddistribucionversion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDREDDISTRIBUCION")
    public VhcReddistribucion getVhcReddistribucion() {
        return this.vhcReddistribucion;
    }
    
    public void setVhcReddistribucion(VhcReddistribucion vhcReddistribucion) {
        this.vhcReddistribucion = vhcReddistribucion;
    }

    
    @Column(name="IDVERSION")
    public byte[] getIdversion() {
        return this.idversion;
    }
    
    public void setIdversion(byte[] idversion) {
        this.idversion = idversion;
    }




}


