package com.organizame.reportes.entity;
// Generated 6 nov 2025 15:47:18 by Hibernate Tools 6.6.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * VhcReddistribucionarchivo generated by hbm2java
 */
@Entity
@Table(name="vhc_reddistribucionarchivo"
)
public class VhcReddistribucionarchivo  implements java.io.Serializable {


     private byte[] idreddistribucionarchivo;
     private VhcReddistribucion vhcReddistribucion;
     private String archivo;
     private byte[] idreddistribucionarchivotipo;

    public VhcReddistribucionarchivo() {
    }

	
    public VhcReddistribucionarchivo(byte[] idreddistribucionarchivo) {
        this.idreddistribucionarchivo = idreddistribucionarchivo;
    }
    public VhcReddistribucionarchivo(byte[] idreddistribucionarchivo, VhcReddistribucion vhcReddistribucion, String archivo, byte[] idreddistribucionarchivotipo) {
       this.idreddistribucionarchivo = idreddistribucionarchivo;
       this.vhcReddistribucion = vhcReddistribucion;
       this.archivo = archivo;
       this.idreddistribucionarchivotipo = idreddistribucionarchivotipo;
    }
   
     @Id 

    
    @Column(name="IDREDDISTRIBUCIONARCHIVO", unique=true, nullable=false)
    public byte[] getIdreddistribucionarchivo() {
        return this.idreddistribucionarchivo;
    }
    
    public void setIdreddistribucionarchivo(byte[] idreddistribucionarchivo) {
        this.idreddistribucionarchivo = idreddistribucionarchivo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDREDDISTRIBUCION")
    public VhcReddistribucion getVhcReddistribucion() {
        return this.vhcReddistribucion;
    }
    
    public void setVhcReddistribucion(VhcReddistribucion vhcReddistribucion) {
        this.vhcReddistribucion = vhcReddistribucion;
    }

    
    @Column(name="ARCHIVO", length=255)
    public String getArchivo() {
        return this.archivo;
    }
    
    public void setArchivo(String archivo) {
        this.archivo = archivo;
    }

    
    @Column(name="IDREDDISTRIBUCIONARCHIVOTIPO")
    public byte[] getIdreddistribucionarchivotipo() {
        return this.idreddistribucionarchivotipo;
    }
    
    public void setIdreddistribucionarchivotipo(byte[] idreddistribucionarchivotipo) {
        this.idreddistribucionarchivotipo = idreddistribucionarchivotipo;
    }




}


