package com.organizame.reportes.entity;
// Generated 6 nov 2025 15:47:18 by Hibernate Tools 6.6.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * VhcReddistribucionarchivotipo generated by hbm2java
 */
@Entity
@Table(name="vhc_reddistribucionarchivotipo"
    , uniqueConstraints = {@UniqueConstraint(columnNames="CLAVE"), @UniqueConstraint(columnNames="NOMBRE")} 
)
public class VhcReddistribucionarchivotipo  implements java.io.Serializable {


     private byte[] idreddistribucionarchivotipo;
     private String nombre;
     private String descripcion;
     private String clave;
     private int orden;

    public VhcReddistribucionarchivotipo() {
    }

	
    public VhcReddistribucionarchivotipo(byte[] idreddistribucionarchivotipo, String nombre, String clave, int orden) {
        this.idreddistribucionarchivotipo = idreddistribucionarchivotipo;
        this.nombre = nombre;
        this.clave = clave;
        this.orden = orden;
    }
    public VhcReddistribucionarchivotipo(byte[] idreddistribucionarchivotipo, String nombre, String descripcion, String clave, int orden) {
       this.idreddistribucionarchivotipo = idreddistribucionarchivotipo;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.clave = clave;
       this.orden = orden;
    }
   
     @Id 

    
    @Column(name="IDREDDISTRIBUCIONARCHIVOTIPO", unique=true, nullable=false)
    public byte[] getIdreddistribucionarchivotipo() {
        return this.idreddistribucionarchivotipo;
    }
    
    public void setIdreddistribucionarchivotipo(byte[] idreddistribucionarchivotipo) {
        this.idreddistribucionarchivotipo = idreddistribucionarchivotipo;
    }

    
    @Column(name="NOMBRE", unique=true, nullable=false, length=255)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="DESCRIPCION", length=2000)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="CLAVE", unique=true, nullable=false, length=255)
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }

    
    @Column(name="ORDEN", nullable=false)
    public int getOrden() {
        return this.orden;
    }
    
    public void setOrden(int orden) {
        this.orden = orden;
    }




}


