package com.organizame.reportes.entity;
// Generated 6 nov 2025 15:47:18 by Hibernate Tools 6.6.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * VhcReddistribucionmodelo generated by hbm2java
 */
@Entity
@Table(name="vhc_reddistribucionmodelo"
)
public class VhcReddistribucionmodelo  implements java.io.Serializable {


     private byte[] idreddistribucionmodelo;
     private VhcReddistribucion vhcReddistribucion;
     private byte[] idmodelo;

    public VhcReddistribucionmodelo() {
    }

	
    public VhcReddistribucionmodelo(byte[] idreddistribucionmodelo) {
        this.idreddistribucionmodelo = idreddistribucionmodelo;
    }
    public VhcReddistribucionmodelo(byte[] idreddistribucionmodelo, VhcReddistribucion vhcReddistribucion, byte[] idmodelo) {
       this.idreddistribucionmodelo = idreddistribucionmodelo;
       this.vhcReddistribucion = vhcReddistribucion;
       this.idmodelo = idmodelo;
    }
   
     @Id 

    
    @Column(name="IDREDDISTRIBUCIONMODELO", unique=true, nullable=false)
    public byte[] getIdreddistribucionmodelo() {
        return this.idreddistribucionmodelo;
    }
    
    public void setIdreddistribucionmodelo(byte[] idreddistribucionmodelo) {
        this.idreddistribucionmodelo = idreddistribucionmodelo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDREDDISTRIBUCION")
    public VhcReddistribucion getVhcReddistribucion() {
        return this.vhcReddistribucion;
    }
    
    public void setVhcReddistribucion(VhcReddistribucion vhcReddistribucion) {
        this.vhcReddistribucion = vhcReddistribucion;
    }

    
    @Column(name="IDMODELO")
    public byte[] getIdmodelo() {
        return this.idmodelo;
    }
    
    public void setIdmodelo(byte[] idmodelo) {
        this.idmodelo = idmodelo;
    }




}


