package com.organizame.reportes.entity;
// Generated 6 nov 2025 15:47:18 by Hibernate Tools 6.6.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * VhcReddistribucionplantillatipobase generated by hbm2java
 */
@Entity
@Table(name="vhc_reddistribucionplantillatipobase"
)
public class VhcReddistribucionplantillatipobase  implements java.io.Serializable {


     private byte[] idreddistribucionplantillatipobase;
     private VhcReddistribucionplantillatipo vhcReddistribucionplantillatipo;
     private String descripcion;
     private int orden;
     private String archivo;
     private String fechainicio;

    public VhcReddistribucionplantillatipobase() {
    }

	
    public VhcReddistribucionplantillatipobase(byte[] idreddistribucionplantillatipobase, int orden) {
        this.idreddistribucionplantillatipobase = idreddistribucionplantillatipobase;
        this.orden = orden;
    }
    public VhcReddistribucionplantillatipobase(byte[] idreddistribucionplantillatipobase, VhcReddistribucionplantillatipo vhcReddistribucionplantillatipo, String descripcion, int orden, String archivo, String fechainicio) {
       this.idreddistribucionplantillatipobase = idreddistribucionplantillatipobase;
       this.vhcReddistribucionplantillatipo = vhcReddistribucionplantillatipo;
       this.descripcion = descripcion;
       this.orden = orden;
       this.archivo = archivo;
       this.fechainicio = fechainicio;
    }
   
     @Id 

    
    @Column(name="IDREDDISTRIBUCIONPLANTILLATIPOBASE", unique=true, nullable=false)
    public byte[] getIdreddistribucionplantillatipobase() {
        return this.idreddistribucionplantillatipobase;
    }
    
    public void setIdreddistribucionplantillatipobase(byte[] idreddistribucionplantillatipobase) {
        this.idreddistribucionplantillatipobase = idreddistribucionplantillatipobase;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDREDDISTRIBUCIONPLANTILLATIPO")
    public VhcReddistribucionplantillatipo getVhcReddistribucionplantillatipo() {
        return this.vhcReddistribucionplantillatipo;
    }
    
    public void setVhcReddistribucionplantillatipo(VhcReddistribucionplantillatipo vhcReddistribucionplantillatipo) {
        this.vhcReddistribucionplantillatipo = vhcReddistribucionplantillatipo;
    }

    
    @Column(name="DESCRIPCION", length=2000)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="ORDEN", nullable=false)
    public int getOrden() {
        return this.orden;
    }
    
    public void setOrden(int orden) {
        this.orden = orden;
    }

    
    @Column(name="ARCHIVO", length=255)
    public String getArchivo() {
        return this.archivo;
    }
    
    public void setArchivo(String archivo) {
        this.archivo = archivo;
    }

    
    @Column(name="FECHAINICIO", length=255)
    public String getFechainicio() {
        return this.fechainicio;
    }
    
    public void setFechainicio(String fechainicio) {
        this.fechainicio = fechainicio;
    }




}


