package com.organizame.reportes.entity;
// Generated 6 nov 2025 15:47:18 by Hibernate Tools 6.6.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import java.util.HashSet;
import java.util.Set;

/**
 * VhcReddistribucionplantillatipo generated by hbm2java
 */
@Entity
@Table(name="vhc_reddistribucionplantillatipo"
    , uniqueConstraints = {@UniqueConstraint(columnNames="CLAVE"), @UniqueConstraint(columnNames="NOMBRE")} 
)
public class VhcReddistribucionplantillatipo  implements java.io.Serializable {


     private byte[] idreddistribucionplantillatipo;
     private String nombre;
     private String descripcion;
     private String clave;
     private Set vhcReddistribucionplantillatipobases = new HashSet(0);

    public VhcReddistribucionplantillatipo() {
    }

	
    public VhcReddistribucionplantillatipo(byte[] idreddistribucionplantillatipo, String nombre, String clave) {
        this.idreddistribucionplantillatipo = idreddistribucionplantillatipo;
        this.nombre = nombre;
        this.clave = clave;
    }
    public VhcReddistribucionplantillatipo(byte[] idreddistribucionplantillatipo, String nombre, String descripcion, String clave, Set vhcReddistribucionplantillatipobases) {
       this.idreddistribucionplantillatipo = idreddistribucionplantillatipo;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.clave = clave;
       this.vhcReddistribucionplantillatipobases = vhcReddistribucionplantillatipobases;
    }
   
     @Id 

    
    @Column(name="IDREDDISTRIBUCIONPLANTILLATIPO", unique=true, nullable=false)
    public byte[] getIdreddistribucionplantillatipo() {
        return this.idreddistribucionplantillatipo;
    }
    
    public void setIdreddistribucionplantillatipo(byte[] idreddistribucionplantillatipo) {
        this.idreddistribucionplantillatipo = idreddistribucionplantillatipo;
    }

    
    @Column(name="NOMBRE", unique=true, nullable=false, length=255)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="DESCRIPCION", length=2000)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="CLAVE", unique=true, nullable=false, length=255)
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vhcReddistribucionplantillatipo")
    public Set getVhcReddistribucionplantillatipobases() {
        return this.vhcReddistribucionplantillatipobases;
    }
    
    public void setVhcReddistribucionplantillatipobases(Set vhcReddistribucionplantillatipobases) {
        this.vhcReddistribucionplantillatipobases = vhcReddistribucionplantillatipobases;
    }




}


