package com.organizame.reportes.entity;
// Generated 6 nov 2025 15:47:18 by Hibernate Tools 6.6.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * VhcSegmentomodelo generated by hbm2java
 */
@Entity
@Table(name="vhc_segmentomodelo"
    , uniqueConstraints = @UniqueConstraint(columnNames={"IDSEGMENTO", "IDMODELO"}) 
)
public class VhcSegmentomodelo  implements java.io.Serializable {


     private byte[] idsegmentomodelo;
     private VhcSegmento vhcSegmento;
     private byte[] idmodelo;

    public VhcSegmentomodelo() {
    }

	
    public VhcSegmentomodelo(byte[] idsegmentomodelo) {
        this.idsegmentomodelo = idsegmentomodelo;
    }
    public VhcSegmentomodelo(byte[] idsegmentomodelo, VhcSegmento vhcSegmento, byte[] idmodelo) {
       this.idsegmentomodelo = idsegmentomodelo;
       this.vhcSegmento = vhcSegmento;
       this.idmodelo = idmodelo;
    }
   
     @Id 

    
    @Column(name="IDSEGMENTOMODELO", unique=true, nullable=false)
    public byte[] getIdsegmentomodelo() {
        return this.idsegmentomodelo;
    }
    
    public void setIdsegmentomodelo(byte[] idsegmentomodelo) {
        this.idsegmentomodelo = idsegmentomodelo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDSEGMENTO")
    public VhcSegmento getVhcSegmento() {
        return this.vhcSegmento;
    }
    
    public void setVhcSegmento(VhcSegmento vhcSegmento) {
        this.vhcSegmento = vhcSegmento;
    }

    
    @Column(name="IDMODELO")
    public byte[] getIdmodelo() {
        return this.idmodelo;
    }
    
    public void setIdmodelo(byte[] idmodelo) {
        this.idmodelo = idmodelo;
    }




}


