package com.organizame.reportes.entity;
// Generated 6 nov 2025 15:47:18 by Hibernate Tools 6.6.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import java.util.HashSet;
import java.util.Set;

/**
 * VhcSegmento generated by hbm2java
 */
@Entity
@Table(name="vhc_segmento"
    , uniqueConstraints = {@UniqueConstraint(columnNames="CLAVE"), @UniqueConstraint(columnNames="NOMBRE")} 
)
public class VhcSegmento  implements java.io.Serializable {


     private byte[] idsegmento;
     private String nombre;
     private String clave;
     private int orden;
     private Set vhcSegmentomodelos = new HashSet(0);

    public VhcSegmento() {
    }

	
    public VhcSegmento(byte[] idsegmento, String nombre, String clave, int orden) {
        this.idsegmento = idsegmento;
        this.nombre = nombre;
        this.clave = clave;
        this.orden = orden;
    }
    public VhcSegmento(byte[] idsegmento, String nombre, String clave, int orden, Set vhcSegmentomodelos) {
       this.idsegmento = idsegmento;
       this.nombre = nombre;
       this.clave = clave;
       this.orden = orden;
       this.vhcSegmentomodelos = vhcSegmentomodelos;
    }
   
     @Id 

    
    @Column(name="IDSEGMENTO", unique=true, nullable=false)
    public byte[] getIdsegmento() {
        return this.idsegmento;
    }
    
    public void setIdsegmento(byte[] idsegmento) {
        this.idsegmento = idsegmento;
    }

    
    @Column(name="NOMBRE", unique=true, nullable=false, length=255)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="CLAVE", unique=true, nullable=false, length=255)
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }

    
    @Column(name="ORDEN", nullable=false)
    public int getOrden() {
        return this.orden;
    }
    
    public void setOrden(int orden) {
        this.orden = orden;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vhcSegmento")
    public Set getVhcSegmentomodelos() {
        return this.vhcSegmentomodelos;
    }
    
    public void setVhcSegmentomodelos(Set vhcSegmentomodelos) {
        this.vhcSegmentomodelos = vhcSegmentomodelos;
    }




}


