package com.organizame.reportes.entity;
// Generated 6 nov 2025 15:47:18 by Hibernate Tools 6.6.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import java.util.HashSet;
import java.util.Set;

/**
 * VhcVersion generated by hbm2java
 */
@Entity
@Table(name="vhc_version"
    , uniqueConstraints = @UniqueConstraint(columnNames={"IDMODELO", "NOMBRE"}) 
)
public class VhcVersion  implements java.io.Serializable {


     private byte[] idversion;
     private VhcModelo vhcModelo;
     private String nombre;
     private Set vhcAnios = new HashSet(0);
     private Set vhcVersionaliases = new HashSet(0);

    public VhcVersion() {
    }

	
    public VhcVersion(byte[] idversion, String nombre) {
        this.idversion = idversion;
        this.nombre = nombre;
    }
    public VhcVersion(byte[] idversion, VhcModelo vhcModelo, String nombre, Set vhcAnios, Set vhcVersionaliases) {
       this.idversion = idversion;
       this.vhcModelo = vhcModelo;
       this.nombre = nombre;
       this.vhcAnios = vhcAnios;
       this.vhcVersionaliases = vhcVersionaliases;
    }
   
     @Id 

    
    @Column(name="IDVERSION", unique=true, nullable=false)
    public byte[] getIdversion() {
        return this.idversion;
    }
    
    public void setIdversion(byte[] idversion) {
        this.idversion = idversion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDMODELO")
    public VhcModelo getVhcModelo() {
        return this.vhcModelo;
    }
    
    public void setVhcModelo(VhcModelo vhcModelo) {
        this.vhcModelo = vhcModelo;
    }

    
    @Column(name="NOMBRE", nullable=false, length=255)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vhcVersion")
    public Set getVhcAnios() {
        return this.vhcAnios;
    }
    
    public void setVhcAnios(Set vhcAnios) {
        this.vhcAnios = vhcAnios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vhcVersion")
    public Set getVhcVersionaliases() {
        return this.vhcVersionaliases;
    }
    
    public void setVhcVersionaliases(Set vhcVersionaliases) {
        this.vhcVersionaliases = vhcVersionaliases;
    }




}


