package com.organizame.reportes.entity;
// Generated 6 nov 2025 15:47:18 by Hibernate Tools 6.6.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;
import java.util.Arrays;

/**
 * VhcVersionaliasViewId generated by hbm2java
 */
@Embeddable
public class VhcVersionaliasViewId  implements java.io.Serializable {


     private String alias;
     private byte[] idversion;
     private String nombre;

    public VhcVersionaliasViewId() {
    }

    public VhcVersionaliasViewId(String alias, byte[] idversion, String nombre) {
       this.alias = alias;
       this.idversion = idversion;
       this.nombre = nombre;
    }
   


    @Column(name="ALIAS", nullable=false, length=255)
    public String getAlias() {
        return this.alias;
    }
    
    public void setAlias(String alias) {
        this.alias = alias;
    }


    @Column(name="IDVERSION", nullable=false)
    public byte[] getIdversion() {
        return this.idversion;
    }
    
    public void setIdversion(byte[] idversion) {
        this.idversion = idversion;
    }


    @Column(name="NOMBRE", nullable=false, length=255)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VhcVersionaliasViewId) ) return false;
		 VhcVersionaliasViewId castOther = ( VhcVersionaliasViewId ) other; 
         
		 return ( (this.getAlias()==castOther.getAlias()) || ( this.getAlias()!=null && castOther.getAlias()!=null && this.getAlias().equals(castOther.getAlias()) ) )
 && ( (this.getIdversion()==castOther.getIdversion()) || ( this.getIdversion()!=null && castOther.getIdversion()!=null && Arrays.equals(this.getIdversion(), castOther.getIdversion()) ) )
 && ( (this.getNombre()==castOther.getNombre()) || ( this.getNombre()!=null && castOther.getNombre()!=null && this.getNombre().equals(castOther.getNombre()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + ( getAlias() == null ? 0 : this.getAlias().hashCode() );
        int idversionHashcode = 0;
         byte[] idversionProperty = this.getIdversion();
         if(idversionProperty != null) {
             idversionHashcode = 1;
             for (int i=0; i<idversionProperty.length; i++) {
                 idversionHashcode = 37 * idversionHashcode + idversionProperty[i];
             }
         }

         result = 37 * result + idversionHashcode;

        result = 37 * result + ( getNombre() == null ? 0 : this.getNombre().hashCode() );
         return result;
   }   


}


