package com.organizame.reportes.entity;
// Generated 6 nov 2025 15:47:18 by Hibernate Tools 6.6.3.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * VhcVersionalias generated by hbm2java
 */
@Entity
@Table(name="vhc_versionalias"
    , uniqueConstraints = @UniqueConstraint(columnNames={"IDVERSION", "NOMBRE"}) 
)
public class VhcVersionalias  implements java.io.Serializable {


     private byte[] idversionalias;
     private VhcVersion vhcVersion;
     private String nombre;

    public VhcVersionalias() {
    }

	
    public VhcVersionalias(byte[] idversionalias, String nombre) {
        this.idversionalias = idversionalias;
        this.nombre = nombre;
    }
    public VhcVersionalias(byte[] idversionalias, VhcVersion vhcVersion, String nombre) {
       this.idversionalias = idversionalias;
       this.vhcVersion = vhcVersion;
       this.nombre = nombre;
    }
   
     @Id 

    
    @Column(name="IDVERSIONALIAS", unique=true, nullable=false)
    public byte[] getIdversionalias() {
        return this.idversionalias;
    }
    
    public void setIdversionalias(byte[] idversionalias) {
        this.idversionalias = idversionalias;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDVERSION")
    public VhcVersion getVhcVersion() {
        return this.vhcVersion;
    }
    
    public void setVhcVersion(VhcVersion vhcVersion) {
        this.vhcVersion = vhcVersion;
    }

    
    @Column(name="NOMBRE", nullable=false, length=255)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


