package com.organizame.reportes.entity;
// Generated 6 nov 2025 15:47:18 by Hibernate Tools 6.6.3.Final


import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

/**
 * VhcVersionaliasView generated by hbm2java
 */
@Entity
@Table(name="vhc_versionalias_view"
)
public class VhcVersionaliasView  implements java.io.Serializable {


     private VhcVersionaliasViewId id;

    public VhcVersionaliasView() {
    }

    public VhcVersionaliasView(VhcVersionaliasViewId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="alias", column=@Column(name="ALIAS", nullable=false, length=255) ), 
        @AttributeOverride(name="idversion", column=@Column(name="IDVERSION", nullable=false) ), 
        @AttributeOverride(name="nombre", column=@Column(name="NOMBRE", nullable=false, length=255) ) } )
    public VhcVersionaliasViewId getId() {
        return this.id;
    }
    
    public void setId(VhcVersionaliasViewId id) {
        this.id = id;
    }




}


