/*
 * Created on 2025-12-11 ( 10:43:56 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;

/**
 * JPA entity class for "BnkBancoperiodo"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="bnk_bancoperiodo", catalog="adistemdb" )
public class BnkBancoperiodo implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Lob
    @Column(name="IDBANCOPERIODO", nullable=false)
    private byte[]     idbancoperiodo ;

    //--- ENTITY DATA FIELDS 
    @Lob
    @Column(name="IDBANCO")
    private byte[]     idbanco ;

    @Column(name="PERIODOANIO", nullable=false)
    private int        periodoanio ;

    @Column(name="PERIODOMES", nullable=false)
    private int        periodomes ;

    @Column(name="UNIDADESFINANCIADAS", nullable=false)
    private int        unidadesfinanciadas ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="IDBANCO", referencedColumnName="IDBANCO", insertable=false, updatable=false)
    private BnkBanco   bnkbanco ; 


    /**
     * Constructor
     */
    public BnkBancoperiodo() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setIdbancoperiodo( byte[] idbancoperiodo ) {
        this.idbancoperiodo = idbancoperiodo ;
    }
    public byte[] getIdbancoperiodo() {
        return this.idbancoperiodo;
    }

    public void setIdbanco( byte[] idbanco ) {
        this.idbanco = idbanco ;
    }
    public byte[] getIdbanco() {
        return this.idbanco;
    }

    public void setPeriodoanio( int periodoanio ) {
        this.periodoanio = periodoanio ;
    }
    public int getPeriodoanio() {
        return this.periodoanio;
    }

    public void setPeriodomes( int periodomes ) {
        this.periodomes = periodomes ;
    }
    public int getPeriodomes() {
        return this.periodomes;
    }

    public void setUnidadesfinanciadas( int unidadesfinanciadas ) {
        this.unidadesfinanciadas = unidadesfinanciadas ;
    }
    public int getUnidadesfinanciadas() {
        return this.unidadesfinanciadas;
    }

    //--- GETTERS FOR LINKS
    public BnkBanco getBnkbanco() {
        return this.bnkbanco;
    } 

    //--- toString specific method
	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("BnkBancoperiodo[");
		// attribute 'idbancoperiodo' (type byte[]) not usable in toString() 
		// attribute 'idbanco' (type byte[]) not usable in toString() 
		sb.append("periodoanio=").append(periodoanio);
		sb.append(separator).append("periodomes=").append(periodomes);
		sb.append(separator).append("unidadesfinanciadas=").append(unidadesfinanciadas);
		sb.append("]");
		return sb.toString();
	}
}
