/*
 * Created on 2025-12-11 ( 10:43:56 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.entities;

import com.organizame.reportes.utils.excel.dto.Celda;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.proxy.HibernateProxy;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Objects;
import java.util.List;

/**
 * JPA entity class for "BnkEstadofinanciero"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@ToString
@RequiredArgsConstructor
@Entity
@Table(name="bnk_estadofinanciero", catalog="adistemdb" )
public class BnkEstadofinanciero implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Lob
    @Column(name="IDESTADOFINANCIERO", nullable=false)
    private byte[]     idestadofinanciero ;

    //--- ENTITY DATA FIELDS 
    @Column(name="PERIODOANIO", nullable=false)
    private int        periodoanio ;

    @Column(name="PERIODOMES", nullable=false)
    private int        periodomes ;

    @Column(name="VENTAMUESTRA", nullable=false)
    private BigDecimal ventamuestra ;

    @Column(name="VENTAAUTOSNUEVOSMENUDEO", nullable=false)
    private BigDecimal ventaautosnuevosmenudeo ;

    @Column(name="VENTAAUTOSNUEVOSFLOTILLA", nullable=false)
    private BigDecimal ventaautosnuevosflotilla ;

    @Column(name="VENTAMERCANCIASVARIASOTROS", nullable=false)
    private BigDecimal ventamercanciasvariasotros ;

    @Column(name="VENTATOTALAUTOSNUEVOS", nullable=false)
    private BigDecimal ventatotalautosnuevos ;

    @Column(name="VENTAAUTOSUSADOS", nullable=false)
    private BigDecimal ventaautosusados ;

    @Column(name="VENTACONTRATOSSERVICIONUEVOSUSADOS", nullable=false)
    private BigDecimal ventacontratosservicionuevosusados ;

    @Column(name="VENTAMECANICA", nullable=false)
    private BigDecimal ventamecanica ;

    @Column(name="VENTAHOJALATERIAPINTURA", nullable=false)
    private BigDecimal ventahojalateriapintura ;

    @Column(name="VENTAREFACCIONES", nullable=false)
    private BigDecimal ventarefacciones ;

    @Column(name="VENTAVENTASTOTALES", nullable=false)
    private BigDecimal ventaventastotales ;

    @Column(name="VENTAVENTATOTALESAUTOSNUEVOSUNIDADES", nullable=false)
    private BigDecimal ventaventatotalesautosnuevosunidades ;

    @Column(name="VENTAPRECIOPROMEDIOUNIDADMEZCLA", nullable=false)
    private BigDecimal ventapreciopromediounidadmezcla ;

    @Column(name="UTILIDADBRUTAAUTOSNUEVOSMENUDEO", nullable=false)
    private BigDecimal utilidadbrutaautosnuevosmenudeo ;

    @Column(name="UTILIDADBRUTAAUTOSNUEVOSFLOTILLA", nullable=false)
    private BigDecimal utilidadbrutaautosnuevosflotilla ;

    @Column(name="UTILIDADBRUTABONOSPLANTA", nullable=false)
    private BigDecimal utilidadbrutabonosplanta ;

    @Column(name="UTILIDADBRUTATRANSFERENCIASBONOSINCENTIVOSFINANCIERAS", nullable=false)
    private BigDecimal utilidadbrutatransferenciasbonosincentivosfinancieras ;

    @Column(name="UTILIDADBRUTATOTALAUTOSNUEVOS", nullable=false)
    private BigDecimal utilidadbrutatotalautosnuevos ;

    @Column(name="UTILIDADBRUTAAUTOSUSADOS", nullable=false)
    private BigDecimal utilidadbrutaautosusados ;

    @Column(name="UTILIDADBRUTACONTRATOSSERVICIONUEVOSUSADOS", nullable=false)
    private BigDecimal utilidadbrutacontratosservicionuevosusados ;

    @Column(name="UTILIDADBRUTAMECANICA", nullable=false)
    private BigDecimal utilidadbrutamecanica ;

    @Column(name="UTILIDADBRUTAHOJALATERIAPINTURA", nullable=false)
    private BigDecimal utilidadbrutahojalateriapintura ;

    @Column(name="UTILIDADBRUTAREFACCIONES", nullable=false)
    private BigDecimal utilidadbrutarefacciones ;

    @Column(name="UTILIDADBRUTAUTILIDADBRUTATOTAL", nullable=false)
    private BigDecimal utilidadbrutautilidadbrutatotal ;

    @Column(name="GASTOVARIABLESNUEVOS", nullable=false)
    private BigDecimal gastovariablesnuevos ;

    @Column(name="GASTOVARIABLESUSADOS", nullable=false)
    private BigDecimal gastovariablesusados ;

    @Column(name="GASTOPLANPISO", nullable=false)
    private BigDecimal gastoplanpiso ;

    @Column(name="GASTOVENTAMECANICA", nullable=false)
    private BigDecimal gastoventamecanica ;

    @Column(name="GASTOVENTAHOJALATERIAPINTURA", nullable=false)
    private BigDecimal gastoventahojalateriapintura ;

    @Column(name="GASTOVENTAREFACCIONES", nullable=false)
    private BigDecimal gastoventarefacciones ;

    @Column(name="GASTOFIJOS", nullable=false)
    private BigDecimal gastofijos ;

    @Column(name="GASTOSUELDOSPROPIETARIOSFUNCIONARIOS", nullable=false)
    private BigDecimal gastosueldospropietariosfuncionarios ;

    @Column(name="GASTOGASTOSTOTALESSINRENTAEQUIVALENTES", nullable=false)
    private BigDecimal gastogastostotalessinrentaequivalentes ;

    @Column(name="UTILIDADNETAUTILIDADOPERACIONSINRENTASSINDEPRECIACION", nullable=false)
    private BigDecimal utilidadnetautilidadoperacionsinrentassindepreciacion ;

    @Column(name="UTILIDADNETABIENESINMUEBLESRENTAEQUIVALENTES", nullable=false)
    private BigDecimal utilidadnetabienesinmueblesrentaequivalentes ;

    @Column(name="UTILIDADNETAUTILIDADOPERACION", nullable=false)
    private BigDecimal utilidadnetautilidadoperacion ;

    @Column(name="UTILIDADNETAOTROSINGRESOSDEDUCCIONES", nullable=false)
    private BigDecimal utilidadnetaotrosingresosdeducciones ;

    @Column(name="UTILIDADNETAUTILIDADNETAREPORTADA", nullable=false)
    private BigDecimal utilidadnetautilidadnetareportada ;

    @Column(name="UTILIDADDEALERSREPORTARONUTILIDAD", nullable=false)
    private BigDecimal utilidaddealersreportaronutilidad ;

    @Column(name="UTILIDADPORCENTAJEDEALERSCONUTILIDAD", nullable=false)
    private BigDecimal utilidadporcentajedealersconutilidad ;

    @Column(name="UTILIDADUTILIDADNETAENTREVENTASTOTALES", nullable=false)
    private BigDecimal utilidadutilidadnetaentreventastotales ;

    @Column(name="UTILIDADEBITDAENTREVENTASTOTALES", nullable=false)
    private BigDecimal utilidadebitdaentreventastotales ;

    @Column(name="UTILIDADABSORCIONSERVICIO", nullable=false)
    private BigDecimal utilidadabsorcionservicio ;

    @Column(name="UTILIDADROIPORCENTAJE", nullable=false)
    private BigDecimal utilidadroiporcentaje ;

    @Column(name="UTILIDADROIOPERATIVOPORCENTAJE", nullable=false)
    private BigDecimal utilidadroioperativoporcentaje ;

    @Column(name="UTILIDADMARGENBRUTO", nullable=false)
    private BigDecimal utilidadmargenbruto ;

    @Column(name="UTILIDADPLANPISOUTILIDADBRUTA", nullable=false)
    private BigDecimal utilidadplanpisoutilidadbruta ;

    @Column(name="UTILIDADAUTOSNUEVOSMENUDEO", nullable=false)
    private BigDecimal utilidadautosnuevosmenudeo ;

    @Column(name="UTILIDADAUTOSNUEVOSFLOTILLAS", nullable=false)
    private BigDecimal utilidadautosnuevosflotillas ;

    @Column(name="UTILIDADAUTOSNUEVOSBONOSPLANTA", nullable=false)
    private BigDecimal utilidadautosnuevosbonosplanta ;

    @Column(name="UTILIDADAUTOSNUEVOSTOTALSINFLOTILLAS", nullable=false)
    private BigDecimal utilidadautosnuevostotalsinflotillas ;

    @Column(name="UTILIDADAUTOSUSADOS", nullable=false)
    private BigDecimal utilidadautosusados ;

    @Column(name="UTILIDADCONTRATOSSERVICIO", nullable=false)
    private BigDecimal utilidadcontratosservicio ;

    @Column(name="UTILIDADMECANICA", nullable=false)
    private BigDecimal utilidadmecanica ;

    @Column(name="UTILIDADHOJALATERIAPINTURA", nullable=false)
    private BigDecimal utilidadhojalateriapintura ;

    @Column(name="UTILIDADREFACCIONES", nullable=false)
    private BigDecimal utilidadrefacciones ;

    @Column(name="UTILIDADTOTAL", nullable=false)
    private BigDecimal utilidadtotal ;



    @Override
    public final boolean equals(Object o) {
        if (this == o) return true;
        if (o == null) return false;
        Class<?> oEffectiveClass = o instanceof HibernateProxy ? ((HibernateProxy) o).getHibernateLazyInitializer().getPersistentClass() : o.getClass();
        Class<?> thisEffectiveClass = this instanceof HibernateProxy ? ((HibernateProxy) this).getHibernateLazyInitializer().getPersistentClass() : this.getClass();
        if (thisEffectiveClass != oEffectiveClass) return false;
        BnkEstadofinanciero that = (BnkEstadofinanciero) o;
        return getIdestadofinanciero() != null && Objects.equals(getIdestadofinanciero(), that.getIdestadofinanciero());
    }

    @Override
    public final int hashCode() {
        return this instanceof HibernateProxy ? ((HibernateProxy) this).getHibernateLazyInitializer().getPersistentClass().hashCode() : getClass().hashCode();
    }

    public List<Celda> toCeldas(String anio, String mes) {
        List<Celda> resultado = new ArrayList<>();

        resultado.add(new Celda(anio, "grisEncabezado", 1));
        resultado.add(new Celda(mes, "grisEncabezado", 1));

        resultado.add(new Celda(this.ventamuestra.intValue(), "Encabezado", 1));
        resultado.add(new Celda(this.ventaautosnuevosmenudeo.intValue(), "normal", 1));
        resultado.add(new Celda(this.ventaautosnuevosflotilla.intValue(), "normal", 1));
        resultado.add(new Celda(this.ventamercanciasvariasotros.intValue(), "normal", 1));

        //Ventas
        resultado.add(new Celda(this.ventatotalautosnuevos.intValue(), "normal", 1));
        resultado.add(new Celda(this.ventaautosusados.intValue(), "normal", 1));
        resultado.add(new Celda(this.ventacontratosservicionuevosusados.intValue(), "normal", 1));
        resultado.add(new Celda(this.ventamecanica.intValue(), "normal", 1));
        resultado.add(new Celda(this.ventahojalateriapintura.intValue(), "normal", 1));
        resultado.add(new Celda(this.ventarefacciones.intValue(), "normal", 1));
        resultado.add(new Celda(this.ventaventastotales.intValue(), "normal", 1));
        resultado.add(new Celda(this.ventaventatotalesautosnuevosunidades.intValue(), "normal", 1));
        resultado.add(new Celda(this.ventapreciopromediounidadmezcla.intValue(), "normal", 1));

        resultado.add(new Celda(this.utilidadbrutaautosnuevosmenudeo.intValue(), "normal", 1));
        resultado.add(new Celda(this.utilidadbrutaautosnuevosflotilla.intValue(), "normal", 1));
        resultado.add(new Celda(this.utilidadbrutabonosplanta.intValue(), "normal", 1));
        resultado.add(new Celda(this.utilidadbrutatransferenciasbonosincentivosfinancieras.intValue(), "normal", 1));
        resultado.add(new Celda(this.utilidadbrutatotalautosnuevos.intValue(), "normal", 1));
        resultado.add(new Celda(this.utilidadbrutaautosusados.intValue(), "normal", 1));
        resultado.add(new Celda(this.utilidadbrutacontratosservicionuevosusados.intValue(), "normal", 1));
        resultado.add(new Celda(this.utilidadbrutamecanica.intValue(), "normal", 1));
        resultado.add(new Celda(this.utilidadbrutahojalateriapintura.intValue(), "normal", 1));
        resultado.add(new Celda(this.utilidadbrutarefacciones.intValue(), "normal", 1));
        resultado.add(new Celda(this.utilidadbrutautilidadbrutatotal.intValue(), "normal", 1));


        //Gastos
        resultado.add(new Celda(this.gastovariablesnuevos.intValue(), "normal", 1));
        resultado.add(new Celda(this.gastovariablesusados.intValue(), "normal", 1));
        resultado.add(new Celda(this.gastoplanpiso.intValue(), "normal", 1));
        resultado.add(new Celda(this.gastoventamecanica.intValue(), "normal", 1));
        resultado.add(new Celda(this.gastoventahojalateriapintura.intValue(), "normal", 1));
        resultado.add(new Celda(this.gastoventarefacciones.intValue(), "normal", 1));
        resultado.add(new Celda(this.gastofijos.intValue(), "normal", 1));
        resultado.add(new Celda(this.gastosueldospropietariosfuncionarios.intValue(), "normal", 1));
        resultado.add(new Celda(this.gastogastostotalessinrentaequivalentes.intValue(), "normal", 1));


        resultado.add(new Celda(this.utilidadnetautilidadoperacionsinrentassindepreciacion.intValue(), "normal", 1));
        resultado.add(new Celda(this.utilidadnetabienesinmueblesrentaequivalentes.intValue(), "normal", 1));
        resultado.add(new Celda(this.utilidadnetautilidadoperacion.intValue(), "normal", 1));
        resultado.add(new Celda(this.utilidadnetaotrosingresosdeducciones.intValue(), "normal", 1));
        resultado.add(new Celda(this.utilidadnetautilidadnetareportada.intValue(), "normal", 1));

        resultado.add(new Celda("", "normal", 1));

        resultado.add(new Celda(this.utilidaddealersreportaronutilidad.intValue(), "encabezado", 1));
        resultado.add(new Celda(this.utilidadporcentajedealersconutilidad, "normal", 1));
        resultado.add(new Celda(this.utilidadutilidadnetaentreventastotales, "normal", 1));

        resultado.add(new Celda("", "normal", 1));
        resultado.add(new Celda("", "normal", 1));
        resultado.add(new Celda("", "normal", 1));

        resultado.add(new Celda(this.utilidadebitdaentreventastotales, "gris", 1));
        resultado.add(new Celda(this.utilidadabsorcionservicio, "normal", 1));
        resultado.add(new Celda(this.utilidadroiporcentaje, "normal", 1));
        resultado.add(new Celda(this.utilidadroioperativoporcentaje, "normal", 1));

        resultado.add(new Celda("", "normal", 1));

        resultado.add(new Celda(this.utilidadmargenbruto, "azul", 1));
        resultado.add(new Celda(this.utilidadplanpisoutilidadbruta, "azul", 1));
        resultado.add(new Celda(this.utilidadautosnuevosmenudeo, "normal", 1));
        resultado.add(new Celda(this.utilidadautosnuevosflotillas, "normal", 1));
        resultado.add(new Celda(this.utilidadautosnuevosbonosplanta, "normal", 1));
        resultado.add(new Celda(this.utilidadautosnuevostotalsinflotillas, "normal", 1));
        resultado.add(new Celda(this.utilidadautosusados, "normal", 1));
        resultado.add(new Celda(this.utilidadcontratosservicio, "normal", 1));
        resultado.add(new Celda(this.utilidadmecanica, "normal", 1));
        resultado.add(new Celda(this.utilidadhojalateriapintura, "normal", 1));
        resultado.add(new Celda(this.utilidadrefacciones, "normal", 1));
        resultado.add(new Celda(this.utilidadtotal, "encabezado", 1));


        resultado.add(new Celda("", "normal", 1));
        resultado.add(new Celda("", "normal", 1));

        resultado.add(new Celda(this.periodomes, "normal", 1));
        return resultado;
    }


    private static BigDecimal nvl(BigDecimal v) {
        return v != null ? v : BigDecimal.ZERO;
    }

    public BnkEstadofinanciero sumarCon(BnkEstadofinanciero otro) {
        BnkEstadofinanciero r = new BnkEstadofinanciero();

        // Ventas
        r.setVentamuestra(nvl(this.ventamuestra).add(nvl(otro.ventamuestra)));
        r.setVentaautosnuevosmenudeo(nvl(this.ventaautosnuevosmenudeo).add(nvl(otro.ventaautosnuevosmenudeo)));
        r.setVentaautosnuevosflotilla(nvl(this.ventaautosnuevosflotilla).add(nvl(otro.ventaautosnuevosflotilla)));
        r.setVentamercanciasvariasotros(nvl(this.ventamercanciasvariasotros).add(nvl(otro.ventamercanciasvariasotros)));
        r.setVentatotalautosnuevos(nvl(this.ventatotalautosnuevos).add(nvl(otro.ventatotalautosnuevos)));
        r.setVentaautosusados(nvl(this.ventaautosusados).add(nvl(otro.ventaautosusados)));
        r.setVentacontratosservicionuevosusados(nvl(this.ventacontratosservicionuevosusados).add(nvl(otro.ventacontratosservicionuevosusados)));
        r.setVentamecanica(nvl(this.ventamecanica).add(nvl(otro.ventamecanica)));
        r.setVentahojalateriapintura(nvl(this.ventahojalateriapintura).add(nvl(otro.ventahojalateriapintura)));
        r.setVentarefacciones(nvl(this.ventarefacciones).add(nvl(otro.ventarefacciones)));
        r.setVentaventastotales(nvl(this.ventaventastotales).add(nvl(otro.ventaventastotales)));
        r.setVentaventatotalesautosnuevosunidades(nvl(this.ventaventatotalesautosnuevosunidades).add(nvl(otro.ventaventatotalesautosnuevosunidades)));
        r.setVentapreciopromediounidadmezcla(nvl(this.ventapreciopromediounidadmezcla).add(nvl(otro.ventapreciopromediounidadmezcla)));

        // Utilidad bruta
        r.setUtilidadbrutaautosnuevosmenudeo(nvl(this.utilidadbrutaautosnuevosmenudeo).add(nvl(otro.utilidadbrutaautosnuevosmenudeo)));
        r.setUtilidadbrutaautosnuevosflotilla(nvl(this.utilidadbrutaautosnuevosflotilla).add(nvl(otro.utilidadbrutaautosnuevosflotilla)));
        r.setUtilidadbrutabonosplanta(nvl(this.utilidadbrutabonosplanta).add(nvl(otro.utilidadbrutabonosplanta)));
        r.setUtilidadbrutatransferenciasbonosincentivosfinancieras(
                nvl(this.utilidadbrutatransferenciasbonosincentivosfinancieras)
                        .add(nvl(otro.utilidadbrutatransferenciasbonosincentivosfinancieras)));
        r.setUtilidadbrutatotalautosnuevos(nvl(this.utilidadbrutatotalautosnuevos).add(nvl(otro.utilidadbrutatotalautosnuevos)));
        r.setUtilidadbrutaautosusados(nvl(this.utilidadbrutaautosusados).add(nvl(otro.utilidadbrutaautosusados)));
        r.setUtilidadbrutacontratosservicionuevosusados(
                nvl(this.utilidadbrutacontratosservicionuevosusados)
                        .add(nvl(otro.utilidadbrutacontratosservicionuevosusados)));
        r.setUtilidadbrutamecanica(nvl(this.utilidadbrutamecanica).add(nvl(otro.utilidadbrutamecanica)));
        r.setUtilidadbrutahojalateriapintura(nvl(this.utilidadbrutahojalateriapintura).add(nvl(otro.utilidadbrutahojalateriapintura)));
        r.setUtilidadbrutarefacciones(nvl(this.utilidadbrutarefacciones).add(nvl(otro.utilidadbrutarefacciones)));
        r.setUtilidadbrutautilidadbrutatotal(
                nvl(this.utilidadbrutautilidadbrutatotal).add(nvl(otro.utilidadbrutautilidadbrutatotal)));

        // Gastos
        r.setGastovariablesnuevos(nvl(this.gastovariablesnuevos).add(nvl(otro.gastovariablesnuevos)));
        r.setGastovariablesusados(nvl(this.gastovariablesusados).add(nvl(otro.gastovariablesusados)));
        r.setGastoplanpiso(nvl(this.gastoplanpiso).add(nvl(otro.gastoplanpiso)));
        r.setGastoventamecanica(nvl(this.gastoventamecanica).add(nvl(otro.gastoventamecanica)));
        r.setGastoventahojalateriapintura(nvl(this.gastoventahojalateriapintura).add(nvl(otro.gastoventahojalateriapintura)));
        r.setGastoventarefacciones(nvl(this.gastoventarefacciones).add(nvl(otro.gastoventarefacciones)));
        r.setGastofijos(nvl(this.gastofijos).add(nvl(otro.gastofijos)));
        r.setGastosueldospropietariosfuncionarios(
                nvl(this.gastosueldospropietariosfuncionarios)
                        .add(nvl(otro.gastosueldospropietariosfuncionarios)));
        r.setGastogastostotalessinrentaequivalentes(
                nvl(this.gastogastostotalessinrentaequivalentes)
                        .add(nvl(otro.gastogastostotalessinrentaequivalentes)));

        // Utilidad neta
        r.setUtilidadnetautilidadoperacionsinrentassindepreciacion(
                nvl(this.utilidadnetautilidadoperacionsinrentassindepreciacion)
                        .add(nvl(otro.utilidadnetautilidadoperacionsinrentassindepreciacion)));
        r.setUtilidadnetabienesinmueblesrentaequivalentes(
                nvl(this.utilidadnetabienesinmueblesrentaequivalentes)
                        .add(nvl(otro.utilidadnetabienesinmueblesrentaequivalentes)));
        r.setUtilidadnetautilidadoperacion(
                nvl(this.utilidadnetautilidadoperacion)
                        .add(nvl(otro.utilidadnetautilidadoperacion)));
        r.setUtilidadnetaotrosingresosdeducciones(
                nvl(this.utilidadnetaotrosingresosdeducciones)
                        .add(nvl(otro.utilidadnetaotrosingresosdeducciones)));
        r.setUtilidadnetautilidadnetareportada(
                nvl(this.utilidadnetautilidadnetareportada)
                        .add(nvl(otro.utilidadnetautilidadnetareportada)));

        // Indicadores finales
        r.setUtilidaddealersreportaronutilidad(
                nvl(this.utilidaddealersreportaronutilidad)
                        .add(nvl(otro.utilidaddealersreportaronutilidad)));
        r.setUtilidadporcentajedealersconutilidad(
                nvl(this.utilidadporcentajedealersconutilidad)
                        .add(nvl(otro.utilidadporcentajedealersconutilidad)));
        r.setUtilidadutilidadnetaentreventastotales(
                nvl(this.utilidadutilidadnetaentreventastotales)
                        .add(nvl(otro.utilidadutilidadnetaentreventastotales)));
        r.setUtilidadebitdaentreventastotales(
                nvl(this.utilidadebitdaentreventastotales)
                        .add(nvl(otro.utilidadebitdaentreventastotales)));
        r.setUtilidadabsorcionservicio(
                nvl(this.utilidadabsorcionservicio)
                        .add(nvl(otro.utilidadabsorcionservicio)));
        r.setUtilidadroiporcentaje(
                nvl(this.utilidadroiporcentaje)
                        .add(nvl(otro.utilidadroiporcentaje)));
        r.setUtilidadroioperativoporcentaje(
                nvl(this.utilidadroioperativoporcentaje)
                        .add(nvl(otro.utilidadroioperativoporcentaje)));
        r.setUtilidadmargenbruto(
                nvl(this.utilidadmargenbruto)
                        .add(nvl(otro.utilidadmargenbruto)));
        r.setUtilidadplanpisoutilidadbruta(
                nvl(this.utilidadplanpisoutilidadbruta)
                        .add(nvl(otro.utilidadplanpisoutilidadbruta)));

        // Utilidades por área
        r.setUtilidadautosnuevosmenudeo(
                nvl(this.utilidadautosnuevosmenudeo)
                        .add(nvl(otro.utilidadautosnuevosmenudeo)));
        r.setUtilidadautosnuevosflotillas(
                nvl(this.utilidadautosnuevosflotillas)
                        .add(nvl(otro.utilidadautosnuevosflotillas)));
        r.setUtilidadautosnuevosbonosplanta(
                nvl(this.utilidadautosnuevosbonosplanta)
                        .add(nvl(otro.utilidadautosnuevosbonosplanta)));
        r.setUtilidadautosnuevostotalsinflotillas(
                nvl(this.utilidadautosnuevostotalsinflotillas)
                        .add(nvl(otro.utilidadautosnuevostotalsinflotillas)));
        r.setUtilidadautosusados(
                nvl(this.utilidadautosusados)
                        .add(nvl(otro.utilidadautosusados)));
        r.setUtilidadcontratosservicio(
                nvl(this.utilidadcontratosservicio)
                        .add(nvl(otro.utilidadcontratosservicio)));
        r.setUtilidadmecanica(
                nvl(this.utilidadmecanica)
                        .add(nvl(otro.utilidadmecanica)));
        r.setUtilidadhojalateriapintura(
                nvl(this.utilidadhojalateriapintura)
                        .add(nvl(otro.utilidadhojalateriapintura)));
        r.setUtilidadrefacciones(
                nvl(this.utilidadrefacciones)
                        .add(nvl(otro.utilidadrefacciones)));
        r.setUtilidadtotal(
                nvl(this.utilidadtotal)
                        .add(nvl(otro.utilidadtotal)));

        return r;
    }


}
