/*
 * Created on 2025-12-11 ( 10:43:56 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.entities;

import java.io.Serializable;
import java.math.BigDecimal;
import jakarta.persistence.*;
import lombok.Data;

/**
 * JPA entity class for "BnkEstadofinanciero"
 *
 * @author Telosys
 *
 */
@Data
@Entity
@Table(name="bnk_estadofinanciero", catalog="adistemdb" )
public class BnkEstadofinanciero implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Lob
    @Column(name="IDESTADOFINANCIERO", nullable=false)
    private byte[]     idestadofinanciero ;

    //--- ENTITY DATA FIELDS 
    @Column(name="PERIODOANIO", nullable=false)
    private int        periodoanio ;

    @Column(name="PERIODOMES", nullable=false)
    private int        periodomes ;

    @Column(name="VENTAMUESTRA", nullable=false)
    private BigDecimal ventamuestra ;

    @Column(name="VENTAAUTOSNUEVOSMENUDEO", nullable=false)
    private BigDecimal ventaautosnuevosmenudeo ;

    @Column(name="VENTAAUTOSNUEVOSFLOTILLA", nullable=false)
    private BigDecimal ventaautosnuevosflotilla ;

    @Column(name="VENTAMERCANCIASVARIASOTROS", nullable=false)
    private BigDecimal ventamercanciasvariasotros ;

    @Column(name="VENTATOTALAUTOSNUEVOS", nullable=false)
    private BigDecimal ventatotalautosnuevos ;

    @Column(name="VENTAAUTOSUSADOS", nullable=false)
    private BigDecimal ventaautosusados ;

    @Column(name="VENTACONTRATOSSERVICIONUEVOSUSADOS", nullable=false)
    private BigDecimal ventacontratosservicionuevosusados ;

    @Column(name="VENTAMECANICA", nullable=false)
    private BigDecimal ventamecanica ;

    @Column(name="VENTAHOJALATERIAPINTURA", nullable=false)
    private BigDecimal ventahojalateriapintura ;

    @Column(name="VENTAREFACCIONES", nullable=false)
    private BigDecimal ventarefacciones ;

    @Column(name="VENTAVENTASTOTALES", nullable=false)
    private BigDecimal ventaventastotales ;

    @Column(name="VENTAVENTATOTALESAUTOSNUEVOSUNIDADES", nullable=false)
    private BigDecimal ventaventatotalesautosnuevosunidades ;

    @Column(name="VENTAPRECIOPROMEDIOUNIDADMEZCLA", nullable=false)
    private BigDecimal ventapreciopromediounidadmezcla ;

    @Column(name="UTILIDADBRUTAAUTOSNUEVOSMENUDEO", nullable=false)
    private BigDecimal utilidadbrutaautosnuevosmenudeo ;

    @Column(name="UTILIDADBRUTAAUTOSNUEVOSFLOTILLA", nullable=false)
    private BigDecimal utilidadbrutaautosnuevosflotilla ;

    @Column(name="UTILIDADBRUTABONOSPLANTA", nullable=false)
    private BigDecimal utilidadbrutabonosplanta ;

    @Column(name="UTILIDADBRUTATRANSFERENCIASBONOSINCENTIVOSFINANCIERAS", nullable=false)
    private BigDecimal utilidadbrutatransferenciasbonosincentivosfinancieras ;

    @Column(name="UTILIDADBRUTATOTALAUTOSNUEVOS", nullable=false)
    private BigDecimal utilidadbrutatotalautosnuevos ;

    @Column(name="UTILIDADBRUTAAUTOSUSADOS", nullable=false)
    private BigDecimal utilidadbrutaautosusados ;

    @Column(name="UTILIDADBRUTACONTRATOSSERVICIONUEVOSUSADOS", nullable=false)
    private BigDecimal utilidadbrutacontratosservicionuevosusados ;

    @Column(name="UTILIDADBRUTAMECANICA", nullable=false)
    private BigDecimal utilidadbrutamecanica ;

    @Column(name="UTILIDADBRUTAHOJALATERIAPINTURA", nullable=false)
    private BigDecimal utilidadbrutahojalateriapintura ;

    @Column(name="UTILIDADBRUTAREFACCIONES", nullable=false)
    private BigDecimal utilidadbrutarefacciones ;

    @Column(name="UTILIDADBRUTAUTILIDADBRUTATOTAL", nullable=false)
    private BigDecimal utilidadbrutautilidadbrutatotal ;

    @Column(name="GASTOVARIABLESNUEVOS", nullable=false)
    private BigDecimal gastovariablesnuevos ;

    @Column(name="GASTOVARIABLESUSADOS", nullable=false)
    private BigDecimal gastovariablesusados ;

    @Column(name="GASTOPLANPISO", nullable=false)
    private BigDecimal gastoplanpiso ;

    @Column(name="GASTOVENTAMECANICA", nullable=false)
    private BigDecimal gastoventamecanica ;

    @Column(name="GASTOVENTAHOJALATERIAPINTURA", nullable=false)
    private BigDecimal gastoventahojalateriapintura ;

    @Column(name="GASTOVENTAREFACCIONES", nullable=false)
    private BigDecimal gastoventarefacciones ;

    @Column(name="GASTOFIJOS", nullable=false)
    private BigDecimal gastofijos ;

    @Column(name="GASTOSUELDOSPROPIETARIOSFUNCIONARIOS", nullable=false)
    private BigDecimal gastosueldospropietariosfuncionarios ;

    @Column(name="GASTOGASTOSTOTALESSINRENTAEQUIVALENTES", nullable=false)
    private BigDecimal gastogastostotalessinrentaequivalentes ;

    @Column(name="UTILIDADNETAUTILIDADOPERACIONSINRENTASSINDEPRECIACION", nullable=false)
    private BigDecimal utilidadnetautilidadoperacionsinrentassindepreciacion ;

    @Column(name="UTILIDADNETABIENESINMUEBLESRENTAEQUIVALENTES", nullable=false)
    private BigDecimal utilidadnetabienesinmueblesrentaequivalentes ;

    @Column(name="UTILIDADNETAUTILIDADOPERACION", nullable=false)
    private BigDecimal utilidadnetautilidadoperacion ;

    @Column(name="UTILIDADNETAOTROSINGRESOSDEDUCCIONES", nullable=false)
    private BigDecimal utilidadnetaotrosingresosdeducciones ;

    @Column(name="UTILIDADNETAUTILIDADNETAREPORTADA", nullable=false)
    private BigDecimal utilidadnetautilidadnetareportada ;

    @Column(name="UTILIDADDEALERSREPORTARONUTILIDAD", nullable=false)
    private BigDecimal utilidaddealersreportaronutilidad ;

    @Column(name="UTILIDADPORCENTAJEDEALERSCONUTILIDAD", nullable=false)
    private BigDecimal utilidadporcentajedealersconutilidad ;

    @Column(name="UTILIDADUTILIDADNETAENTREVENTASTOTALES", nullable=false)
    private BigDecimal utilidadutilidadnetaentreventastotales ;

    @Column(name="UTILIDADEBITDAENTREVENTASTOTALES", nullable=false)
    private BigDecimal utilidadebitdaentreventastotales ;

    @Column(name="UTILIDADABSORCIONSERVICIO", nullable=false)
    private BigDecimal utilidadabsorcionservicio ;

    @Column(name="UTILIDADROIPORCENTAJE", nullable=false)
    private BigDecimal utilidadroiporcentaje ;

    @Column(name="UTILIDADROIOPERATIVOPORCENTAJE", nullable=false)
    private BigDecimal utilidadroioperativoporcentaje ;

    @Column(name="UTILIDADMARGENBRUTO", nullable=false)
    private BigDecimal utilidadmargenbruto ;

    @Column(name="UTILIDADPLANPISOUTILIDADBRUTA", nullable=false)
    private BigDecimal utilidadplanpisoutilidadbruta ;

    @Column(name="UTILIDADAUTOSNUEVOSMENUDEO", nullable=false)
    private BigDecimal utilidadautosnuevosmenudeo ;

    @Column(name="UTILIDADAUTOSNUEVOSFLOTILLAS", nullable=false)
    private BigDecimal utilidadautosnuevosflotillas ;

    @Column(name="UTILIDADAUTOSNUEVOSBONOSPLANTA", nullable=false)
    private BigDecimal utilidadautosnuevosbonosplanta ;

    @Column(name="UTILIDADAUTOSNUEVOSTOTALSINFLOTILLAS", nullable=false)
    private BigDecimal utilidadautosnuevostotalsinflotillas ;

    @Column(name="UTILIDADAUTOSUSADOS", nullable=false)
    private BigDecimal utilidadautosusados ;

    @Column(name="UTILIDADCONTRATOSSERVICIO", nullable=false)
    private BigDecimal utilidadcontratosservicio ;

    @Column(name="UTILIDADMECANICA", nullable=false)
    private BigDecimal utilidadmecanica ;

    @Column(name="UTILIDADHOJALATERIAPINTURA", nullable=false)
    private BigDecimal utilidadhojalateriapintura ;

    @Column(name="UTILIDADREFACCIONES", nullable=false)
    private BigDecimal utilidadrefacciones ;

    @Column(name="UTILIDADTOTAL", nullable=false)
    private BigDecimal utilidadtotal ;

    
      //--- toString specific method
	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("BnkEstadofinanciero[");
		// attribute 'idestadofinanciero' (type byte[]) not usable in toString() 
		sb.append("periodoanio=").append(periodoanio);
		sb.append(separator).append("periodomes=").append(periodomes);
		sb.append(separator).append("ventamuestra=").append(ventamuestra);
		sb.append(separator).append("ventaautosnuevosmenudeo=").append(ventaautosnuevosmenudeo);
		sb.append(separator).append("ventaautosnuevosflotilla=").append(ventaautosnuevosflotilla);
		sb.append(separator).append("ventamercanciasvariasotros=").append(ventamercanciasvariasotros);
		sb.append(separator).append("ventatotalautosnuevos=").append(ventatotalautosnuevos);
		sb.append(separator).append("ventaautosusados=").append(ventaautosusados);
		sb.append(separator).append("ventacontratosservicionuevosusados=").append(ventacontratosservicionuevosusados);
		sb.append(separator).append("ventamecanica=").append(ventamecanica);
		sb.append(separator).append("ventahojalateriapintura=").append(ventahojalateriapintura);
		sb.append(separator).append("ventarefacciones=").append(ventarefacciones);
		sb.append(separator).append("ventaventastotales=").append(ventaventastotales);
		sb.append(separator).append("ventaventatotalesautosnuevosunidades=").append(ventaventatotalesautosnuevosunidades);
		sb.append(separator).append("ventapreciopromediounidadmezcla=").append(ventapreciopromediounidadmezcla);
		sb.append(separator).append("utilidadbrutaautosnuevosmenudeo=").append(utilidadbrutaautosnuevosmenudeo);
		sb.append(separator).append("utilidadbrutaautosnuevosflotilla=").append(utilidadbrutaautosnuevosflotilla);
		sb.append(separator).append("utilidadbrutabonosplanta=").append(utilidadbrutabonosplanta);
		sb.append(separator).append("utilidadbrutatransferenciasbonosincentivosfinancieras=").append(utilidadbrutatransferenciasbonosincentivosfinancieras);
		sb.append(separator).append("utilidadbrutatotalautosnuevos=").append(utilidadbrutatotalautosnuevos);
		sb.append(separator).append("utilidadbrutaautosusados=").append(utilidadbrutaautosusados);
		sb.append(separator).append("utilidadbrutacontratosservicionuevosusados=").append(utilidadbrutacontratosservicionuevosusados);
		sb.append(separator).append("utilidadbrutamecanica=").append(utilidadbrutamecanica);
		sb.append(separator).append("utilidadbrutahojalateriapintura=").append(utilidadbrutahojalateriapintura);
		sb.append(separator).append("utilidadbrutarefacciones=").append(utilidadbrutarefacciones);
		sb.append(separator).append("utilidadbrutautilidadbrutatotal=").append(utilidadbrutautilidadbrutatotal);
		sb.append(separator).append("gastovariablesnuevos=").append(gastovariablesnuevos);
		sb.append(separator).append("gastovariablesusados=").append(gastovariablesusados);
		sb.append(separator).append("gastoplanpiso=").append(gastoplanpiso);
		sb.append(separator).append("gastoventamecanica=").append(gastoventamecanica);
		sb.append(separator).append("gastoventahojalateriapintura=").append(gastoventahojalateriapintura);
		sb.append(separator).append("gastoventarefacciones=").append(gastoventarefacciones);
		sb.append(separator).append("gastofijos=").append(gastofijos);
		sb.append(separator).append("gastosueldospropietariosfuncionarios=").append(gastosueldospropietariosfuncionarios);
		sb.append(separator).append("gastogastostotalessinrentaequivalentes=").append(gastogastostotalessinrentaequivalentes);
		sb.append(separator).append("utilidadnetautilidadoperacionsinrentassindepreciacion=").append(utilidadnetautilidadoperacionsinrentassindepreciacion);
		sb.append(separator).append("utilidadnetabienesinmueblesrentaequivalentes=").append(utilidadnetabienesinmueblesrentaequivalentes);
		sb.append(separator).append("utilidadnetautilidadoperacion=").append(utilidadnetautilidadoperacion);
		sb.append(separator).append("utilidadnetaotrosingresosdeducciones=").append(utilidadnetaotrosingresosdeducciones);
		sb.append(separator).append("utilidadnetautilidadnetareportada=").append(utilidadnetautilidadnetareportada);
		sb.append(separator).append("utilidaddealersreportaronutilidad=").append(utilidaddealersreportaronutilidad);
		sb.append(separator).append("utilidadporcentajedealersconutilidad=").append(utilidadporcentajedealersconutilidad);
		sb.append(separator).append("utilidadutilidadnetaentreventastotales=").append(utilidadutilidadnetaentreventastotales);
		sb.append(separator).append("utilidadebitdaentreventastotales=").append(utilidadebitdaentreventastotales);
		sb.append(separator).append("utilidadabsorcionservicio=").append(utilidadabsorcionservicio);
		sb.append(separator).append("utilidadroiporcentaje=").append(utilidadroiporcentaje);
		sb.append(separator).append("utilidadroioperativoporcentaje=").append(utilidadroioperativoporcentaje);
		sb.append(separator).append("utilidadmargenbruto=").append(utilidadmargenbruto);
		sb.append(separator).append("utilidadplanpisoutilidadbruta=").append(utilidadplanpisoutilidadbruta);
		sb.append(separator).append("utilidadautosnuevosmenudeo=").append(utilidadautosnuevosmenudeo);
		sb.append(separator).append("utilidadautosnuevosflotillas=").append(utilidadautosnuevosflotillas);
		sb.append(separator).append("utilidadautosnuevosbonosplanta=").append(utilidadautosnuevosbonosplanta);
		sb.append(separator).append("utilidadautosnuevostotalsinflotillas=").append(utilidadautosnuevostotalsinflotillas);
		sb.append(separator).append("utilidadautosusados=").append(utilidadautosusados);
		sb.append(separator).append("utilidadcontratosservicio=").append(utilidadcontratosservicio);
		sb.append(separator).append("utilidadmecanica=").append(utilidadmecanica);
		sb.append(separator).append("utilidadhojalateriapintura=").append(utilidadhojalateriapintura);
		sb.append(separator).append("utilidadrefacciones=").append(utilidadrefacciones);
		sb.append(separator).append("utilidadtotal=").append(utilidadtotal);
		sb.append("]");
		return sb.toString();
	}
}
