/*
 * Created on 2025-12-11 ( 10:43:56 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;

/**
 * JPA entity class for "BnkInstitucionfinancieraperiodo"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="bnk_institucionfinancieraperiodo", catalog="adistemdb" )
public class BnkInstitucionfinancieraperiodo implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Lob
    @Column(name="IDINSTITUCIONFINANCIERAPERIODO", nullable=false)
    private byte[]     idinstitucionfinancieraperiodo ;

    //--- ENTITY DATA FIELDS 
    @Lob
    @Column(name="IDINSTITUCIONFINANCIERA")
    private byte[]     idinstitucionfinanciera ;

    @Column(name="PERIODOANIO", nullable=false)
    private int        periodoanio ;

    @Column(name="PERIODOMES", nullable=false)
    private int        periodomes ;

    @Column(name="UNIDADESFINANCIADAS", nullable=false)
    private int        unidadesfinanciadas ;

    @Column(name="VENTAS", nullable=false)
    private int        ventas ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="IDINSTITUCIONFINANCIERA", referencedColumnName="IDINSTITUCIONFINANCIERA", insertable=false, updatable=false)
    private BnkInstitucionfinanciera bnkinstitucionfinanciera ; 


    /**
     * Constructor
     */
    public BnkInstitucionfinancieraperiodo() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setIdinstitucionfinancieraperiodo( byte[] idinstitucionfinancieraperiodo ) {
        this.idinstitucionfinancieraperiodo = idinstitucionfinancieraperiodo ;
    }
    public byte[] getIdinstitucionfinancieraperiodo() {
        return this.idinstitucionfinancieraperiodo;
    }

    public void setIdinstitucionfinanciera( byte[] idinstitucionfinanciera ) {
        this.idinstitucionfinanciera = idinstitucionfinanciera ;
    }
    public byte[] getIdinstitucionfinanciera() {
        return this.idinstitucionfinanciera;
    }

    public void setPeriodoanio( int periodoanio ) {
        this.periodoanio = periodoanio ;
    }
    public int getPeriodoanio() {
        return this.periodoanio;
    }

    public void setPeriodomes( int periodomes ) {
        this.periodomes = periodomes ;
    }
    public int getPeriodomes() {
        return this.periodomes;
    }

    public void setUnidadesfinanciadas( int unidadesfinanciadas ) {
        this.unidadesfinanciadas = unidadesfinanciadas ;
    }
    public int getUnidadesfinanciadas() {
        return this.unidadesfinanciadas;
    }

    public void setVentas( int ventas ) {
        this.ventas = ventas ;
    }
    public int getVentas() {
        return this.ventas;
    }

    //--- GETTERS FOR LINKS
    public BnkInstitucionfinanciera getBnkinstitucionfinanciera() {
        return this.bnkinstitucionfinanciera;
    } 

    //--- toString specific method
	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("BnkInstitucionfinancieraperiodo[");
		// attribute 'idinstitucionfinancieraperiodo' (type byte[]) not usable in toString() 
		// attribute 'idinstitucionfinanciera' (type byte[]) not usable in toString() 
		sb.append("periodoanio=").append(periodoanio);
		sb.append(separator).append("periodomes=").append(periodomes);
		sb.append(separator).append("unidadesfinanciadas=").append(unidadesfinanciadas);
		sb.append(separator).append("ventas=").append(ventas);
		sb.append("]");
		return sb.toString();
	}
}
