/*
 * Created on 2025-12-11 ( 10:43:56 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.entities;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.proxy.HibernateProxy;

import java.io.Serial;
import java.io.Serializable;
import java.util.Arrays;

/**
 * JPA entity class for "BnkInstitucionfinancieraperiodo"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@ToString
@RequiredArgsConstructor
@Entity
@Table(name="bnk_institucionfinancieraperiodo", catalog="adistemdb" )
public class BnkInstitucionfinancieraperiodo implements Serializable {

    @Serial
    private static final long serialVersionUID = 7525502835743716929L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Lob
    @Column(name="IDINSTITUCIONFINANCIERAPERIODO", nullable=false)
    private byte[]     idinstitucionfinancieraperiodo ;

    //--- ENTITY DATA FIELDS 
    @Lob
    @Column(name="IDINSTITUCIONFINANCIERA")
    private byte[]     idinstitucionfinanciera ;

    @Column(name="PERIODOANIO", nullable=false)
    private int        periodoanio ;

    @Column(name="PERIODOMES", nullable=false)
    private int        periodomes ;

    @Column(name="UNIDADESFINANCIADAS", nullable=false)
    private int        unidadesfinanciadas ;

    @Column(name="VENTAS", nullable=false)
    private int        ventas ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="IDINSTITUCIONFINANCIERA", referencedColumnName="IDINSTITUCIONFINANCIERA", insertable=false, updatable=false)
    private BnkInstitucionfinanciera bnkinstitucionfinanciera ; 


    @Override
    public final boolean equals(Object o) {
        if (this == o) return true;
        if (o == null) return false;
        Class<?> oEffectiveClass = o instanceof HibernateProxy ? ((HibernateProxy) o).getHibernateLazyInitializer().getPersistentClass() : o.getClass();
        Class<?> thisEffectiveClass = this instanceof HibernateProxy ? ((HibernateProxy) this).getHibernateLazyInitializer().getPersistentClass() : this.getClass();
        if (thisEffectiveClass != oEffectiveClass) return false;
        BnkInstitucionfinancieraperiodo that = (BnkInstitucionfinancieraperiodo) o;
        return getIdinstitucionfinancieraperiodo() != null && Arrays.equals(getIdinstitucionfinancieraperiodo(), that.getIdinstitucionfinancieraperiodo());
    }

    @Override
    public final int hashCode() {
        return this instanceof HibernateProxy ? ((HibernateProxy) this).getHibernateLazyInitializer().getPersistentClass().hashCode() : getClass().hashCode();
    }
}
