/*
 * Created on 2025-12-11 ( 10:43:56 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.entities;

import java.io.Serializable;
import java.util.List;
import jakarta.persistence.*;

/**
 * JPA entity class for "BnkInstitucionfinanciera"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="bnk_institucionfinanciera", catalog="adistemdb" )
public class BnkInstitucionfinanciera implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Lob
    @Column(name="IDINSTITUCIONFINANCIERA", nullable=false)
    private byte[]     idinstitucionfinanciera ;

    //--- ENTITY DATA FIELDS 
    @Column(name="NOMBRE", nullable=false, length=255)
    private String     nombre ;

    @Column(name="CLAVE", nullable=false, length=255)
    private String     clave ;

    @Column(name="ORDEN", nullable=false)
    private int        orden ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="bnkinstitucionfinanciera")
    private List<BnkInstitucionfinancieraperiodo> bnkinstitucionfinancieraperiodoList ; 


    /**
     * Constructor
     */
    public BnkInstitucionfinanciera() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setIdinstitucionfinanciera( byte[] idinstitucionfinanciera ) {
        this.idinstitucionfinanciera = idinstitucionfinanciera ;
    }
    public byte[] getIdinstitucionfinanciera() {
        return this.idinstitucionfinanciera;
    }

    public void setNombre( String nombre ) {
        this.nombre = nombre ;
    }
    public String getNombre() {
        return this.nombre;
    }

    public void setClave( String clave ) {
        this.clave = clave ;
    }
    public String getClave() {
        return this.clave;
    }

    public void setOrden( int orden ) {
        this.orden = orden ;
    }
    public int getOrden() {
        return this.orden;
    }

    //--- GETTERS FOR LINKS
    public List<BnkInstitucionfinancieraperiodo> getBnkinstitucionfinancieraperiodoList() {
        return this.bnkinstitucionfinancieraperiodoList;
    } 

    //--- toString specific method
	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("BnkInstitucionfinanciera[");
		// attribute 'idinstitucionfinanciera' (type byte[]) not usable in toString() 
		sb.append("nombre=").append(nombre);
		sb.append(separator).append("clave=").append(clave);
		sb.append(separator).append("orden=").append(orden);
		sb.append("]");
		return sb.toString();
	}
}
