/*
 * Created on 2026-02-11 ( 11:29:05 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.entities;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;
import lombok.ToString;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.List;

/**
 * JPA entity class for "LogCarga"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@ToString
@RequiredArgsConstructor
@Entity
@Table(name="log_carga", catalog="adistemdb" )
public class LogCarga implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Lob
    @Column(name="IDCARGA", nullable=false)
    private byte[]     idcarga ;

    //--- ENTITY DATA FIELDS 
    @Column(name="NOMBRE", nullable=false, length=255)
    private String     nombre ;

    @Column(name="TIPO", length=255)
    private String     tipo ;

    @Column(name="INICIO")
    private LocalDateTime inicio ;

    @Column(name="FIN")
    private LocalDateTime fin ;

    @Column(name="DESCRIPCION", length=2000)
    private String     descripcion ;

    @Column(name="ACTIVO", nullable=false)
    private boolean    activo ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="logcarga")
    private List<VhcDaacuota> vhcdaacuotaList ;

    @OneToMany(mappedBy="logcarga")
    private List<VhcReembolso> vhcreembolsoList ;


}
