/*
 * Created on 2025-11-07 ( 16:16:33 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.entities;

import java.io.Serializable;
import java.util.List;
import jakarta.persistence.*;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

/**
 * JPA entity class for "VhcAnio"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="vhc_anio", catalog="adistemdb" )
@Setter
@Getter
@NoArgsConstructor
public class VhcAnio implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @Lob
    @Column(name="IDANIO", nullable=false, columnDefinition = "TINYBLOB")
    @JdbcTypeCode(SqlTypes.BLOB)
    private byte[]  idanio ;

    //--- OTHER DATA FIELDS 
    @Column(name="NOMBRE", nullable=false, length=255)
    private String     nombre ;

    @Lob
    @Column(name="IDVERSION")
    private byte[]     idversion ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="IDVERSION", referencedColumnName="IDVERSION", insertable=false, updatable=false)
    private VhcVersion vhcversion ; 

    @OneToMany(mappedBy="vhcanio")
    private List<VhcPeriodo> vhcperiodoList ; 



}
