/*
 * Created on 2026-02-11 ( 11:29:05 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.entities;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;
import lombok.ToString;

import java.io.Serializable;

/**
 * JPA entity class for "VhcBoletinpreciogasto"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@ToString
@RequiredArgsConstructor
@Entity
@Table(name="vhc_boletinpreciogasto", catalog="adistemdb" )
public class VhcBoletinpreciogasto implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Lob
    @Column(name="IDBOLETINPRECIOGASTO", nullable=false)
    private byte[]     idboletinpreciogasto ;

    //--- ENTITY DATA FIELDS 
    @Column(name="NOMBRE", nullable=false, length=255)
    private String     nombre ;

    @Lob
    @Column(name="IDBOLETINPRECIO")
    private byte[]     idboletinprecio ;

    @Column(name="DISTRIBUIDOR", length=255)
    private String     distribuidor ;

    @Column(name="PUBLICO", length=255)
    private String     publico ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="IDBOLETINPRECIO", referencedColumnName="IDBOLETINPRECIO", insertable=false, updatable=false)
    private VhcBoletinprecio vhcboletinprecio ;


}
