/*
 * Created on 2026-02-11 ( 11:29:05 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.entities;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;
import lombok.ToString;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;

/**
 * JPA entity class for "VhcBoletinprecio"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@ToString
@RequiredArgsConstructor
@Entity
@Table(name="vhc_boletinprecio", catalog="adistemdb" )
public class VhcBoletinprecio implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Lob
    @Column(name="IDBOLETINPRECIO", nullable=false)
    private byte[]     idboletinprecio ;

    //--- ENTITY DATA FIELDS 
    @Lob
    @Column(name="IDANIO")
    private byte[]     idanio ;

    @Column(name="BODYMODELCPOS", length=255)
    private String     bodymodelcpos ;

    @Column(name="VERSIONARCHIVO", length=255)
    private String     versionarchivo ;

    @Column(name="ANIOMYARCHIVO", length=255)
    private String     aniomyarchivo ;

    @Column(name="FECHAINICIO")
    private LocalDateTime fechainicio ;

    @Column(name="DISTRIBUIDORUNIDADBASICA", nullable=false)
    private BigDecimal distribuidorunidadbasica ;

    @Column(name="DISTRIBUIDORCONTENIDOSUBTOTAL", nullable=false)
    private BigDecimal distribuidorcontenidosubtotal ;

    @Column(name="DISTRIBUIDORGASTOSUBTOTAL", nullable=false)
    private BigDecimal distribuidorgastosubtotal ;

    @Column(name="DISTRIBUIDORISAN", nullable=false)
    private BigDecimal distribuidorisan ;

    @Column(name="DISTRIBUIDORIVA", nullable=false)
    private BigDecimal distribuidoriva ;

    @Column(name="DISTRIBUIDORTOTAL", nullable=false)
    private BigDecimal distribuidortotal ;

    @Column(name="PUBLICOUNIDADBASICA", nullable=false)
    private BigDecimal publicounidadbasica ;

    @Column(name="PUBLICOCONTENIDOSUBTOTAL", nullable=false)
    private BigDecimal publicocontenidosubtotal ;

    @Column(name="PUBLICOGASTOSUBTOTAL", nullable=false)
    private BigDecimal publicogastosubtotal ;

    @Column(name="PUBLICOISAN", nullable=false)
    private BigDecimal publicoisan ;

    @Column(name="PUBLICOIVA", nullable=false)
    private BigDecimal publicoiva ;

    @Column(name="PUBLICOTOTAL", nullable=false)
    private BigDecimal publicototal ;

    @Lob
    @Column(name="IDCARGA")
    private byte[]     idcarga ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="IDANIO", referencedColumnName="IDANIO", insertable=false, updatable=false)
    private VhcAnio vhcanio ;

    @OneToMany(mappedBy="vhcboletinprecio")
    private List<VhcBoletinpreciogasto> vhcboletinpreciogastoList ;



}
