/*
 * Created on 2026-02-11 ( 11:29:05 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.entities;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;
import lombok.ToString;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * JPA entity class for "VhcDaacuota"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@ToString
@RequiredArgsConstructor
@Entity
@Table(name="vhc_daacuota", catalog="adistemdb" )
public class VhcDaacuota implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Lob
    @Column(name="IDDAACUOTA", nullable=false)
    private byte[]     iddaacuota ;

    //--- ENTITY DATA FIELDS 
    @Lob
    @Column(name="IDANIO")
    private byte[]     idanio ;

    @Column(name="PERIODOANIO", nullable=false)
    private int        periodoanio ;

    @Column(name="PERIODOMES", nullable=false)
    private int        periodomes ;

    @Column(name="FECHAINICIO")
    private LocalDateTime fechainicio ;

    @Column(name="FECHAFIN")
    private LocalDateTime fechafin ;

    @Column(name="DAACUOTA", nullable=false)
    private BigDecimal daacuota ;

    @Column(name="MARCAARCHIVO", length=255)
    private String     marcaarchivo ;

    @Column(name="REDDISTRIBUCIONARCHIVO", length=255)
    private String     reddistribucionarchivo ;

    @Column(name="VERSIONARCHIVO", length=255)
    private String     versionarchivo ;

    @Column(name="ANIOMYARCHIVO", length=255)
    private String     aniomyarchivo ;

    @Column(name="BODYMODELCPOS", length=255)
    private String     bodymodelcpos ;

    @Lob
    @Column(name="IDCARGA")
    private byte[]     idcarga ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="IDANIO", referencedColumnName="IDANIO", insertable=false, updatable=false)
    private VhcAnio vhcanio ;

    @ManyToOne
    @JoinColumn(name="IDCARGA", referencedColumnName="IDCARGA", insertable=false, updatable=false)
    private LogCarga logcarga ;


}
