/*
 * Created on 2025-11-07 ( 16:16:33 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.entities;

import java.io.Serializable;
import java.util.List;
import jakarta.persistence.*;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

/**
 * JPA entity class for "VhcFabricante"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="vhc_fabricante", catalog="adistemdb" )
public class VhcFabricante implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @Column(name="IDFABRICANTE", nullable=false)
    @JdbcTypeCode(SqlTypes.BINARY)
    private byte[]     idfabricante ;

    //--- OTHER DATA FIELDS 
    @Column(name="NOMBRE", nullable=false, length=255)
    private String     nombre ;

    @Column(name="CLAVE", nullable=false, length=255)
    private String     clave ;

    @Column(name="ORDEN", nullable=false)
    private int        orden ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="vhcfabricante")
    private List<VhcFabricantemarca> vhcfabricantemarcaList ; 

    /**
     * Constructor
     */
    public VhcFabricante() {
		super();
    }
    
    public void setIdfabricante( byte[] idfabricante ) {
        this.idfabricante = idfabricante ;
    }
    public byte[] getIdfabricante() {
        return this.idfabricante;
    }

    public void setNombre( String nombre ) {
        this.nombre = nombre ;
    }
    public String getNombre() {
        return this.nombre;
    }

    public void setClave( String clave ) {
        this.clave = clave ;
    }
    public String getClave() {
        return this.clave;
    }

    public void setOrden( int orden ) {
        this.orden = orden ;
    }
    public int getOrden() {
        return this.orden;
    }

    public List<VhcFabricantemarca> getVhcfabricantemarcaList() {
        return this.vhcfabricantemarcaList;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("VhcFabricante[");
		// attribute 'idfabricante' (type byte[]) not usable in toString() 
		sb.append("nombre=").append(nombre);
		sb.append(separator).append("clave=").append(clave);
		sb.append(separator).append("orden=").append(orden);
		sb.append("]");
		return sb.toString();
	}

}
