/*
 * Created on 2025-11-07 ( 16:16:33 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;

/**
 * JPA entity class for "VhcFabricantemarca"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="vhc_fabricantemarca", catalog="adistemdb" )
public class VhcFabricantemarca implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @Lob
    @Column(name="IDFABRICANTEMARCA", nullable=false)
    private byte[]     idfabricantemarca ;

    //--- OTHER DATA FIELDS 
    @Lob
    @Column(name="IDFABRICANTE")
    private byte[]     idfabricante ;

    @Lob
    @Column(name="IDMARCA")
    private byte[]     idmarca ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="IDFABRICANTE", referencedColumnName="IDFABRICANTE", insertable=false, updatable=false)
    private VhcFabricante vhcfabricante ; 

    /**
     * Constructor
     */
    public VhcFabricantemarca() {
		super();
    }
    
    public void setIdfabricantemarca( byte[] idfabricantemarca ) {
        this.idfabricantemarca = idfabricantemarca ;
    }
    public byte[] getIdfabricantemarca() {
        return this.idfabricantemarca;
    }

    public void setIdfabricante( byte[] idfabricante ) {
        this.idfabricante = idfabricante ;
    }
    public byte[] getIdfabricante() {
        return this.idfabricante;
    }

    public void setIdmarca( byte[] idmarca ) {
        this.idmarca = idmarca ;
    }
    public byte[] getIdmarca() {
        return this.idmarca;
    }

    public VhcFabricante getVhcfabricante() {
        return this.vhcfabricante;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("VhcFabricantemarca[");
		// attribute 'idfabricantemarca' (type byte[]) not usable in toString() 
		// attribute 'idfabricante' (type byte[]) not usable in toString() 
		// attribute 'idmarca' (type byte[]) not usable in toString() 
		sb.append("]");
		return sb.toString();
	}

}
