/*
 * Created on 2025-11-07 ( 16:16:33 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;

/**
 * JPA entity class for "VhcGrupomarca"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="vhc_grupomarca", catalog="adistemdb" )
public class VhcGrupomarca implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @Lob
    @Column(name="IDGRUPOMARCA", nullable=false)
    private byte[]     idgrupomarca ;

    //--- OTHER DATA FIELDS 
    @Lob
    @Column(name="IDGRUPO")
    private byte[]     idgrupo ;

    @Lob
    @Column(name="IDMARCA")
    private byte[]     idmarca ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="IDGRUPO", referencedColumnName="IDGRUPO", insertable=false, updatable=false)
    private VhcGrupo   vhcgrupo ; 

    /**
     * Constructor
     */
    public VhcGrupomarca() {
		super();
    }
    
    public void setIdgrupomarca( byte[] idgrupomarca ) {
        this.idgrupomarca = idgrupomarca ;
    }
    public byte[] getIdgrupomarca() {
        return this.idgrupomarca;
    }

    public void setIdgrupo( byte[] idgrupo ) {
        this.idgrupo = idgrupo ;
    }
    public byte[] getIdgrupo() {
        return this.idgrupo;
    }

    public void setIdmarca( byte[] idmarca ) {
        this.idmarca = idmarca ;
    }
    public byte[] getIdmarca() {
        return this.idmarca;
    }

    public VhcGrupo getVhcgrupo() {
        return this.vhcgrupo;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("VhcGrupomarca[");
		// attribute 'idgrupomarca' (type byte[]) not usable in toString() 
		// attribute 'idgrupo' (type byte[]) not usable in toString() 
		// attribute 'idmarca' (type byte[]) not usable in toString() 
		sb.append("]");
		return sb.toString();
	}

}
