/*
 * Created on 2025-11-07 ( 16:16:33 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.entities;

import java.io.Serializable;
import java.util.List;
import jakarta.persistence.*;

/**
 * JPA entity class for "VhcGrupo"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="vhc_grupo", catalog="adistemdb" )
public class VhcGrupo implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @Lob
    @Column(name="IDGRUPO", nullable=false)
    private byte[]     idgrupo ;

    //--- OTHER DATA FIELDS 
    @Column(name="NOMBRE", nullable=false, length=255)
    private String     nombre ;

    @Column(name="CLAVE", nullable=false, length=255)
    private String     clave ;

    @Column(name="ORDEN", nullable=false)
    private int        orden ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="vhcgrupo")
    private List<VhcGrupomarca> vhcgrupomarcaList ; 

    @OneToMany(mappedBy="vhcgrupo")
    private List<VhcGrupoperiodoventausa> vhcgrupoperiodoventausaList ; 

    /**
     * Constructor
     */
    public VhcGrupo() {
		super();
    }
    
    public void setIdgrupo( byte[] idgrupo ) {
        this.idgrupo = idgrupo ;
    }
    public byte[] getIdgrupo() {
        return this.idgrupo;
    }

    public void setNombre( String nombre ) {
        this.nombre = nombre ;
    }
    public String getNombre() {
        return this.nombre;
    }

    public void setClave( String clave ) {
        this.clave = clave ;
    }
    public String getClave() {
        return this.clave;
    }

    public void setOrden( int orden ) {
        this.orden = orden ;
    }
    public int getOrden() {
        return this.orden;
    }

    public List<VhcGrupomarca> getVhcgrupomarcaList() {
        return this.vhcgrupomarcaList;
    } 

    public List<VhcGrupoperiodoventausa> getVhcgrupoperiodoventausaList() {
        return this.vhcgrupoperiodoventausaList;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("VhcGrupo[");
		// attribute 'idgrupo' (type byte[]) not usable in toString() 
		sb.append("nombre=").append(nombre);
		sb.append(separator).append("clave=").append(clave);
		sb.append(separator).append("orden=").append(orden);
		sb.append("]");
		return sb.toString();
	}

}
