/*
 * Created on 2025-11-07 ( 16:16:33 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.entities;

import java.io.Serializable;
import java.util.List;
import jakarta.persistence.*;
import lombok.Data;

/**
 * JPA entity class for "VhcGrupo"
 *
 * @author Telosys
 *
 */
@Data
@Entity
@Table(name="vhc_grupo", catalog="adistemdb" )
public class VhcGrupo implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @Lob
    @Column(name="IDGRUPO", nullable=false)
    private byte[]     idgrupo ;

    //--- OTHER DATA FIELDS 
    @Column(name="NOMBRE", nullable=false, length=255)
    private String     nombre ;

    @Column(name="CLAVE", nullable=false, length=255)
    private String     clave ;

    @Column(name="ORDEN", nullable=false)
    private int        orden ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="vhcgrupo", fetch = FetchType.LAZY)
    private List<VhcGrupomarca> vhcgrupomarcaList ; 


	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("VhcGrupo[");
		// attribute 'idgrupo' (type byte[]) not usable in toString() 
		sb.append("nombre=").append(nombre);
		sb.append(separator).append("clave=").append(clave);
		sb.append(separator).append("orden=").append(orden);
		sb.append("]");
		return sb.toString();
	}

}
