/*
 * Created on 2025-11-07 ( 16:16:33 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;

/**
 * JPA entity class for "VhcGrupoperiodoventausa"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="vhc_grupoperiodoventausa", catalog="adistemdb" )
public class VhcGrupoperiodoventausa implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @Lob
    @Column(name="IDGRUPOPERIODOVENTAUSA", nullable=false)
    private byte[]     idgrupoperiodoventausa ;

    //--- OTHER DATA FIELDS 
    @Lob
    @Column(name="IDGRUPO")
    private byte[]     idgrupo ;

    @Column(name="PERIODOANIO", nullable=false)
    private int        periodoanio ;

    @Column(name="PERIODOTRIMESTRE", nullable=false)
    private int        periodotrimestre ;

    @Column(name="CANTIDAD", nullable=false)
    private int        cantidad ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="IDGRUPO", referencedColumnName="IDGRUPO", insertable=false, updatable=false)
    private VhcGrupo   vhcgrupo ; 

    /**
     * Constructor
     */
    public VhcGrupoperiodoventausa() {
		super();
    }
    
    public void setIdgrupoperiodoventausa( byte[] idgrupoperiodoventausa ) {
        this.idgrupoperiodoventausa = idgrupoperiodoventausa ;
    }
    public byte[] getIdgrupoperiodoventausa() {
        return this.idgrupoperiodoventausa;
    }

    public void setIdgrupo( byte[] idgrupo ) {
        this.idgrupo = idgrupo ;
    }
    public byte[] getIdgrupo() {
        return this.idgrupo;
    }

    public void setPeriodoanio( int periodoanio ) {
        this.periodoanio = periodoanio ;
    }
    public int getPeriodoanio() {
        return this.periodoanio;
    }

    public void setPeriodotrimestre( int periodotrimestre ) {
        this.periodotrimestre = periodotrimestre ;
    }
    public int getPeriodotrimestre() {
        return this.periodotrimestre;
    }

    public void setCantidad( int cantidad ) {
        this.cantidad = cantidad ;
    }
    public int getCantidad() {
        return this.cantidad;
    }

    public VhcGrupo getVhcgrupo() {
        return this.vhcgrupo;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("VhcGrupoperiodoventausa[");
		// attribute 'idgrupoperiodoventausa' (type byte[]) not usable in toString() 
		// attribute 'idgrupo' (type byte[]) not usable in toString() 
		sb.append("periodoanio=").append(periodoanio);
		sb.append(separator).append("periodotrimestre=").append(periodotrimestre);
		sb.append(separator).append("cantidad=").append(cantidad);
		sb.append("]");
		return sb.toString();
	}

}
