/*
 * Created on 2026-02-11 ( 11:29:05 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.entities;

import com.organizame.reportes.entities.VhcAnio;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;
import lombok.ToString;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * JPA entity class for "VhcIncentivo"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@ToString
@RequiredArgsConstructor
@Entity
@Table(name="vhc_incentivo", catalog="adistemdb" )
public class VhcIncentivo implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Lob
    @Column(name="IDINCENTIVO", nullable=false)
    private byte[]     idincentivo ;

    //--- ENTITY DATA FIELDS 
    @Lob
    @Column(name="IDANIO", nullable=false)
    private byte[]     idanio ;

    @Column(name="PERIODOANIO", nullable=false)
    private int        periodoanio ;

    @Column(name="PERIODOMES", nullable=false)
    private int        periodomes ;

    @Column(name="FECHAINICIO")
    private LocalDateTime fechainicio ;

    @Column(name="FECHAFIN")
    private LocalDateTime fechafin ;

    @Column(name="PRECIOLISTA", nullable=false)
    private BigDecimal preciolista ;

    @Column(name="CONTADODESCUENTO", nullable=false)
    private BigDecimal contadodescuento ;

    @Column(name="CONTADOPARTICIPACIONDISTRIBUIDORES", nullable=false)
    private BigDecimal contadoparticipaciondistribuidores ;

    @Column(name="CONTADOTOTALDESCUENTOS", nullable=false)
    private BigDecimal contadototaldescuentos ;

    @Column(name="CONTADOPRECIO", nullable=false)
    private BigDecimal contadoprecio ;

    @Column(name="CONTADOSEGUROGRATIS", length=255)
    private String     contadosegurogratis ;

    @Column(name="CONTADOMANTENIMIENTOGRATIS", length=255)
    private String     contadomantenimientogratis ;

    @Column(name="FINANCIAMIENTODESCUENTOPROMOCIONAL", nullable=false)
    private BigDecimal financiamientodescuentopromocional ;

    @Column(name="FINANCIAMIENTOPARTICIPACIONDISTRIBUIDORES", nullable=false)
    private BigDecimal financiamientoparticipaciondistribuidores ;

    @Column(name="FINANCIAMIENTOTOTALDESCUENTOS", nullable=false)
    private BigDecimal financiamientototaldescuentos ;

    @Column(name="FINANCIAMIENTOPRECIOPROMOCIONAL", nullable=false)
    private BigDecimal financiamientopreciopromocional ;

    @Column(name="FINANCIAMIENTOTASADESDE", length=255)
    private String     financiamientotasadesde ;

    @Column(name="FINANCIAMIENTOSEGUROGRATIS", length=255)
    private String     financiamientosegurogratis ;

    @Column(name="FINANCIAMIENTOMANTENIMIENTOGRATIS", length=255)
    private String     financiamientomantenimientogratis ;

    @Column(name="FINANCIAMIENTOALTERNODESCUENTOPROMOCIONAL", nullable=false)
    private BigDecimal financiamientoalternodescuentopromocional ;

    @Column(name="FINANCIAMIENTOALTERNOPARTICIPACIONDISTRIBUIDORES", nullable=false)
    private BigDecimal financiamientoalternoparticipaciondistribuidores ;

    @Column(name="FINANCIAMIENTOALTERNOTOTALDESCUENTOS", nullable=false)
    private BigDecimal financiamientoalternototaldescuentos ;

    @Column(name="FINANCIAMIENTOALTERNOPRECIOPROMOCIONAL", nullable=false)
    private BigDecimal financiamientoalternopreciopromocional ;

    @Column(name="FINANCIAMIENTOALTERNOTASADESDE", length=255)
    private String     financiamientoalternotasadesde ;

    @Column(name="FINANCIAMIENTOALTERNOSEGUROGRATIS", length=255)
    private String     financiamientoalternosegurogratis ;

    @Column(name="MESESSININTERESES", length=255)
    private String     mesessinintereses ;

    @Column(name="MESESSININTERESESPRECIO", length=255)
    private String     mesessininteresesprecio ;

    @Column(name="MARCAARCHIVO", length=255)
    private String     marcaarchivo ;

    @Column(name="MODELOARCHIVO", length=255)
    private String     modeloarchivo ;

    @Column(name="VERSIONARCHIVO", length=255)
    private String     versionarchivo ;

    @Column(name="ANIOARCHIVO", length=255)
    private String     anioarchivo ;

    @Lob
    @Column(name="IDCARGA")
    private byte[]     idcarga ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="IDANIO", referencedColumnName="IDANIO", insertable=false, updatable=false)
    private com.organizame.reportes.entities.VhcAnio vhcanio ;



}
