/*
 * Created on 2025-11-07 ( 16:16:34 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;

/**
 * JPA entity class for "VhcModeloalias"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="vhc_modeloalias", catalog="adistemdb" )
public class VhcModeloalias implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @Lob
    @Column(name="IDMODELOALIAS", nullable=false)
    private byte[]     idmodeloalias ;

    //--- OTHER DATA FIELDS 
    @Column(name="NOMBRE", nullable=false, length=255)
    private String     nombre ;

    @Lob
    @Column(name="IDMODELO")
    private byte[]     idmodelo ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="IDMODELO", referencedColumnName="IDMODELO", insertable=false, updatable=false)
    private VhcModelo  vhcmodelo ; 

    /**
     * Constructor
     */
    public VhcModeloalias() {
		super();
    }
    
    public void setIdmodeloalias( byte[] idmodeloalias ) {
        this.idmodeloalias = idmodeloalias ;
    }
    public byte[] getIdmodeloalias() {
        return this.idmodeloalias;
    }

    public void setNombre( String nombre ) {
        this.nombre = nombre ;
    }
    public String getNombre() {
        return this.nombre;
    }

    public void setIdmodelo( byte[] idmodelo ) {
        this.idmodelo = idmodelo ;
    }
    public byte[] getIdmodelo() {
        return this.idmodelo;
    }

    public VhcModelo getVhcmodelo() {
        return this.vhcmodelo;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("VhcModeloalias[");
		// attribute 'idmodeloalias' (type byte[]) not usable in toString() 
		sb.append("nombre=").append(nombre);
		// attribute 'idmodelo' (type byte[]) not usable in toString() 
		sb.append("]");
		return sb.toString();
	}

}
