/*
 * Created on 2025-11-07 ( 16:16:34 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;

/**
 * JPA entity class for "VhcModeloperiodoinegi"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="vhc_modeloperiodoinegi", catalog="adistemdb" )
public class VhcModeloperiodoinegi implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @Lob
    @Column(name="IDMODELOPERIODOINEGI", nullable=false)
    private byte[]     idmodeloperiodoinegi ;

    //--- OTHER DATA FIELDS 
    @Lob
    @Column(name="IDMODELO")
    private byte[]     idmodelo ;

    @Column(name="PERIODOANIO", nullable=false)
    private int        periodoanio ;

    @Column(name="PERIODOMES", nullable=false)
    private int        periodomes ;

    @Lob
    @Column(name="IDORIGEN")
    private byte[]     idorigen ;

    @Column(name="CANTIDAD", nullable=false)
    private int        cantidad ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="IDMODELO", referencedColumnName="IDMODELO", insertable=false, updatable=false)
    private VhcModelo  vhcmodelo ; 

    /**
     * Constructor
     */
    public VhcModeloperiodoinegi() {
		super();
    }
    
    public void setIdmodeloperiodoinegi( byte[] idmodeloperiodoinegi ) {
        this.idmodeloperiodoinegi = idmodeloperiodoinegi ;
    }
    public byte[] getIdmodeloperiodoinegi() {
        return this.idmodeloperiodoinegi;
    }

    public void setIdmodelo( byte[] idmodelo ) {
        this.idmodelo = idmodelo ;
    }
    public byte[] getIdmodelo() {
        return this.idmodelo;
    }

    public void setPeriodoanio( int periodoanio ) {
        this.periodoanio = periodoanio ;
    }
    public int getPeriodoanio() {
        return this.periodoanio;
    }

    public void setPeriodomes( int periodomes ) {
        this.periodomes = periodomes ;
    }
    public int getPeriodomes() {
        return this.periodomes;
    }

    public void setIdorigen( byte[] idorigen ) {
        this.idorigen = idorigen ;
    }
    public byte[] getIdorigen() {
        return this.idorigen;
    }

    public void setCantidad( int cantidad ) {
        this.cantidad = cantidad ;
    }
    public int getCantidad() {
        return this.cantidad;
    }

    public VhcModelo getVhcmodelo() {
        return this.vhcmodelo;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("VhcModeloperiodoinegi[");
		// attribute 'idmodeloperiodoinegi' (type byte[]) not usable in toString() 
		// attribute 'idmodelo' (type byte[]) not usable in toString() 
		sb.append("periodoanio=").append(periodoanio);
		sb.append(separator).append("periodomes=").append(periodomes);
		// attribute 'idorigen' (type byte[]) not usable in toString() 
		sb.append(separator).append("cantidad=").append(cantidad);
		sb.append("]");
		return sb.toString();
	}

}
