/*
 * Created on 2025-11-07 ( 16:16:34 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.entities;

import java.io.Serializable;
import java.util.List;
import jakarta.persistence.*;
import lombok.Data;
import lombok.ToString;

/**
 * JPA entity class for "VhcModelo"
 *
 * @author Telosys
 *
 */
@Data
@Entity
@ToString
@Table(name="vhc_modelo", catalog="adistemdb" )
public class VhcModelo implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @Lob
    @Column(name="IDMODELO", nullable=false)
    private byte[]     idmodelo ;

    @Column(name="NOMBRE", nullable=false, length=255)
    private String     nombre ;

    @Lob
    @Column(name="IDMARCA")
    private byte[]     idmarca ;

    @ManyToOne
    @JoinColumn(name="IDMARCA", referencedColumnName="IDMARCA", insertable=false, updatable=false)
    private VhcMarca   vhcmarca ; 

    @OneToMany(mappedBy="vhcmodelo")
    private List<VhcModeloalias> vhcmodeloaliasList ; 

    @OneToMany(mappedBy="vhcmodelo")
    private List<VhcModeloperiodo> vhcmodeloperiodoList ; 

    @OneToMany(mappedBy="vhcmodelo")
    private List<VhcModeloperiodoindustria> vhcmodeloperiodoindustriaList ; 

    @OneToMany(mappedBy="vhcmodelo")
    private List<VhcModeloperiodoinegi> vhcmodeloperiodoinegiList ; 

    @OneToMany(mappedBy="vhcmodelo")
    private List<VhcModeloperiodoventausa> vhcmodeloperiodoventausaList ; 

    @OneToMany(mappedBy="vhcmodelo")
    private List<VhcVersion> vhcversionList ;



}
