/*
 * Created on 2025-11-07 ( 16:16:34 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;

/**
 * JPA entity class for "VhcModeloperiodoventausa"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="vhc_modeloperiodoventausa", catalog="adistemdb" )
public class VhcModeloperiodoventausa implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @Lob
    @Column(name="IDMODELOPERIODOVENTAUSA", nullable=false)
    private byte[]     idmodeloperiodoventausa ;

    //--- OTHER DATA FIELDS 
    @Lob
    @Column(name="IDMODELO")
    private byte[]     idmodelo ;

    @Column(name="PERIODOANIO", nullable=false)
    private int        periodoanio ;

    @Column(name="PERIODOTRIMESTRE", nullable=false)
    private int        periodotrimestre ;

    @Column(name="CANTIDAD", nullable=false)
    private int        cantidad ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="IDMODELO", referencedColumnName="IDMODELO", insertable=false, updatable=false)
    private VhcModelo  vhcmodelo ; 

    /**
     * Constructor
     */
    public VhcModeloperiodoventausa() {
		super();
    }
    
    public void setIdmodeloperiodoventausa( byte[] idmodeloperiodoventausa ) {
        this.idmodeloperiodoventausa = idmodeloperiodoventausa ;
    }
    public byte[] getIdmodeloperiodoventausa() {
        return this.idmodeloperiodoventausa;
    }

    public void setIdmodelo( byte[] idmodelo ) {
        this.idmodelo = idmodelo ;
    }
    public byte[] getIdmodelo() {
        return this.idmodelo;
    }

    public void setPeriodoanio( int periodoanio ) {
        this.periodoanio = periodoanio ;
    }
    public int getPeriodoanio() {
        return this.periodoanio;
    }

    public void setPeriodotrimestre( int periodotrimestre ) {
        this.periodotrimestre = periodotrimestre ;
    }
    public int getPeriodotrimestre() {
        return this.periodotrimestre;
    }

    public void setCantidad( int cantidad ) {
        this.cantidad = cantidad ;
    }
    public int getCantidad() {
        return this.cantidad;
    }

    public VhcModelo getVhcmodelo() {
        return this.vhcmodelo;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("VhcModeloperiodoventausa[");
		// attribute 'idmodeloperiodoventausa' (type byte[]) not usable in toString() 
		// attribute 'idmodelo' (type byte[]) not usable in toString() 
		sb.append("periodoanio=").append(periodoanio);
		sb.append(separator).append("periodotrimestre=").append(periodotrimestre);
		sb.append(separator).append("cantidad=").append(cantidad);
		sb.append("]");
		return sb.toString();
	}

}
