/*
 * Created on 2025-11-07 ( 16:16:34 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.Data;

/**
 * JPA entity class for "VhcMarcaperiodo"
 *
 * @author Telosys
 *
 */
@Data
@Entity
@Table(name="vhc_marcaperiodo", catalog="adistemdb" )
public class VhcMarcaperiodo implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @Lob
    @Column(name="IDMARCAPERIODO", nullable=false)
    private byte[]     idmarcaperiodo ;

    //--- OTHER DATA FIELDS 
    @Lob
    @Column(name="IDMARCA")
    private byte[]     idmarca ;

    @Column(name="PERIODOANIO", nullable=false)
    private int        periodoanio ;

    @Column(name="PERIODOMES", nullable=false)
    private int        periodomes ;

    @Column(name="VENTAPUNTOS", nullable=false)
    private int        ventapuntos ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="IDMARCA", referencedColumnName="IDMARCA", insertable=false, updatable=false)
    private VhcMarca   vhcmarca ;



}
