/*
 * Created on 2025-11-07 ( 16:16:34 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;

/**
 * JPA entity class for "VhcMarcaplantilla"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="vhc_marcaplantilla", catalog="adistemdb" )
public class VhcMarcaplantilla implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @Lob
    @Column(name="IDMARCAPLANTILLA", nullable=false)
    private byte[]     idmarcaplantilla ;

    //--- OTHER DATA FIELDS 
    @Column(name="ORDEN", nullable=false)
    private int        orden ;

    @Column(name="ARCHIVO", length=255)
    private String     archivo ;

    @Lob
    @Column(name="IDMARCA")
    private byte[]     idmarca ;

    @Lob
    @Column(name="IDMARCAPLANTILLATIPO")
    private byte[]     idmarcaplantillatipo ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="IDMARCA", referencedColumnName="IDMARCA", insertable=false, updatable=false)
    private VhcMarca   vhcmarca ; 

    /**
     * Constructor
     */
    public VhcMarcaplantilla() {
		super();
    }
    
    public void setIdmarcaplantilla( byte[] idmarcaplantilla ) {
        this.idmarcaplantilla = idmarcaplantilla ;
    }
    public byte[] getIdmarcaplantilla() {
        return this.idmarcaplantilla;
    }

    public void setOrden( int orden ) {
        this.orden = orden ;
    }
    public int getOrden() {
        return this.orden;
    }

    public void setArchivo( String archivo ) {
        this.archivo = archivo ;
    }
    public String getArchivo() {
        return this.archivo;
    }

    public void setIdmarca( byte[] idmarca ) {
        this.idmarca = idmarca ;
    }
    public byte[] getIdmarca() {
        return this.idmarca;
    }

    public void setIdmarcaplantillatipo( byte[] idmarcaplantillatipo ) {
        this.idmarcaplantillatipo = idmarcaplantillatipo ;
    }
    public byte[] getIdmarcaplantillatipo() {
        return this.idmarcaplantillatipo;
    }

    public VhcMarca getVhcmarca() {
        return this.vhcmarca;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("VhcMarcaplantilla[");
		// attribute 'idmarcaplantilla' (type byte[]) not usable in toString() 
		sb.append("orden=").append(orden);
		sb.append(separator).append("archivo=").append(archivo);
		// attribute 'idmarca' (type byte[]) not usable in toString() 
		// attribute 'idmarcaplantillatipo' (type byte[]) not usable in toString() 
		sb.append("]");
		return sb.toString();
	}

}
