/*
 * Created on 2025-11-07 ( 16:16:34 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;

/**
 * JPA entity class for "VhcMarcaperiodo"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="vhc_marcaperiodo", catalog="adistemdb" )
public class VhcMarcaperiodo implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @Lob
    @Column(name="IDMARCAPERIODO", nullable=false)
    private byte[]     idmarcaperiodo ;

    //--- OTHER DATA FIELDS 
    @Lob
    @Column(name="IDMARCA")
    private byte[]     idmarca ;

    @Column(name="PERIODOANIO", nullable=false)
    private int        periodoanio ;

    @Column(name="PERIODOMES", nullable=false)
    private int        periodomes ;

    @Column(name="VENTAPUNTOS", nullable=false)
    private int        ventapuntos ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="IDMARCA", referencedColumnName="IDMARCA", insertable=false, updatable=false)
    private VhcMarca   vhcmarca ; 

    /**
     * Constructor
     */
    public VhcMarcaperiodo() {
		super();
    }
    
    public void setIdmarcaperiodo( byte[] idmarcaperiodo ) {
        this.idmarcaperiodo = idmarcaperiodo ;
    }
    public byte[] getIdmarcaperiodo() {
        return this.idmarcaperiodo;
    }

    public void setIdmarca( byte[] idmarca ) {
        this.idmarca = idmarca ;
    }
    public byte[] getIdmarca() {
        return this.idmarca;
    }

    public void setPeriodoanio( int periodoanio ) {
        this.periodoanio = periodoanio ;
    }
    public int getPeriodoanio() {
        return this.periodoanio;
    }

    public void setPeriodomes( int periodomes ) {
        this.periodomes = periodomes ;
    }
    public int getPeriodomes() {
        return this.periodomes;
    }

    public void setVentapuntos( int ventapuntos ) {
        this.ventapuntos = ventapuntos ;
    }
    public int getVentapuntos() {
        return this.ventapuntos;
    }

    public VhcMarca getVhcmarca() {
        return this.vhcmarca;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("VhcMarcaperiodo[");
		// attribute 'idmarcaperiodo' (type byte[]) not usable in toString() 
		// attribute 'idmarca' (type byte[]) not usable in toString() 
		sb.append("periodoanio=").append(periodoanio);
		sb.append(separator).append("periodomes=").append(periodomes);
		sb.append(separator).append("ventapuntos=").append(ventapuntos);
		sb.append("]");
		return sb.toString();
	}

}
