/*
 * Created on 2025-11-07 ( 16:16:34 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;

/**
 * JPA entity class for "VhcMarcaarchivo"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="vhc_marcaarchivo", catalog="adistemdb" )
public class VhcMarcaarchivo implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @Lob
    @Column(name="IDMARCAARCHIVO", nullable=false)
    private byte[]     idmarcaarchivo ;

    //--- OTHER DATA FIELDS 
    @Column(name="ARCHIVO", length=255)
    private String     archivo ;

    @Lob
    @Column(name="IDMARCA")
    private byte[]     idmarca ;

    @Lob
    @Column(name="IDMARCAARCHIVOTIPO")
    private byte[]     idmarcaarchivotipo ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="IDMARCA", referencedColumnName="IDMARCA", insertable=false, updatable=false)
    private VhcMarca   vhcmarca ; 

    /**
     * Constructor
     */
    public VhcMarcaarchivo() {
		super();
    }
    
    public void setIdmarcaarchivo( byte[] idmarcaarchivo ) {
        this.idmarcaarchivo = idmarcaarchivo ;
    }
    public byte[] getIdmarcaarchivo() {
        return this.idmarcaarchivo;
    }

    public void setArchivo( String archivo ) {
        this.archivo = archivo ;
    }
    public String getArchivo() {
        return this.archivo;
    }

    public void setIdmarca( byte[] idmarca ) {
        this.idmarca = idmarca ;
    }
    public byte[] getIdmarca() {
        return this.idmarca;
    }

    public void setIdmarcaarchivotipo( byte[] idmarcaarchivotipo ) {
        this.idmarcaarchivotipo = idmarcaarchivotipo ;
    }
    public byte[] getIdmarcaarchivotipo() {
        return this.idmarcaarchivotipo;
    }

    public VhcMarca getVhcmarca() {
        return this.vhcmarca;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("VhcMarcaarchivo[");
		// attribute 'idmarcaarchivo' (type byte[]) not usable in toString() 
		sb.append("archivo=").append(archivo);
		// attribute 'idmarca' (type byte[]) not usable in toString() 
		// attribute 'idmarcaarchivotipo' (type byte[]) not usable in toString() 
		sb.append("]");
		return sb.toString();
	}

}
