/*
 * Created on 2025-11-07 ( 16:16:34 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.entities;

import java.io.Serializable;
import java.util.List;
import jakarta.persistence.*;

/**
 * JPA entity class for "VhcModelo"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="vhc_modelo", catalog="adistemdb" )
public class VhcModelo implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @Lob
    @Column(name="IDMODELO", nullable=false)
    private byte[]     idmodelo ;

    //--- OTHER DATA FIELDS 
    @Column(name="NOMBRE", nullable=false, length=255)
    private String     nombre ;

    @Lob
    @Column(name="IDMARCA")
    private byte[]     idmarca ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="IDMARCA", referencedColumnName="IDMARCA", insertable=false, updatable=false)
    private VhcMarca   vhcmarca ; 

    @OneToMany(mappedBy="vhcmodelo")
    private List<VhcModeloalias> vhcmodeloaliasList ; 

    @OneToMany(mappedBy="vhcmodelo")
    private List<VhcModeloperiodo> vhcmodeloperiodoList ; 

    @OneToMany(mappedBy="vhcmodelo")
    private List<VhcModeloperiodoindustria> vhcmodeloperiodoindustriaList ; 

    @OneToMany(mappedBy="vhcmodelo")
    private List<VhcModeloperiodoinegi> vhcmodeloperiodoinegiList ; 

    @OneToMany(mappedBy="vhcmodelo")
    private List<VhcModeloperiodoventausa> vhcmodeloperiodoventausaList ; 

    @OneToMany(mappedBy="vhcmodelo")
    private List<VhcVersion> vhcversionList ; 

    /**
     * Constructor
     */
    public VhcModelo() {
		super();
    }
    
    public void setIdmodelo( byte[] idmodelo ) {
        this.idmodelo = idmodelo ;
    }
    public byte[] getIdmodelo() {
        return this.idmodelo;
    }

    public void setNombre( String nombre ) {
        this.nombre = nombre ;
    }
    public String getNombre() {
        return this.nombre;
    }

    public void setIdmarca( byte[] idmarca ) {
        this.idmarca = idmarca ;
    }
    public byte[] getIdmarca() {
        return this.idmarca;
    }

    public VhcMarca getVhcmarca() {
        return this.vhcmarca;
    } 

    public List<VhcModeloalias> getVhcmodeloaliasList() {
        return this.vhcmodeloaliasList;
    } 

    public List<VhcModeloperiodo> getVhcmodeloperiodoList() {
        return this.vhcmodeloperiodoList;
    } 

    public List<VhcModeloperiodoindustria> getVhcmodeloperiodoindustriaList() {
        return this.vhcmodeloperiodoindustriaList;
    } 

    public List<VhcModeloperiodoinegi> getVhcmodeloperiodoinegiList() {
        return this.vhcmodeloperiodoinegiList;
    } 

    public List<VhcModeloperiodoventausa> getVhcmodeloperiodoventausaList() {
        return this.vhcmodeloperiodoventausaList;
    } 

    public List<VhcVersion> getVhcversionList() {
        return this.vhcversionList;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("VhcModelo[");
		// attribute 'idmodelo' (type byte[]) not usable in toString() 
		sb.append("nombre=").append(nombre);
		// attribute 'idmarca' (type byte[]) not usable in toString() 
		sb.append("]");
		return sb.toString();
	}

}
