/*
 * Created on 2025-11-07 ( 16:16:34 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;

/**
 * JPA entity class for "VhcMarcaplantillatipobase"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="vhc_marcaplantillatipobase", catalog="adistemdb" )
public class VhcMarcaplantillatipobase implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @Lob
    @Column(name="IDMARCAPLANTILLATIPOBASE", nullable=false)
    private byte[]     idmarcaplantillatipobase ;

    //--- OTHER DATA FIELDS 
    @Column(name="DESCRIPCION", length=2000)
    private String     descripcion ;

    @Column(name="ORDEN", nullable=false)
    private int        orden ;

    @Column(name="ARCHIVO", length=255)
    private String     archivo ;

    @Lob
    @Column(name="IDMARCAPLANTILLATIPO")
    private byte[]     idmarcaplantillatipo ;

    @Column(name="FECHAINICIO", length=255)
    private String     fechainicio ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="IDMARCAPLANTILLATIPO", referencedColumnName="IDMARCAPLANTILLATIPO", insertable=false, updatable=false)
    private VhcMarcaplantillatipo vhcmarcaplantillatipo ; 

    /**
     * Constructor
     */
    public VhcMarcaplantillatipobase() {
		super();
    }
    
    public void setIdmarcaplantillatipobase( byte[] idmarcaplantillatipobase ) {
        this.idmarcaplantillatipobase = idmarcaplantillatipobase ;
    }
    public byte[] getIdmarcaplantillatipobase() {
        return this.idmarcaplantillatipobase;
    }

    public void setDescripcion( String descripcion ) {
        this.descripcion = descripcion ;
    }
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setOrden( int orden ) {
        this.orden = orden ;
    }
    public int getOrden() {
        return this.orden;
    }

    public void setArchivo( String archivo ) {
        this.archivo = archivo ;
    }
    public String getArchivo() {
        return this.archivo;
    }

    public void setIdmarcaplantillatipo( byte[] idmarcaplantillatipo ) {
        this.idmarcaplantillatipo = idmarcaplantillatipo ;
    }
    public byte[] getIdmarcaplantillatipo() {
        return this.idmarcaplantillatipo;
    }

    public void setFechainicio( String fechainicio ) {
        this.fechainicio = fechainicio ;
    }
    public String getFechainicio() {
        return this.fechainicio;
    }

    public VhcMarcaplantillatipo getVhcmarcaplantillatipo() {
        return this.vhcmarcaplantillatipo;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("VhcMarcaplantillatipobase[");
		// attribute 'idmarcaplantillatipobase' (type byte[]) not usable in toString() 
		sb.append("descripcion=").append(descripcion);
		sb.append(separator).append("orden=").append(orden);
		sb.append(separator).append("archivo=").append(archivo);
		// attribute 'idmarcaplantillatipo' (type byte[]) not usable in toString() 
		sb.append(separator).append("fechainicio=").append(fechainicio);
		sb.append("]");
		return sb.toString();
	}

}
