/*
 * Created on 2025-11-07 ( 16:16:34 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.entities;

import java.io.Serializable;
import java.util.List;
import jakarta.persistence.*;

/**
 * JPA entity class for "VhcMarca"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="vhc_marca", catalog="adistemdb" )
public class VhcMarca implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @Lob
    @Column(name="IDMARCA", nullable=false)
    private byte[]     idmarca ;

    //--- OTHER DATA FIELDS 
    @Column(name="NOMBRE", nullable=false, length=255)
    private String     nombre ;

    @Column(name="ORDEN", nullable=false)
    private int        orden ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="vhcmarca")
    private List<VhcMarcaarchivo> vhcmarcaarchivoList ; 

    @OneToMany(mappedBy="vhcmarca")
    private List<VhcMarcaperiodo> vhcmarcaperiodoList ; 

    @OneToMany(mappedBy="vhcmarca")
    private List<VhcMarcaplantilla> vhcmarcaplantillaList ; 

    @OneToMany(mappedBy="vhcmarca")
    private List<VhcModelo> vhcmodeloList ;

    @OneToMany(mappedBy="vhcmarca")
    private List<VhcModelo> vhcmodeloperiodoindustriaList ;

    /**
     * Constructor
     */
    public VhcMarca() {
		super();
    }
    
    public void setIdmarca( byte[] idmarca ) {
        this.idmarca = idmarca ;
    }
    public byte[] getIdmarca() {
        return this.idmarca;
    }

    public void setNombre( String nombre ) {
        this.nombre = nombre ;
    }
    public String getNombre() {
        return this.nombre;
    }

    public void setOrden( int orden ) {
        this.orden = orden ;
    }
    public int getOrden() {
        return this.orden;
    }

    public List<VhcMarcaarchivo> getVhcmarcaarchivoList() {
        return this.vhcmarcaarchivoList;
    } 

    public List<VhcMarcaperiodo> getVhcmarcaperiodoList() {
        return this.vhcmarcaperiodoList;
    } 

    public List<VhcMarcaplantilla> getVhcmarcaplantillaList() {
        return this.vhcmarcaplantillaList;
    } 

    public List<VhcModelo> getVhcmodeloList() {
        return this.vhcmodeloList;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("VhcMarca[");
		// attribute 'idmarca' (type byte[]) not usable in toString() 
		sb.append("nombre=").append(nombre);
		sb.append(separator).append("orden=").append(orden);
		sb.append("]");
		return sb.toString();
	}

}
