/*
 * Created on 2025-11-07 ( 16:16:34 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

/**
 * JPA entity class for "VhcModeloperiodo"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="vhc_modeloperiodo", catalog="adistemdb" )
@Getter
@Setter
public class VhcModeloperiodo implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @Lob
    @Column(name="IDMODELOPERIODO", nullable=false)
    private byte[]     idmodeloperiodo ;

    //--- OTHER DATA FIELDS 
    @Lob
    @Column(name="IDMODELO")
    private byte[]     idmodelo ;

    @Column(name="PERIODOANIO", nullable=false)
    private int        periodoanio ;

    @Column(name="PERIODOMES", nullable=false)
    private int        periodomes ;

    @Column(name="MENUDEOFLOTILLANORMAL", nullable=false)
    private int        menudeoflotillanormal ;

    @Column(name="FLOTILLAESPECIAL", nullable=false)
    private int        flotillaespecial ;

    @Column(name="INVENTARIOCAMBIO", nullable=false)
    private int        inventariocambio ;

    @Column(name="INVENTARIONIVEL", nullable=false)
    private int        inventarionivel ;

    @Column(name="INVENTARIO", nullable=false)
    private int        inventario ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="IDMODELO", referencedColumnName="IDMODELO", insertable=false, updatable=false)
    private VhcModelo  vhcmodelo ; 

    /**
     * Constructor
     */
    public VhcModeloperiodo() {
		super();
    }


	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("VhcModeloperiodo[");
		// attribute 'idmodeloperiodo' (type byte[]) not usable in toString() 
		// attribute 'idmodelo' (type byte[]) not usable in toString() 
		sb.append("periodoanio=").append(periodoanio);
		sb.append(separator).append("periodomes=").append(periodomes);
		sb.append(separator).append("menudeoflotillanormal=").append(menudeoflotillanormal);
		sb.append(separator).append("flotillaespecial=").append(flotillaespecial);
		sb.append(separator).append("inventariocambio=").append(inventariocambio);
		sb.append(separator).append("inventarionivel=").append(inventarionivel);
		sb.append("]");
		return sb.toString();
	}

}
