/*
 * Created on 2025-11-07 ( 16:16:34 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.entities;

import java.io.Serializable;
import java.util.List;
import jakarta.persistence.*;

/**
 * JPA entity class for "VhcMarcaplantillatipo"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="vhc_marcaplantillatipo", catalog="adistemdb" )
public class VhcMarcaplantillatipo implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @Lob
    @Column(name="IDMARCAPLANTILLATIPO", nullable=false)
    private byte[]     idmarcaplantillatipo ;

    //--- OTHER DATA FIELDS 
    @Column(name="NOMBRE", nullable=false, length=255)
    private String     nombre ;

    @Column(name="DESCRIPCION", length=2000)
    private String     descripcion ;

    @Column(name="CLAVE", nullable=false, length=255)
    private String     clave ;

    @Column(name="ORDEN", nullable=false)
    private int        orden ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="vhcmarcaplantillatipo")
    private List<VhcMarcaplantillatipobase> vhcmarcaplantillatipobaseList ; 

    /**
     * Constructor
     */
    public VhcMarcaplantillatipo() {
		super();
    }
    
    public void setIdmarcaplantillatipo( byte[] idmarcaplantillatipo ) {
        this.idmarcaplantillatipo = idmarcaplantillatipo ;
    }
    public byte[] getIdmarcaplantillatipo() {
        return this.idmarcaplantillatipo;
    }

    public void setNombre( String nombre ) {
        this.nombre = nombre ;
    }
    public String getNombre() {
        return this.nombre;
    }

    public void setDescripcion( String descripcion ) {
        this.descripcion = descripcion ;
    }
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setClave( String clave ) {
        this.clave = clave ;
    }
    public String getClave() {
        return this.clave;
    }

    public void setOrden( int orden ) {
        this.orden = orden ;
    }
    public int getOrden() {
        return this.orden;
    }

    public List<VhcMarcaplantillatipobase> getVhcmarcaplantillatipobaseList() {
        return this.vhcmarcaplantillatipobaseList;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("VhcMarcaplantillatipo[");
		// attribute 'idmarcaplantillatipo' (type byte[]) not usable in toString() 
		sb.append("nombre=").append(nombre);
		sb.append(separator).append("descripcion=").append(descripcion);
		sb.append(separator).append("clave=").append(clave);
		sb.append(separator).append("orden=").append(orden);
		sb.append("]");
		return sb.toString();
	}

}
