/*
 * Created on 2025-11-07 ( 16:16:34 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.entities;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.proxy.HibernateProxy;

import java.io.Serializable;
import java.util.Objects;

/**
 * JPA entity class for "VhcMarcaarchivo"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@ToString
@RequiredArgsConstructor
@Entity
@Table(name="vhc_marcaarchivo", catalog="adistemdb" )
public class VhcMarcaarchivo implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @Lob
    @Column(name="IDMARCAARCHIVO", nullable=false)
    private byte[]     idmarcaarchivo ;

    //--- OTHER DATA FIELDS 
    @Column(name="ARCHIVO", length=255)
    private String     archivo ;


    //--- LINKS ( RELATIONSHIPS )
    //@JsonIgnore
    @ManyToOne
    @JoinColumn(name="IDMARCA", referencedColumnName="IDMARCA", insertable=false, updatable=false)
    private VhcMarca   vhcmarca ;

    @Override
    public final boolean equals(Object o) {
        if (this == o) return true;
        if (o == null) return false;
        Class<?> oEffectiveClass = o instanceof HibernateProxy ? ((HibernateProxy) o).getHibernateLazyInitializer().getPersistentClass() : o.getClass();
        Class<?> thisEffectiveClass = this instanceof HibernateProxy ? ((HibernateProxy) this).getHibernateLazyInitializer().getPersistentClass() : this.getClass();
        if (thisEffectiveClass != oEffectiveClass) return false;
        VhcMarcaarchivo that = (VhcMarcaarchivo) o;
        return getIdmarcaarchivo() != null && Objects.equals(getIdmarcaarchivo(), that.getIdmarcaarchivo());
    }

    @Override
    public final int hashCode() {
        return this instanceof HibernateProxy ? ((HibernateProxy) this).getHibernateLazyInitializer().getPersistentClass().hashCode() : getClass().hashCode();
    }
}
