/*
 * Created on 2025-11-07 ( 16:16:34 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;

/**
 * JPA entity class for "VhcModeloperiodoindustria"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="vhc_modeloperiodoindustria", catalog="adistemdb" )
public class VhcModeloperiodoindustria implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @Lob
    @Column(name="IDMODELOPERIODOINDUSTRIA", nullable=false)
    private byte[]     idmodeloperiodoindustria ;

    //--- OTHER DATA FIELDS 
    @Lob
    @Column(name="IDMODELO")
    private byte[]     idmodelo ;

    @Column(name="PERIODOANIO", nullable=false)
    private int        periodoanio ;

    @Column(name="PERIODOMES", nullable=false)
    private int        periodomes ;

    @Column(name="SEGMENTOARCHIVO", length=255)
    private String     segmentoarchivo ;

    @Column(name="MODELOARCHIVO", length=255)
    private String     modeloarchivo ;

    @Column(name="FABRICANTEARCHIVO", length=255)
    private String     fabricantearchivo ;

    @Column(name="ORIGENARCHIVO", length=255)
    private String     origenarchivo ;

    @Column(name="MARCAARCHIVO", length=255)
    private String     marcaarchivo ;

    @Column(name="CANTIDAD", nullable=false)
    private int        cantidad ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="IDMODELO", referencedColumnName="IDMODELO", insertable=false, updatable=false)
    private VhcModelo  vhcmodelo ; 

    /**
     * Constructor
     */
    public VhcModeloperiodoindustria() {
		super();
    }
    
    public void setIdmodeloperiodoindustria( byte[] idmodeloperiodoindustria ) {
        this.idmodeloperiodoindustria = idmodeloperiodoindustria ;
    }
    public byte[] getIdmodeloperiodoindustria() {
        return this.idmodeloperiodoindustria;
    }

    public void setIdmodelo( byte[] idmodelo ) {
        this.idmodelo = idmodelo ;
    }
    public byte[] getIdmodelo() {
        return this.idmodelo;
    }

    public void setPeriodoanio( int periodoanio ) {
        this.periodoanio = periodoanio ;
    }
    public int getPeriodoanio() {
        return this.periodoanio;
    }

    public void setPeriodomes( int periodomes ) {
        this.periodomes = periodomes ;
    }
    public int getPeriodomes() {
        return this.periodomes;
    }

    public void setSegmentoarchivo( String segmentoarchivo ) {
        this.segmentoarchivo = segmentoarchivo ;
    }
    public String getSegmentoarchivo() {
        return this.segmentoarchivo;
    }

    public void setModeloarchivo( String modeloarchivo ) {
        this.modeloarchivo = modeloarchivo ;
    }
    public String getModeloarchivo() {
        return this.modeloarchivo;
    }

    public void setFabricantearchivo( String fabricantearchivo ) {
        this.fabricantearchivo = fabricantearchivo ;
    }
    public String getFabricantearchivo() {
        return this.fabricantearchivo;
    }

    public void setOrigenarchivo( String origenarchivo ) {
        this.origenarchivo = origenarchivo ;
    }
    public String getOrigenarchivo() {
        return this.origenarchivo;
    }

    public void setMarcaarchivo( String marcaarchivo ) {
        this.marcaarchivo = marcaarchivo ;
    }
    public String getMarcaarchivo() {
        return this.marcaarchivo;
    }

    public void setCantidad( int cantidad ) {
        this.cantidad = cantidad ;
    }
    public int getCantidad() {
        return this.cantidad;
    }

    public VhcModelo getVhcmodelo() {
        return this.vhcmodelo;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("VhcModeloperiodoindustria[");
		// attribute 'idmodeloperiodoindustria' (type byte[]) not usable in toString() 
		// attribute 'idmodelo' (type byte[]) not usable in toString() 
		sb.append("periodoanio=").append(periodoanio);
		sb.append(separator).append("periodomes=").append(periodomes);
		sb.append(separator).append("segmentoarchivo=").append(segmentoarchivo);
		sb.append(separator).append("modeloarchivo=").append(modeloarchivo);
		sb.append(separator).append("fabricantearchivo=").append(fabricantearchivo);
		sb.append(separator).append("origenarchivo=").append(origenarchivo);
		sb.append(separator).append("marcaarchivo=").append(marcaarchivo);
		sb.append(separator).append("cantidad=").append(cantidad);
		sb.append("]");
		return sb.toString();
	}

}
