/*
 * Created on 2025-11-07 ( 16:16:34 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;

/**
 * JPA entity class for "VhcOrigen"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="vhc_origen", catalog="adistemdb" )
public class VhcOrigen implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @Lob
    @Column(name="IDORIGEN", nullable=false)
    private byte[]     idorigen ;

    //--- OTHER DATA FIELDS 
    @Column(name="NOMBRE", nullable=false, length=255)
    private String     nombre ;

    @Column(name="CLAVE", nullable=false, length=255)
    private String     clave ;

    @Column(name="ORDEN", nullable=false)
    private int        orden ;

    /**
     * Constructor
     */
    public VhcOrigen() {
		super();
    }
    
    public void setIdorigen( byte[] idorigen ) {
        this.idorigen = idorigen ;
    }
    public byte[] getIdorigen() {
        return this.idorigen;
    }

    public void setNombre( String nombre ) {
        this.nombre = nombre ;
    }
    public String getNombre() {
        return this.nombre;
    }

    public void setClave( String clave ) {
        this.clave = clave ;
    }
    public String getClave() {
        return this.clave;
    }

    public void setOrden( int orden ) {
        this.orden = orden ;
    }
    public int getOrden() {
        return this.orden;
    }

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("VhcOrigen[");
		// attribute 'idorigen' (type byte[]) not usable in toString() 
		sb.append("nombre=").append(nombre);
		sb.append(separator).append("clave=").append(clave);
		sb.append(separator).append("orden=").append(orden);
		sb.append("]");
		return sb.toString();
	}

}
