/*
 * Created on 2025-11-07 ( 16:16:34 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.entities;

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.LocalDateTime;
import java.util.Objects;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

/**
 * JPA entity class for "VhcPeriodo"
 *
 * @author Telosys
 *
 */
@Entity
@Getter
@Setter
@Table(name="vhc_periodo", catalog="adistemdb" )
public class VhcPeriodo implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @Lob
    @Column(name="IDPERIODO", nullable=false)
    private byte[]     idperiodo ;

    //--- OTHER DATA FIELDS 
    @Lob
    @Column(name="IDANIO")
    private byte[]     idanio ;

    @Column(name="PERIODOANIO", nullable=false)
    private int        periodoanio ;

    @Column(name="PERIODOMES", nullable=false)
    private int        periodomes ;

    @Column(name="FECHAINICIO")
    private LocalDateTime fechainicio ;

    @Column(name="FECHAFIN")
    private LocalDateTime fechafin ;

    @Column(name="SALE", nullable=false)
    private int        sale ;

    @Column(name="DEALERSTOCK", nullable=false)
    private int        dealerstock ;

    @Column(name="INTRANSIT", nullable=false)
    private int        intransit ;

    @Column(name="INCOUNTRYSTOCK", nullable=false)
    private int        incountrystock ;

    @Column(name="PRECIOLISTA", nullable=false)
    private BigDecimal preciolista ;

    @Column(name="CONTADODESCUENTO", nullable=false)
    private BigDecimal contadodescuento ;

    @Column(name="CONTADOPARTICIPACIONDISTRIBUIDORES", nullable=false)
    private BigDecimal contadoparticipaciondistribuidores ;

    @Column(name="CONTADOTOTALDESCUENTOS", nullable=false)
    private BigDecimal contadototaldescuentos ;

    @Column(name="CONTADOPRECIO", nullable=false)
    private BigDecimal contadoprecio ;

    @Column(name="CONTADOSEGUROGRATIS", length=255)
    private String     contadosegurogratis ;

    @Column(name="FINANCIAMIENTODESCUENTOPROMOCIONAL", nullable=false)
    private BigDecimal financiamientodescuentopromocional ;

    @Column(name="FINANCIAMIENTOPARTICIPACIONDISTRIBUIDORES", nullable=false)
    private BigDecimal financiamientoparticipaciondistribuidores ;

    @Column(name="FINANCIAMIENTOTOTALDESCUENTOS", nullable=false)
    private BigDecimal financiamientototaldescuentos ;

    @Column(name="FINANCIAMIENTOPRECIOPROMOCIONAL", nullable=false)
    private BigDecimal financiamientopreciopromocional ;

    @Column(name="FINANCIAMIENTOTASADESDE", length=255)
    private String     financiamientotasadesde ;

    @Column(name="FINANCIAMIENTOSEGUROGRATIS", length=255)
    private String     financiamientosegurogratis ;

    @Column(name="FINANCIAMIENTOALTERNODESCUENTOPROMOCIONAL", nullable=false)
    private BigDecimal financiamientoalternodescuentopromocional ;

    @Column(name="FINANCIAMIENTOALTERNOPARTICIPACIONDISTRIBUIDORES", nullable=false)
    private BigDecimal financiamientoalternoparticipaciondistribuidores ;

    @Column(name="FINANCIAMIENTOALTERNOTOTALDESCUENTOS", nullable=false)
    private BigDecimal financiamientoalternototaldescuentos ;

    @Column(name="FINANCIAMIENTOALTERNOPRECIOPROMOCIONAL", nullable=false)
    private BigDecimal financiamientoalternopreciopromocional ;

    @Column(name="FINANCIAMIENTOALTERNOTASADESDE", length=255)
    private String     financiamientoalternotasadesde ;

    @Column(name="FINANCIAMIENTOALTERNOSEGUROGRATIS", length=255)
    private String     financiamientoalternosegurogratis ;

    @Column(name="MESESSININTERESES", length=255)
    private String     mesessinintereses ;

    @Column(name="TOTALMES12", nullable=false)
    private BigDecimal totalmes12 ;

    @Column(name="PROMEDIOMES6", nullable=false)
    private BigDecimal promediomes6 ;

    @Column(name="MODELOARCHIVO", length=255)
    private String     modeloArchivo ;

    @Column(name="MARCAARCHIVO", length=255)
    private String     marcaArchivo ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="IDANIO", referencedColumnName="IDANIO", insertable=false, updatable=false)
    private VhcAnio    vhcanio ; 

    /**
     * Constructor
     */
    public VhcPeriodo() {
		super();
    }


	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("VhcPeriodo[");
		// attribute 'idperiodo' (type byte[]) not usable in toString() 
		// attribute 'idanio' (type byte[]) not usable in toString() 
		sb.append("totalmes12=").append(intransit);
		sb.append(separator).append("promediomes6=").append(incountrystock);
		sb.append(separator).append("sale=").append(sale);
		sb.append(separator).append("dealerstock=").append(dealerstock);
        sb.append(separator).append("marca=").append(marcaArchivo);
        sb.append(separator).append("modelo=").append(modeloArchivo);
		sb.append("]");
		return sb.toString();
	}

    public VhcPeriodo sumarCon(VhcPeriodo otro) {
        var acumulado = new VhcPeriodo();
        //Valores originales
        acumulado.setPeriodoanio(otro.getPeriodoanio());
        acumulado.setPeriodomes(otro.getPeriodomes());
        acumulado.setMarcaArchivo(otro.getMarcaArchivo());
        acumulado.setModeloArchivo(otro.getModeloArchivo());
        acumulado.setMesessinintereses(otro.getMesessinintereses());

        // Sumar valores int
        acumulado.setSale(this.sale + otro.getSale());
        acumulado.setDealerstock(this.dealerstock + otro.getDealerstock());
        acumulado.setIntransit(this.intransit + otro.getIntransit());
        acumulado.setIncountrystock(this.incountrystock + otro.getIncountrystock());

        // Sumar BigDecimal

        var tot12 = Objects.isNull(this.totalmes12) ? new BigDecimal(0) :  this.totalmes12;
        acumulado.setTotalmes12(tot12.add(otro.getTotalmes12()).divide(new BigDecimal(2)));
        //acumulado.setPreciolista(this.getPreciolista().add(otro.getPreciolista()));
        //acumulado.setContadodescuento(this.getContadodescuento().add(otro.getContadodescuento()));
        //acumulado.setContadoparticipaciondistribuidores(
        //        this.getContadoparticipaciondistribuidores().add(otro.getContadoparticipaciondistribuidores())
        //);
        //acumulado.setContadototaldescuentos(
        //        this.getContadototaldescuentos().add(otro.getContadototaldescuentos())
        //);
        //acumulado.setContadoprecio(this.getContadoprecio().add(otro.getContadoprecio()));

        // Sumar otros BigDecimal financieros
        //acumulado.setFinanciamientodescuentopromocional(
        //        this.getFinanciamientodescuentopromocional().add(otro.getFinanciamientodescuentopromocional())
        //);


        return acumulado;
    }

}
