/*
 * Created on 2025-11-07 ( 16:16:34 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.entities;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import jakarta.persistence.*;

/**
 * JPA entity class for "VhcPeriodo"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="vhc_periodo", catalog="adistemdb" )
public class VhcPeriodo implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @Lob
    @Column(name="IDPERIODO", nullable=false)
    private byte[]     idperiodo ;

    //--- OTHER DATA FIELDS 
    @Lob
    @Column(name="IDANIO")
    private byte[]     idanio ;

    @Column(name="PERIODOANIO", nullable=false)
    private int        periodoanio ;

    @Column(name="PERIODOMES", nullable=false)
    private int        periodomes ;

    @Column(name="FECHAINICIO")
    private LocalDateTime fechainicio ;

    @Column(name="FECHAFIN")
    private LocalDateTime fechafin ;

    @Column(name="SALE", nullable=false)
    private int        sale ;

    @Column(name="DEALERSTOCK", nullable=false)
    private int        dealerstock ;

    @Column(name="INTRANSIT", nullable=false)
    private int        intransit ;

    @Column(name="INCOUNTRYSTOCK", nullable=false)
    private int        incountrystock ;

    @Column(name="PRECIOLISTA", nullable=false)
    private BigDecimal preciolista ;

    @Column(name="CONTADODESCUENTO", nullable=false)
    private BigDecimal contadodescuento ;

    @Column(name="CONTADOPARTICIPACIONDISTRIBUIDORES", nullable=false)
    private BigDecimal contadoparticipaciondistribuidores ;

    @Column(name="CONTADOTOTALDESCUENTOS", nullable=false)
    private BigDecimal contadototaldescuentos ;

    @Column(name="CONTADOPRECIO", nullable=false)
    private BigDecimal contadoprecio ;

    @Column(name="CONTADOSEGUROGRATIS", length=255)
    private String     contadosegurogratis ;

    @Column(name="FINANCIAMIENTODESCUENTOPROMOCIONAL", nullable=false)
    private BigDecimal financiamientodescuentopromocional ;

    @Column(name="FINANCIAMIENTOPARTICIPACIONDISTRIBUIDORES", nullable=false)
    private BigDecimal financiamientoparticipaciondistribuidores ;

    @Column(name="FINANCIAMIENTOTOTALDESCUENTOS", nullable=false)
    private BigDecimal financiamientototaldescuentos ;

    @Column(name="FINANCIAMIENTOPRECIOPROMOCIONAL", nullable=false)
    private BigDecimal financiamientopreciopromocional ;

    @Column(name="FINANCIAMIENTOTASADESDE", length=255)
    private String     financiamientotasadesde ;

    @Column(name="FINANCIAMIENTOSEGUROGRATIS", length=255)
    private String     financiamientosegurogratis ;

    @Column(name="FINANCIAMIENTOALTERNODESCUENTOPROMOCIONAL", nullable=false)
    private BigDecimal financiamientoalternodescuentopromocional ;

    @Column(name="FINANCIAMIENTOALTERNOPARTICIPACIONDISTRIBUIDORES", nullable=false)
    private BigDecimal financiamientoalternoparticipaciondistribuidores ;

    @Column(name="FINANCIAMIENTOALTERNOTOTALDESCUENTOS", nullable=false)
    private BigDecimal financiamientoalternototaldescuentos ;

    @Column(name="FINANCIAMIENTOALTERNOPRECIOPROMOCIONAL", nullable=false)
    private BigDecimal financiamientoalternopreciopromocional ;

    @Column(name="FINANCIAMIENTOALTERNOTASADESDE", length=255)
    private String     financiamientoalternotasadesde ;

    @Column(name="FINANCIAMIENTOALTERNOSEGUROGRATIS", length=255)
    private String     financiamientoalternosegurogratis ;

    @Column(name="MESESSININTERESES", length=255)
    private String     mesessinintereses ;

    @Column(name="TOTALMES12", nullable=false)
    private BigDecimal totalmes12 ;

    @Column(name="PROMEDIOMES6", nullable=false)
    private BigDecimal promediomes6 ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="IDANIO", referencedColumnName="IDANIO", insertable=false, updatable=false)
    private VhcAnio    vhcanio ; 

    /**
     * Constructor
     */
    public VhcPeriodo() {
		super();
    }
    
    public void setIdperiodo( byte[] idperiodo ) {
        this.idperiodo = idperiodo ;
    }
    public byte[] getIdperiodo() {
        return this.idperiodo;
    }

    public void setIdanio( byte[] idanio ) {
        this.idanio = idanio ;
    }
    public byte[] getIdanio() {
        return this.idanio;
    }

    public void setPeriodoanio( int periodoanio ) {
        this.periodoanio = periodoanio ;
    }
    public int getPeriodoanio() {
        return this.periodoanio;
    }

    public void setPeriodomes( int periodomes ) {
        this.periodomes = periodomes ;
    }
    public int getPeriodomes() {
        return this.periodomes;
    }

    public void setFechainicio( LocalDateTime fechainicio ) {
        this.fechainicio = fechainicio ;
    }
    public LocalDateTime getFechainicio() {
        return this.fechainicio;
    }

    public void setFechafin( LocalDateTime fechafin ) {
        this.fechafin = fechafin ;
    }
    public LocalDateTime getFechafin() {
        return this.fechafin;
    }

    public void setSale( int sale ) {
        this.sale = sale ;
    }
    public int getSale() {
        return this.sale;
    }

    public void setDealerstock( int dealerstock ) {
        this.dealerstock = dealerstock ;
    }
    public int getDealerstock() {
        return this.dealerstock;
    }

    public void setIntransit( int intransit ) {
        this.intransit = intransit ;
    }
    public int getIntransit() {
        return this.intransit;
    }

    public void setIncountrystock( int incountrystock ) {
        this.incountrystock = incountrystock ;
    }
    public int getIncountrystock() {
        return this.incountrystock;
    }

    public void setPreciolista( BigDecimal preciolista ) {
        this.preciolista = preciolista ;
    }
    public BigDecimal getPreciolista() {
        return this.preciolista;
    }

    public void setContadodescuento( BigDecimal contadodescuento ) {
        this.contadodescuento = contadodescuento ;
    }
    public BigDecimal getContadodescuento() {
        return this.contadodescuento;
    }

    public void setContadoparticipaciondistribuidores( BigDecimal contadoparticipaciondistribuidores ) {
        this.contadoparticipaciondistribuidores = contadoparticipaciondistribuidores ;
    }
    public BigDecimal getContadoparticipaciondistribuidores() {
        return this.contadoparticipaciondistribuidores;
    }

    public void setContadototaldescuentos( BigDecimal contadototaldescuentos ) {
        this.contadototaldescuentos = contadototaldescuentos ;
    }
    public BigDecimal getContadototaldescuentos() {
        return this.contadototaldescuentos;
    }

    public void setContadoprecio( BigDecimal contadoprecio ) {
        this.contadoprecio = contadoprecio ;
    }
    public BigDecimal getContadoprecio() {
        return this.contadoprecio;
    }

    public void setContadosegurogratis( String contadosegurogratis ) {
        this.contadosegurogratis = contadosegurogratis ;
    }
    public String getContadosegurogratis() {
        return this.contadosegurogratis;
    }

    public void setFinanciamientodescuentopromocional( BigDecimal financiamientodescuentopromocional ) {
        this.financiamientodescuentopromocional = financiamientodescuentopromocional ;
    }
    public BigDecimal getFinanciamientodescuentopromocional() {
        return this.financiamientodescuentopromocional;
    }

    public void setFinanciamientoparticipaciondistribuidores( BigDecimal financiamientoparticipaciondistribuidores ) {
        this.financiamientoparticipaciondistribuidores = financiamientoparticipaciondistribuidores ;
    }
    public BigDecimal getFinanciamientoparticipaciondistribuidores() {
        return this.financiamientoparticipaciondistribuidores;
    }

    public void setFinanciamientototaldescuentos( BigDecimal financiamientototaldescuentos ) {
        this.financiamientototaldescuentos = financiamientototaldescuentos ;
    }
    public BigDecimal getFinanciamientototaldescuentos() {
        return this.financiamientototaldescuentos;
    }

    public void setFinanciamientopreciopromocional( BigDecimal financiamientopreciopromocional ) {
        this.financiamientopreciopromocional = financiamientopreciopromocional ;
    }
    public BigDecimal getFinanciamientopreciopromocional() {
        return this.financiamientopreciopromocional;
    }

    public void setFinanciamientotasadesde( String financiamientotasadesde ) {
        this.financiamientotasadesde = financiamientotasadesde ;
    }
    public String getFinanciamientotasadesde() {
        return this.financiamientotasadesde;
    }

    public void setFinanciamientosegurogratis( String financiamientosegurogratis ) {
        this.financiamientosegurogratis = financiamientosegurogratis ;
    }
    public String getFinanciamientosegurogratis() {
        return this.financiamientosegurogratis;
    }

    public void setFinanciamientoalternodescuentopromocional( BigDecimal financiamientoalternodescuentopromocional ) {
        this.financiamientoalternodescuentopromocional = financiamientoalternodescuentopromocional ;
    }
    public BigDecimal getFinanciamientoalternodescuentopromocional() {
        return this.financiamientoalternodescuentopromocional;
    }

    public void setFinanciamientoalternoparticipaciondistribuidores( BigDecimal financiamientoalternoparticipaciondistribuidores ) {
        this.financiamientoalternoparticipaciondistribuidores = financiamientoalternoparticipaciondistribuidores ;
    }
    public BigDecimal getFinanciamientoalternoparticipaciondistribuidores() {
        return this.financiamientoalternoparticipaciondistribuidores;
    }

    public void setFinanciamientoalternototaldescuentos( BigDecimal financiamientoalternototaldescuentos ) {
        this.financiamientoalternototaldescuentos = financiamientoalternototaldescuentos ;
    }
    public BigDecimal getFinanciamientoalternototaldescuentos() {
        return this.financiamientoalternototaldescuentos;
    }

    public void setFinanciamientoalternopreciopromocional( BigDecimal financiamientoalternopreciopromocional ) {
        this.financiamientoalternopreciopromocional = financiamientoalternopreciopromocional ;
    }
    public BigDecimal getFinanciamientoalternopreciopromocional() {
        return this.financiamientoalternopreciopromocional;
    }

    public void setFinanciamientoalternotasadesde( String financiamientoalternotasadesde ) {
        this.financiamientoalternotasadesde = financiamientoalternotasadesde ;
    }
    public String getFinanciamientoalternotasadesde() {
        return this.financiamientoalternotasadesde;
    }

    public void setFinanciamientoalternosegurogratis( String financiamientoalternosegurogratis ) {
        this.financiamientoalternosegurogratis = financiamientoalternosegurogratis ;
    }
    public String getFinanciamientoalternosegurogratis() {
        return this.financiamientoalternosegurogratis;
    }

    public void setMesessinintereses( String mesessinintereses ) {
        this.mesessinintereses = mesessinintereses ;
    }
    public String getMesessinintereses() {
        return this.mesessinintereses;
    }

    public void setTotalmes12( BigDecimal totalmes12 ) {
        this.totalmes12 = totalmes12 ;
    }
    public BigDecimal getTotalmes12() {
        return this.totalmes12;
    }

    public void setPromediomes6( BigDecimal promediomes6 ) {
        this.promediomes6 = promediomes6 ;
    }
    public BigDecimal getPromediomes6() {
        return this.promediomes6;
    }

    public VhcAnio getVhcanio() {
        return this.vhcanio;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("VhcPeriodo[");
		// attribute 'idperiodo' (type byte[]) not usable in toString() 
		// attribute 'idanio' (type byte[]) not usable in toString() 
		sb.append("periodoanio=").append(periodoanio);
		sb.append(separator).append("periodomes=").append(periodomes);
		sb.append(separator).append("fechainicio=").append(fechainicio);
		sb.append(separator).append("fechafin=").append(fechafin);
		sb.append(separator).append("sale=").append(sale);
		sb.append(separator).append("dealerstock=").append(dealerstock);
		sb.append(separator).append("intransit=").append(intransit);
		sb.append(separator).append("incountrystock=").append(incountrystock);
		sb.append(separator).append("preciolista=").append(preciolista);
		sb.append(separator).append("contadodescuento=").append(contadodescuento);
		sb.append(separator).append("contadoparticipaciondistribuidores=").append(contadoparticipaciondistribuidores);
		sb.append(separator).append("contadototaldescuentos=").append(contadototaldescuentos);
		sb.append(separator).append("contadoprecio=").append(contadoprecio);
		sb.append(separator).append("contadosegurogratis=").append(contadosegurogratis);
		sb.append(separator).append("financiamientodescuentopromocional=").append(financiamientodescuentopromocional);
		sb.append(separator).append("financiamientoparticipaciondistribuidores=").append(financiamientoparticipaciondistribuidores);
		sb.append(separator).append("financiamientototaldescuentos=").append(financiamientototaldescuentos);
		sb.append(separator).append("financiamientopreciopromocional=").append(financiamientopreciopromocional);
		sb.append(separator).append("financiamientotasadesde=").append(financiamientotasadesde);
		sb.append(separator).append("financiamientosegurogratis=").append(financiamientosegurogratis);
		sb.append(separator).append("financiamientoalternodescuentopromocional=").append(financiamientoalternodescuentopromocional);
		sb.append(separator).append("financiamientoalternoparticipaciondistribuidores=").append(financiamientoalternoparticipaciondistribuidores);
		sb.append(separator).append("financiamientoalternototaldescuentos=").append(financiamientoalternototaldescuentos);
		sb.append(separator).append("financiamientoalternopreciopromocional=").append(financiamientoalternopreciopromocional);
		sb.append(separator).append("financiamientoalternotasadesde=").append(financiamientoalternotasadesde);
		sb.append(separator).append("financiamientoalternosegurogratis=").append(financiamientoalternosegurogratis);
		sb.append(separator).append("mesessinintereses=").append(mesessinintereses);
		sb.append(separator).append("totalmes12=").append(totalmes12);
		sb.append(separator).append("promediomes6=").append(promediomes6);
		sb.append("]");
		return sb.toString();
	}

}
