/*
 * Created on 2025-11-07 ( 16:16:34 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.entities;

import java.io.Serializable;
import java.util.List;
import jakarta.persistence.*;

/**
 * JPA entity class for "VhcReddistribucionplantillatipo"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="vhc_reddistribucionplantillatipo", catalog="adistemdb" )
public class VhcReddistribucionplantillatipo implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @Lob
    @Column(name="IDREDDISTRIBUCIONPLANTILLATIPO", nullable=false)
    private byte[]     idreddistribucionplantillatipo ;

    //--- OTHER DATA FIELDS 
    @Column(name="NOMBRE", nullable=false, length=255)
    private String     nombre ;

    @Column(name="DESCRIPCION", length=2000)
    private String     descripcion ;

    @Column(name="CLAVE", nullable=false, length=255)
    private String     clave ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="vhcreddistribucionplantillatipo")
    private List<VhcReddistribucionplantillatipobase> vhcreddistribucionplantillatipobaseList ; 

    /**
     * Constructor
     */
    public VhcReddistribucionplantillatipo() {
		super();
    }
    
    public void setIdreddistribucionplantillatipo( byte[] idreddistribucionplantillatipo ) {
        this.idreddistribucionplantillatipo = idreddistribucionplantillatipo ;
    }
    public byte[] getIdreddistribucionplantillatipo() {
        return this.idreddistribucionplantillatipo;
    }

    public void setNombre( String nombre ) {
        this.nombre = nombre ;
    }
    public String getNombre() {
        return this.nombre;
    }

    public void setDescripcion( String descripcion ) {
        this.descripcion = descripcion ;
    }
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setClave( String clave ) {
        this.clave = clave ;
    }
    public String getClave() {
        return this.clave;
    }

    public List<VhcReddistribucionplantillatipobase> getVhcreddistribucionplantillatipobaseList() {
        return this.vhcreddistribucionplantillatipobaseList;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("VhcReddistribucionplantillatipo[");
		// attribute 'idreddistribucionplantillatipo' (type byte[]) not usable in toString() 
		sb.append("nombre=").append(nombre);
		sb.append(separator).append("descripcion=").append(descripcion);
		sb.append(separator).append("clave=").append(clave);
		sb.append("]");
		return sb.toString();
	}

}
