/*
 * Created on 2025-11-07 ( 16:16:34 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;

/**
 * JPA entity class for "VhcReddistribucionplantillatipobase"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="vhc_reddistribucionplantillatipobase", catalog="adistemdb" )
public class VhcReddistribucionplantillatipobase implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @Lob
    @Column(name="IDREDDISTRIBUCIONPLANTILLATIPOBASE", nullable=false)
    private byte[]     idreddistribucionplantillatipobase ;

    //--- OTHER DATA FIELDS 
    @Column(name="DESCRIPCION", length=2000)
    private String     descripcion ;

    @Column(name="ORDEN", nullable=false)
    private int        orden ;

    @Column(name="ARCHIVO", length=255)
    private String     archivo ;

    @Lob
    @Column(name="IDREDDISTRIBUCIONPLANTILLATIPO")
    private byte[]     idreddistribucionplantillatipo ;

    @Column(name="FECHAINICIO", length=255)
    private String     fechainicio ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="IDREDDISTRIBUCIONPLANTILLATIPO", referencedColumnName="IDREDDISTRIBUCIONPLANTILLATIPO", insertable=false, updatable=false)
    private VhcReddistribucionplantillatipo vhcreddistribucionplantillatipo ; 

    /**
     * Constructor
     */
    public VhcReddistribucionplantillatipobase() {
		super();
    }
    
    public void setIdreddistribucionplantillatipobase( byte[] idreddistribucionplantillatipobase ) {
        this.idreddistribucionplantillatipobase = idreddistribucionplantillatipobase ;
    }
    public byte[] getIdreddistribucionplantillatipobase() {
        return this.idreddistribucionplantillatipobase;
    }

    public void setDescripcion( String descripcion ) {
        this.descripcion = descripcion ;
    }
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setOrden( int orden ) {
        this.orden = orden ;
    }
    public int getOrden() {
        return this.orden;
    }

    public void setArchivo( String archivo ) {
        this.archivo = archivo ;
    }
    public String getArchivo() {
        return this.archivo;
    }

    public void setIdreddistribucionplantillatipo( byte[] idreddistribucionplantillatipo ) {
        this.idreddistribucionplantillatipo = idreddistribucionplantillatipo ;
    }
    public byte[] getIdreddistribucionplantillatipo() {
        return this.idreddistribucionplantillatipo;
    }

    public void setFechainicio( String fechainicio ) {
        this.fechainicio = fechainicio ;
    }
    public String getFechainicio() {
        return this.fechainicio;
    }

    public VhcReddistribucionplantillatipo getVhcreddistribucionplantillatipo() {
        return this.vhcreddistribucionplantillatipo;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("VhcReddistribucionplantillatipobase[");
		// attribute 'idreddistribucionplantillatipobase' (type byte[]) not usable in toString() 
		sb.append("descripcion=").append(descripcion);
		sb.append(separator).append("orden=").append(orden);
		sb.append(separator).append("archivo=").append(archivo);
		// attribute 'idreddistribucionplantillatipo' (type byte[]) not usable in toString() 
		sb.append(separator).append("fechainicio=").append(fechainicio);
		sb.append("]");
		return sb.toString();
	}

}
