/*
 * Created on 2025-11-07 ( 16:16:34 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;

/**
 * JPA entity class for "VhcReddistribucionmodelo"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="vhc_reddistribucionmodelo", catalog="adistemdb" )
public class VhcReddistribucionmodelo implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @Lob
    @Column(name="IDREDDISTRIBUCIONMODELO", nullable=false)
    private byte[]     idreddistribucionmodelo ;

    //--- OTHER DATA FIELDS 
    @Lob
    @Column(name="IDREDDISTRIBUCION")
    private byte[]     idreddistribucion ;

    @Lob
    @Column(name="IDMODELO")
    private byte[]     idmodelo ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="IDREDDISTRIBUCION", referencedColumnName="IDREDDISTRIBUCION", insertable=false, updatable=false)
    private VhcReddistribucion vhcreddistribucion ; 

    /**
     * Constructor
     */
    public VhcReddistribucionmodelo() {
		super();
    }
    
    public void setIdreddistribucionmodelo( byte[] idreddistribucionmodelo ) {
        this.idreddistribucionmodelo = idreddistribucionmodelo ;
    }
    public byte[] getIdreddistribucionmodelo() {
        return this.idreddistribucionmodelo;
    }

    public void setIdreddistribucion( byte[] idreddistribucion ) {
        this.idreddistribucion = idreddistribucion ;
    }
    public byte[] getIdreddistribucion() {
        return this.idreddistribucion;
    }

    public void setIdmodelo( byte[] idmodelo ) {
        this.idmodelo = idmodelo ;
    }
    public byte[] getIdmodelo() {
        return this.idmodelo;
    }

    public VhcReddistribucion getVhcreddistribucion() {
        return this.vhcreddistribucion;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("VhcReddistribucionmodelo[");
		// attribute 'idreddistribucionmodelo' (type byte[]) not usable in toString() 
		// attribute 'idreddistribucion' (type byte[]) not usable in toString() 
		// attribute 'idmodelo' (type byte[]) not usable in toString() 
		sb.append("]");
		return sb.toString();
	}

}
