/*
 * Created on 2025-11-07 ( 16:16:34 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;

/**
 * JPA entity class for "VhcReddistribucionarchivotipo"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="vhc_reddistribucionarchivotipo", catalog="adistemdb" )
public class VhcReddistribucionarchivotipo implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @Lob
    @Column(name="IDREDDISTRIBUCIONARCHIVOTIPO", nullable=false)
    private byte[]     idreddistribucionarchivotipo ;

    //--- OTHER DATA FIELDS 
    @Column(name="NOMBRE", nullable=false, length=255)
    private String     nombre ;

    @Column(name="DESCRIPCION", length=2000)
    private String     descripcion ;

    @Column(name="CLAVE", nullable=false, length=255)
    private String     clave ;

    @Column(name="ORDEN", nullable=false)
    private int        orden ;

    /**
     * Constructor
     */
    public VhcReddistribucionarchivotipo() {
		super();
    }
    
    public void setIdreddistribucionarchivotipo( byte[] idreddistribucionarchivotipo ) {
        this.idreddistribucionarchivotipo = idreddistribucionarchivotipo ;
    }
    public byte[] getIdreddistribucionarchivotipo() {
        return this.idreddistribucionarchivotipo;
    }

    public void setNombre( String nombre ) {
        this.nombre = nombre ;
    }
    public String getNombre() {
        return this.nombre;
    }

    public void setDescripcion( String descripcion ) {
        this.descripcion = descripcion ;
    }
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setClave( String clave ) {
        this.clave = clave ;
    }
    public String getClave() {
        return this.clave;
    }

    public void setOrden( int orden ) {
        this.orden = orden ;
    }
    public int getOrden() {
        return this.orden;
    }

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("VhcReddistribucionarchivotipo[");
		// attribute 'idreddistribucionarchivotipo' (type byte[]) not usable in toString() 
		sb.append("nombre=").append(nombre);
		sb.append(separator).append("descripcion=").append(descripcion);
		sb.append(separator).append("clave=").append(clave);
		sb.append(separator).append("orden=").append(orden);
		sb.append("]");
		return sb.toString();
	}

}
