/*
 * Created on 2025-11-07 ( 16:16:34 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.entities;

import java.io.Serializable;
import java.util.List;
import jakarta.persistence.*;

/**
 * JPA entity class for "VhcReddistribucion"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="vhc_reddistribucion", catalog="adistemdb" )
public class VhcReddistribucion implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @Lob
    @Column(name="IDREDDISTRIBUCION", nullable=false)
    private byte[]     idreddistribucion ;

    //--- OTHER DATA FIELDS 
    @Column(name="NOMBRE", nullable=false, length=255)
    private String     nombre ;

    @Column(name="CLAVE", nullable=false, length=255)
    private String     clave ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="vhcreddistribucion")
    private List<VhcReddistribucionarchivo> vhcreddistribucionarchivoList ; 

    @OneToMany(mappedBy="vhcreddistribucion")
    private List<VhcReddistribucionmodelo> vhcreddistribucionmodeloList ; 

    @OneToMany(mappedBy="vhcreddistribucion")
    private List<VhcReddistribucionplantilla> vhcreddistribucionplantillaList ; 

    @OneToMany(mappedBy="vhcreddistribucion")
    private List<VhcReddistribucionversion> vhcreddistribucionversionList ; 

    /**
     * Constructor
     */
    public VhcReddistribucion() {
		super();
    }
    
    public void setIdreddistribucion( byte[] idreddistribucion ) {
        this.idreddistribucion = idreddistribucion ;
    }
    public byte[] getIdreddistribucion() {
        return this.idreddistribucion;
    }

    public void setNombre( String nombre ) {
        this.nombre = nombre ;
    }
    public String getNombre() {
        return this.nombre;
    }

    public void setClave( String clave ) {
        this.clave = clave ;
    }
    public String getClave() {
        return this.clave;
    }

    public List<VhcReddistribucionarchivo> getVhcreddistribucionarchivoList() {
        return this.vhcreddistribucionarchivoList;
    } 

    public List<VhcReddistribucionmodelo> getVhcreddistribucionmodeloList() {
        return this.vhcreddistribucionmodeloList;
    } 

    public List<VhcReddistribucionplantilla> getVhcreddistribucionplantillaList() {
        return this.vhcreddistribucionplantillaList;
    } 

    public List<VhcReddistribucionversion> getVhcreddistribucionversionList() {
        return this.vhcreddistribucionversionList;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("VhcReddistribucion[");
		// attribute 'idreddistribucion' (type byte[]) not usable in toString() 
		sb.append("nombre=").append(nombre);
		sb.append(separator).append("clave=").append(clave);
		sb.append("]");
		return sb.toString();
	}

}
