/*
 * Created on 2025-11-07 ( 16:16:34 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;

/**
 * JPA entity class for "VhcReddistribucionversion"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="vhc_reddistribucionversion", catalog="adistemdb" )
public class VhcReddistribucionversion implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @Lob
    @Column(name="IDREDDISTRIBUCIONVERSION", nullable=false)
    private byte[]     idreddistribucionversion ;

    //--- OTHER DATA FIELDS 
    @Lob
    @Column(name="IDREDDISTRIBUCION")
    private byte[]     idreddistribucion ;

    @Lob
    @Column(name="IDVERSION")
    private byte[]     idversion ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="IDREDDISTRIBUCION", referencedColumnName="IDREDDISTRIBUCION", insertable=false, updatable=false)
    private VhcReddistribucion vhcreddistribucion ; 

    /**
     * Constructor
     */
    public VhcReddistribucionversion() {
		super();
    }
    
    public void setIdreddistribucionversion( byte[] idreddistribucionversion ) {
        this.idreddistribucionversion = idreddistribucionversion ;
    }
    public byte[] getIdreddistribucionversion() {
        return this.idreddistribucionversion;
    }

    public void setIdreddistribucion( byte[] idreddistribucion ) {
        this.idreddistribucion = idreddistribucion ;
    }
    public byte[] getIdreddistribucion() {
        return this.idreddistribucion;
    }

    public void setIdversion( byte[] idversion ) {
        this.idversion = idversion ;
    }
    public byte[] getIdversion() {
        return this.idversion;
    }

    public VhcReddistribucion getVhcreddistribucion() {
        return this.vhcreddistribucion;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("VhcReddistribucionversion[");
		// attribute 'idreddistribucionversion' (type byte[]) not usable in toString() 
		// attribute 'idreddistribucion' (type byte[]) not usable in toString() 
		// attribute 'idversion' (type byte[]) not usable in toString() 
		sb.append("]");
		return sb.toString();
	}

}
