/*
 * Created on 2026-02-11 ( 11:29:05 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.entities;


import jakarta.persistence.*;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;
import lombok.ToString;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * JPA entity class for "VhcReembolso"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@ToString
@RequiredArgsConstructor
@Entity
@Table(name="vhc_reembolso", catalog="adistemdb" )
public class VhcReembolso implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Lob
    @Column(name="IDREEMBOLSO", nullable=false)
    private byte[]     idreembolso ;

    //--- ENTITY DATA FIELDS 
    @Lob
    @Column(name="IDANIO", nullable=false)
    private byte[]     idanio ;

    @Column(name="BODYMODELCPOS", length=255)
    private String     bodymodelcpos ;

    @Column(name="VERSIONARCHIVO", length=255)
    private String     versionarchivo ;

    @Column(name="ANIOMYARCHIVO", length=255)
    private String     aniomyarchivo ;

    @Column(name="FECHAINICIO")
    private LocalDateTime fechainicio ;

    @Column(name="FECHAFIN")
    private LocalDateTime fechafin ;

    @Column(name="PRECIOLISTA", nullable=false)
    private BigDecimal preciolista ;

    @Column(name="CONTADODESCUENTO", nullable=false)
    private BigDecimal contadodescuento ;

    @Column(name="CONTADOREEMBOLSO", nullable=false)
    private BigDecimal contadoreembolso ;

    @Column(name="OFERTAPRINCIPALDESCUENTO", nullable=false)
    private BigDecimal ofertaprincipaldescuento ;

    @Column(name="OFERTAPRINCIPALREEMBOLSO", nullable=false)
    private BigDecimal ofertaprincipalreembolso ;

    @Column(name="OFERTAALTERNADESCUENTO", nullable=false)
    private BigDecimal ofertaalternadescuento ;

    @Column(name="OFERTAALTERNAREEMBOLSO", nullable=false)
    private BigDecimal ofertaalternareembolso ;

    @Lob
    @Column(name="IDCARGA")
    private byte[]     idcarga ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="IDANIO", referencedColumnName="IDANIO", insertable=false, updatable=false)
    private VhcAnio vhcanio ;

    @ManyToOne
    @JoinColumn(name="IDCARGA", referencedColumnName="IDCARGA", insertable=false, updatable=false)
    private LogCarga logcarga ;


}
