/*
 * Created on 2025-11-07 ( 16:16:34 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;

/**
 * JPA entity class for "VhcReddistribucionarchivo"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="vhc_reddistribucionarchivo", catalog="adistemdb" )
public class VhcReddistribucionarchivo implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @Lob
    @Column(name="IDREDDISTRIBUCIONARCHIVO", nullable=false)
    private byte[]     idreddistribucionarchivo ;

    //--- OTHER DATA FIELDS 
    @Column(name="ARCHIVO", length=255)
    private String     archivo ;

    @Lob
    @Column(name="IDREDDISTRIBUCION")
    private byte[]     idreddistribucion ;

    @Lob
    @Column(name="IDREDDISTRIBUCIONARCHIVOTIPO")
    private byte[]     idreddistribucionarchivotipo ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="IDREDDISTRIBUCION", referencedColumnName="IDREDDISTRIBUCION", insertable=false, updatable=false)
    private VhcReddistribucion vhcreddistribucion ; 

    /**
     * Constructor
     */
    public VhcReddistribucionarchivo() {
		super();
    }
    
    public void setIdreddistribucionarchivo( byte[] idreddistribucionarchivo ) {
        this.idreddistribucionarchivo = idreddistribucionarchivo ;
    }
    public byte[] getIdreddistribucionarchivo() {
        return this.idreddistribucionarchivo;
    }

    public void setArchivo( String archivo ) {
        this.archivo = archivo ;
    }
    public String getArchivo() {
        return this.archivo;
    }

    public void setIdreddistribucion( byte[] idreddistribucion ) {
        this.idreddistribucion = idreddistribucion ;
    }
    public byte[] getIdreddistribucion() {
        return this.idreddistribucion;
    }

    public void setIdreddistribucionarchivotipo( byte[] idreddistribucionarchivotipo ) {
        this.idreddistribucionarchivotipo = idreddistribucionarchivotipo ;
    }
    public byte[] getIdreddistribucionarchivotipo() {
        return this.idreddistribucionarchivotipo;
    }

    public VhcReddistribucion getVhcreddistribucion() {
        return this.vhcreddistribucion;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("VhcReddistribucionarchivo[");
		// attribute 'idreddistribucionarchivo' (type byte[]) not usable in toString() 
		sb.append("archivo=").append(archivo);
		// attribute 'idreddistribucion' (type byte[]) not usable in toString() 
		// attribute 'idreddistribucionarchivotipo' (type byte[]) not usable in toString() 
		sb.append("]");
		return sb.toString();
	}

}
