/*
 * Created on 2025-11-07 ( 16:16:34 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;

/**
 * JPA entity class for "VhcReddistribucionplantilla"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="vhc_reddistribucionplantilla", catalog="adistemdb" )
public class VhcReddistribucionplantilla implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @Lob
    @Column(name="IDREDDISTRIBUCIONPLANTILLA", nullable=false)
    private byte[]     idreddistribucionplantilla ;

    //--- OTHER DATA FIELDS 
    @Column(name="ORDEN", nullable=false)
    private int        orden ;

    @Column(name="ARCHIVO", length=255)
    private String     archivo ;

    @Lob
    @Column(name="IDREDDISTRIBUCION")
    private byte[]     idreddistribucion ;

    @Lob
    @Column(name="IDREDDISTRIBUCIONPLANTILLATIPO")
    private byte[]     idreddistribucionplantillatipo ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="IDREDDISTRIBUCION", referencedColumnName="IDREDDISTRIBUCION", insertable=false, updatable=false)
    private VhcReddistribucion vhcreddistribucion ; 

    /**
     * Constructor
     */
    public VhcReddistribucionplantilla() {
		super();
    }
    
    public void setIdreddistribucionplantilla( byte[] idreddistribucionplantilla ) {
        this.idreddistribucionplantilla = idreddistribucionplantilla ;
    }
    public byte[] getIdreddistribucionplantilla() {
        return this.idreddistribucionplantilla;
    }

    public void setOrden( int orden ) {
        this.orden = orden ;
    }
    public int getOrden() {
        return this.orden;
    }

    public void setArchivo( String archivo ) {
        this.archivo = archivo ;
    }
    public String getArchivo() {
        return this.archivo;
    }

    public void setIdreddistribucion( byte[] idreddistribucion ) {
        this.idreddistribucion = idreddistribucion ;
    }
    public byte[] getIdreddistribucion() {
        return this.idreddistribucion;
    }

    public void setIdreddistribucionplantillatipo( byte[] idreddistribucionplantillatipo ) {
        this.idreddistribucionplantillatipo = idreddistribucionplantillatipo ;
    }
    public byte[] getIdreddistribucionplantillatipo() {
        return this.idreddistribucionplantillatipo;
    }

    public VhcReddistribucion getVhcreddistribucion() {
        return this.vhcreddistribucion;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("VhcReddistribucionplantilla[");
		// attribute 'idreddistribucionplantilla' (type byte[]) not usable in toString() 
		sb.append("orden=").append(orden);
		sb.append(separator).append("archivo=").append(archivo);
		// attribute 'idreddistribucion' (type byte[]) not usable in toString() 
		// attribute 'idreddistribucionplantillatipo' (type byte[]) not usable in toString() 
		sb.append("]");
		return sb.toString();
	}

}
