/*
 * Created on 2025-11-07 ( 16:16:34 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.entities;

import java.io.Serializable;
import java.util.List;
import jakarta.persistence.*;

/**
 * JPA entity class for "VhcSegmento"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="vhc_segmento", catalog="adistemdb" )
public class VhcSegmento implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @Lob
    @Column(name="IDSEGMENTO", nullable=false)
    private byte[]     idsegmento ;

    //--- OTHER DATA FIELDS 
    @Column(name="NOMBRE", nullable=false, length=255)
    private String     nombre ;

    @Column(name="CLAVE", nullable=false, length=255)
    private String     clave ;

    @Column(name="ORDEN", nullable=false)
    private int        orden ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="vhcsegmento")
    private List<VhcSegmentomodelo> vhcsegmentomodeloList ; 

    /**
     * Constructor
     */
    public VhcSegmento() {
		super();
    }
    
    public void setIdsegmento( byte[] idsegmento ) {
        this.idsegmento = idsegmento ;
    }
    public byte[] getIdsegmento() {
        return this.idsegmento;
    }

    public void setNombre( String nombre ) {
        this.nombre = nombre ;
    }
    public String getNombre() {
        return this.nombre;
    }

    public void setClave( String clave ) {
        this.clave = clave ;
    }
    public String getClave() {
        return this.clave;
    }

    public void setOrden( int orden ) {
        this.orden = orden ;
    }
    public int getOrden() {
        return this.orden;
    }

    public List<VhcSegmentomodelo> getVhcsegmentomodeloList() {
        return this.vhcsegmentomodeloList;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("VhcSegmento[");
		// attribute 'idsegmento' (type byte[]) not usable in toString() 
		sb.append("nombre=").append(nombre);
		sb.append(separator).append("clave=").append(clave);
		sb.append(separator).append("orden=").append(orden);
		sb.append("]");
		return sb.toString();
	}

}
