/*
 * Created on 2025-11-07 ( 16:16:34 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;

/**
 * JPA entity class for "VhcSegmentomodelo"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="vhc_segmentomodelo", catalog="adistemdb" )
public class VhcSegmentomodelo implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @Lob
    @Column(name="IDSEGMENTOMODELO", nullable=false)
    private byte[]     idsegmentomodelo ;

    //--- OTHER DATA FIELDS 
    @Lob
    @Column(name="IDSEGMENTO")
    private byte[]     idsegmento ;

    @Lob
    @Column(name="IDMODELO")
    private byte[]     idmodelo ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="IDSEGMENTO", referencedColumnName="IDSEGMENTO", insertable=false, updatable=false)
    private VhcSegmento vhcsegmento ; 

    /**
     * Constructor
     */
    public VhcSegmentomodelo() {
		super();
    }
    
    public void setIdsegmentomodelo( byte[] idsegmentomodelo ) {
        this.idsegmentomodelo = idsegmentomodelo ;
    }
    public byte[] getIdsegmentomodelo() {
        return this.idsegmentomodelo;
    }

    public void setIdsegmento( byte[] idsegmento ) {
        this.idsegmento = idsegmento ;
    }
    public byte[] getIdsegmento() {
        return this.idsegmento;
    }

    public void setIdmodelo( byte[] idmodelo ) {
        this.idmodelo = idmodelo ;
    }
    public byte[] getIdmodelo() {
        return this.idmodelo;
    }

    public VhcSegmento getVhcsegmento() {
        return this.vhcsegmento;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("VhcSegmentomodelo[");
		// attribute 'idsegmentomodelo' (type byte[]) not usable in toString() 
		// attribute 'idsegmento' (type byte[]) not usable in toString() 
		// attribute 'idmodelo' (type byte[]) not usable in toString() 
		sb.append("]");
		return sb.toString();
	}

}
