/*
 * Created on 2025-11-07 ( 16:16:34 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.entities;

import java.io.Serializable;
import java.util.List;
import jakarta.persistence.*;

/**
 * JPA entity class for "VhcVersion"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="vhc_version", catalog="adistemdb" )
public class VhcVersion implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @Lob
    @Column(name="IDVERSION", nullable=false)
    private byte[]     idversion ;

    //--- OTHER DATA FIELDS 
    @Column(name="NOMBRE", nullable=false, length=255)
    private String     nombre ;

    @Lob
    @Column(name="IDMODELO")
    private byte[]     idmodelo ;

    //--- LINKS ( RELATIONSHIPS )
    @OneToMany(mappedBy="vhcversion")
    private List<VhcAnio> vhcanioList ; 

    @ManyToOne
    @JoinColumn(name="IDMODELO", referencedColumnName="IDMODELO", insertable=false, updatable=false)
    private VhcModelo  vhcmodelo ; 

    @OneToMany(mappedBy="vhcversion")
    private List<VhcVersionalias> vhcversionaliasList ; 

    /**
     * Constructor
     */
    public VhcVersion() {
		super();
    }
    
    public void setIdversion( byte[] idversion ) {
        this.idversion = idversion ;
    }
    public byte[] getIdversion() {
        return this.idversion;
    }

    public void setNombre( String nombre ) {
        this.nombre = nombre ;
    }
    public String getNombre() {
        return this.nombre;
    }

    public void setIdmodelo( byte[] idmodelo ) {
        this.idmodelo = idmodelo ;
    }
    public byte[] getIdmodelo() {
        return this.idmodelo;
    }

    public List<VhcAnio> getVhcanioList() {
        return this.vhcanioList;
    } 

    public VhcModelo getVhcmodelo() {
        return this.vhcmodelo;
    } 

    public List<VhcVersionalias> getVhcversionaliasList() {
        return this.vhcversionaliasList;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("VhcVersion[");
		// attribute 'idversion' (type byte[]) not usable in toString() 
		sb.append("nombre=").append(nombre);
		// attribute 'idmodelo' (type byte[]) not usable in toString() 
		sb.append("]");
		return sb.toString();
	}

}
