/*
 * Created on 2025-11-07 ( 16:16:34 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;

/**
 * JPA entity class for "VhcVersionalias"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="vhc_versionalias", catalog="adistemdb" )
public class VhcVersionalias implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @Lob
    @Column(name="IDVERSIONALIAS", nullable=false)
    private byte[]     idversionalias ;

    //--- OTHER DATA FIELDS 
    @Column(name="NOMBRE", nullable=false, length=255)
    private String     nombre ;

    @Lob
    @Column(name="IDVERSION")
    private byte[]     idversion ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="IDVERSION", referencedColumnName="IDVERSION", insertable=false, updatable=false)
    private VhcVersion vhcversion ; 

    /**
     * Constructor
     */
    public VhcVersionalias() {
		super();
    }
    
    public void setIdversionalias( byte[] idversionalias ) {
        this.idversionalias = idversionalias ;
    }
    public byte[] getIdversionalias() {
        return this.idversionalias;
    }

    public void setNombre( String nombre ) {
        this.nombre = nombre ;
    }
    public String getNombre() {
        return this.nombre;
    }

    public void setIdversion( byte[] idversion ) {
        this.idversion = idversion ;
    }
    public byte[] getIdversion() {
        return this.idversion;
    }

    public VhcVersion getVhcversion() {
        return this.vhcversion;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("VhcVersionalias[");
		// attribute 'idversionalias' (type byte[]) not usable in toString() 
		sb.append("nombre=").append(nombre);
		// attribute 'idversion' (type byte[]) not usable in toString() 
		sb.append("]");
		return sb.toString();
	}

}
