/*
 * Created on 2026-02-11 ( 11:29:05 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.entities;

import static junit.framework.TestCase.assertNotNull;

import com.organizame.reportes.entities.tooling.JpaTest;
import org.junit.Test;

public class LogCargaJpaTest extends JpaTest {

    public static LogCarga getInitEntity() {
    	LogCarga entity = new LogCarga();
		entity.setIdcarga( null ) ;
		entity.setNombre( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		entity.setTipo( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		entity.setInicio( java.time.LocalDateTime.parse("2001-05-21T01:46:52") ) ;
		entity.setFin( java.time.LocalDateTime.parse("2001-05-21T01:46:52") ) ;
		entity.setDescripcion( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		entity.setActivo( true ) ;
    	return entity;
	}
	
    private LogCarga createEntity() {
    	LogCarga entity = new LogCarga();
		entity.setIdcarga( null ) ;
		entity.setNombre( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setTipo( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setInicio( java.time.LocalDateTime.parse("2002-05-21T02:46:52") ) ;
		entity.setFin( java.time.LocalDateTime.parse("2002-05-21T02:46:52") ) ;
		entity.setDescripcion( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setActivo( false ) ;
    	return entity;
    }


    private Object getEntityKey(LogCarga entity) {
    	return entity.getIdcarga();
    }

    @Test
    public void testFind() {
    	LogCarga e = find(LogCarga.class, getEntityKey(getInitEntity()) );
		assertNotNull(e);
    }
    
    @Test
    public void testPersistFind() {
    	LogCarga entity = createEntity();
    	Object key = getEntityKey(entity);

    	// if entity doesn't exist yet
    	if ( find(LogCarga.class, key) == null ) {

	    	// Create with 'persist'
    		persistAndRefresh(entity);
    	
			// Find
			LogCarga entity2 = find(LogCarga.class, key);
			assertNotNull(entity2);
        
			// Remove (use only if no risk of referential integrity constraint violation)
			// findAndRemove(LogCarga.class, key);			
			// assertNull(find(LogCarga.class, key));
		}
    }

    @Test
    public void testMergeFind() {
    	LogCarga entity = createEntity();
    	Object key = getEntityKey(entity);

    	// Create or update with 'merge'
    	mergeAndRefresh(entity);
    	
    	// Find
    	LogCarga entity2 = find(LogCarga.class, key);
        assertNotNull(entity2);
        
		// Remove (use only if no risk of referential integrity constraint violation)
		// findAndRemove(LogCarga.class, key);			
        // assertNull(find(LogCarga.class, key));
    }

}
