/*
 * Created on 2026-02-11 ( 11:29:05 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.entities;

import static junit.framework.TestCase.assertNotNull;

import com.organizame.reportes.entities.tooling.JpaTest;
import org.junit.Test;

public class VhcAnioJpaTest extends JpaTest {

    public static VhcAnio getInitEntity() {
    	VhcAnio entity = new VhcAnio();
		entity.setIdanio( null ) ;
		entity.setNombre( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		entity.setIdversion( VhcVersionJpaTest.getInitEntity().getIdversion() ) ;
    	return entity;
	}
	
    private VhcAnio createEntity() {
    	VhcAnio entity = new VhcAnio();
		entity.setIdanio( null ) ;
		entity.setNombre( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setIdversion( VhcVersionJpaTest.getInitEntity().getIdversion() ) ;
    	return entity;
    }


    private Object getEntityKey(VhcAnio entity) {
    	return entity.getIdanio();
    }

    @Test
    public void testFind() {
    	VhcAnio e = find(VhcAnio.class, getEntityKey(getInitEntity()) );
		assertNotNull(e);
    }
    
    @Test
    public void testPersistFind() {
    	VhcAnio entity = createEntity();
    	Object key = getEntityKey(entity);

    	// if entity doesn't exist yet
    	if ( find(VhcAnio.class, key) == null ) {

	    	// Create with 'persist'
    		persistAndRefresh(entity);
    	
			// Find
			VhcAnio entity2 = find(VhcAnio.class, key);
			assertNotNull(entity2);
        
			// Remove (use only if no risk of referential integrity constraint violation)
			// findAndRemove(VhcAnio.class, key);			
			// assertNull(find(VhcAnio.class, key));
		}
    }

    @Test
    public void testMergeFind() {
    	VhcAnio entity = createEntity();
    	Object key = getEntityKey(entity);

    	// Create or update with 'merge'
    	mergeAndRefresh(entity);
    	
    	// Find
    	VhcAnio entity2 = find(VhcAnio.class, key);
        assertNotNull(entity2);
        
		// Remove (use only if no risk of referential integrity constraint violation)
		// findAndRemove(VhcAnio.class, key);			
        // assertNull(find(VhcAnio.class, key));
    }

}
