/*
 * Created on 2026-02-11 ( 11:29:05 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.entities;

import static junit.framework.TestCase.assertNotNull;

import com.organizame.reportes.entities.tooling.JpaTest;
import org.junit.Test;

public class VhcBoletinpreciogastoJpaTest extends JpaTest {

    public static VhcBoletinpreciogasto getInitEntity() {
    	VhcBoletinpreciogasto entity = new VhcBoletinpreciogasto();
		entity.setIdboletinpreciogasto( null ) ;
		entity.setNombre( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		entity.setIdboletinprecio( VhcBoletinprecioJpaTest.getInitEntity().getIdboletinprecio() ) ;
		entity.setDistribuidor( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		entity.setPublico( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
    	return entity;
	}
	
    private VhcBoletinpreciogasto createEntity() {
    	VhcBoletinpreciogasto entity = new VhcBoletinpreciogasto();
		entity.setIdboletinpreciogasto( null ) ;
		entity.setNombre( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setIdboletinprecio( VhcBoletinprecioJpaTest.getInitEntity().getIdboletinprecio() ) ;
		entity.setDistribuidor( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setPublico( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
    	return entity;
    }


    private Object getEntityKey(VhcBoletinpreciogasto entity) {
    	return entity.getIdboletinpreciogasto();
    }

    @Test
    public void testFind() {
    	VhcBoletinpreciogasto e = find(VhcBoletinpreciogasto.class, getEntityKey(getInitEntity()) );
		assertNotNull(e);
    }
    
    @Test
    public void testPersistFind() {
    	VhcBoletinpreciogasto entity = createEntity();
    	Object key = getEntityKey(entity);

    	// if entity doesn't exist yet
    	if ( find(VhcBoletinpreciogasto.class, key) == null ) {

	    	// Create with 'persist'
    		persistAndRefresh(entity);
    	
			// Find
			VhcBoletinpreciogasto entity2 = find(VhcBoletinpreciogasto.class, key);
			assertNotNull(entity2);
        
			// Remove (use only if no risk of referential integrity constraint violation)
			// findAndRemove(VhcBoletinpreciogasto.class, key);			
			// assertNull(find(VhcBoletinpreciogasto.class, key));
		}
    }

    @Test
    public void testMergeFind() {
    	VhcBoletinpreciogasto entity = createEntity();
    	Object key = getEntityKey(entity);

    	// Create or update with 'merge'
    	mergeAndRefresh(entity);
    	
    	// Find
    	VhcBoletinpreciogasto entity2 = find(VhcBoletinpreciogasto.class, key);
        assertNotNull(entity2);
        
		// Remove (use only if no risk of referential integrity constraint violation)
		// findAndRemove(VhcBoletinpreciogasto.class, key);			
        // assertNull(find(VhcBoletinpreciogasto.class, key));
    }

}
