/*
 * Created on 2026-02-11 ( 11:29:05 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.entities;

import static junit.framework.TestCase.assertNotNull;

import com.organizame.reportes.entities.tooling.JpaTest;
import org.junit.Test;

public class VhcBoletinprecioJpaTest extends JpaTest {

    public static VhcBoletinprecio getInitEntity() {
    	VhcBoletinprecio entity = new VhcBoletinprecio();
		entity.setIdboletinprecio( null ) ;
		entity.setIdanio( VhcAnioJpaTest.getInitEntity().getIdanio() ) ;
		entity.setBodymodelcpos( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		entity.setVersionarchivo( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		entity.setAniomyarchivo( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		entity.setFechainicio( java.time.LocalDateTime.parse("2001-05-21T01:46:52") ) ;
		entity.setDistribuidorunidadbasica( java.math.BigDecimal.valueOf(10000.77) ) ;
		entity.setDistribuidorcontenidosubtotal( java.math.BigDecimal.valueOf(10000.77) ) ;
		entity.setDistribuidorgastosubtotal( java.math.BigDecimal.valueOf(10000.77) ) ;
		entity.setDistribuidorisan( java.math.BigDecimal.valueOf(10000.77) ) ;
		entity.setDistribuidoriva( java.math.BigDecimal.valueOf(10000.77) ) ;
		entity.setDistribuidortotal( java.math.BigDecimal.valueOf(10000.77) ) ;
		entity.setPublicounidadbasica( java.math.BigDecimal.valueOf(10000.77) ) ;
		entity.setPublicocontenidosubtotal( java.math.BigDecimal.valueOf(10000.77) ) ;
		entity.setPublicogastosubtotal( java.math.BigDecimal.valueOf(10000.77) ) ;
		entity.setPublicoisan( java.math.BigDecimal.valueOf(10000.77) ) ;
		entity.setPublicoiva( java.math.BigDecimal.valueOf(10000.77) ) ;
		entity.setPublicototal( java.math.BigDecimal.valueOf(10000.77) ) ;
		entity.setIdcarga( null ) ;
    	return entity;
	}
	
    private VhcBoletinprecio createEntity() {
    	VhcBoletinprecio entity = new VhcBoletinprecio();
		entity.setIdboletinprecio( null ) ;
		entity.setIdanio( VhcAnioJpaTest.getInitEntity().getIdanio() ) ;
		entity.setBodymodelcpos( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setVersionarchivo( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setAniomyarchivo( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setFechainicio( java.time.LocalDateTime.parse("2002-05-21T02:46:52") ) ;
		entity.setDistribuidorunidadbasica( java.math.BigDecimal.valueOf(20000.77) ) ;
		entity.setDistribuidorcontenidosubtotal( java.math.BigDecimal.valueOf(20000.77) ) ;
		entity.setDistribuidorgastosubtotal( java.math.BigDecimal.valueOf(20000.77) ) ;
		entity.setDistribuidorisan( java.math.BigDecimal.valueOf(20000.77) ) ;
		entity.setDistribuidoriva( java.math.BigDecimal.valueOf(20000.77) ) ;
		entity.setDistribuidortotal( java.math.BigDecimal.valueOf(20000.77) ) ;
		entity.setPublicounidadbasica( java.math.BigDecimal.valueOf(20000.77) ) ;
		entity.setPublicocontenidosubtotal( java.math.BigDecimal.valueOf(20000.77) ) ;
		entity.setPublicogastosubtotal( java.math.BigDecimal.valueOf(20000.77) ) ;
		entity.setPublicoisan( java.math.BigDecimal.valueOf(20000.77) ) ;
		entity.setPublicoiva( java.math.BigDecimal.valueOf(20000.77) ) ;
		entity.setPublicototal( java.math.BigDecimal.valueOf(20000.77) ) ;
		entity.setIdcarga( null ) ;
    	return entity;
    }


    private Object getEntityKey(VhcBoletinprecio entity) {
    	return entity.getIdboletinprecio();
    }

    @Test
    public void testFind() {
    	VhcBoletinprecio e = find(VhcBoletinprecio.class, getEntityKey(getInitEntity()) );
		assertNotNull(e);
    }
    
    @Test
    public void testPersistFind() {
    	VhcBoletinprecio entity = createEntity();
    	Object key = getEntityKey(entity);

    	// if entity doesn't exist yet
    	if ( find(VhcBoletinprecio.class, key) == null ) {

	    	// Create with 'persist'
    		persistAndRefresh(entity);
    	
			// Find
			VhcBoletinprecio entity2 = find(VhcBoletinprecio.class, key);
			assertNotNull(entity2);
        
			// Remove (use only if no risk of referential integrity constraint violation)
			// findAndRemove(VhcBoletinprecio.class, key);			
			// assertNull(find(VhcBoletinprecio.class, key));
		}
    }

    @Test
    public void testMergeFind() {
    	VhcBoletinprecio entity = createEntity();
    	Object key = getEntityKey(entity);

    	// Create or update with 'merge'
    	mergeAndRefresh(entity);
    	
    	// Find
    	VhcBoletinprecio entity2 = find(VhcBoletinprecio.class, key);
        assertNotNull(entity2);
        
		// Remove (use only if no risk of referential integrity constraint violation)
		// findAndRemove(VhcBoletinprecio.class, key);			
        // assertNull(find(VhcBoletinprecio.class, key));
    }

}
