/*
 * Created on 2026-02-11 ( 11:29:05 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.entities;

import static junit.framework.TestCase.assertNotNull;

import com.organizame.reportes.entities.tooling.JpaTest;
import org.junit.Test;

public class VhcDaacuotaJpaTest extends JpaTest {

    public static VhcDaacuota getInitEntity() {
    	VhcDaacuota entity = new VhcDaacuota();
		entity.setIddaacuota( null ) ;
		entity.setIdanio( VhcAnioJpaTest.getInitEntity().getIdanio() ) ;
		entity.setPeriodoanio( 100 ) ;
		entity.setPeriodomes( 100 ) ;
		entity.setFechainicio( java.time.LocalDateTime.parse("2001-05-21T01:46:52") ) ;
		entity.setFechafin( java.time.LocalDateTime.parse("2001-05-21T01:46:52") ) ;
		entity.setDaacuota( java.math.BigDecimal.valueOf(10000.77) ) ;
		entity.setMarcaarchivo( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		entity.setReddistribucionarchivo( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		entity.setVersionarchivo( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		entity.setAniomyarchivo( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		entity.setBodymodelcpos( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		entity.setIdcarga( LogCargaJpaTest.getInitEntity().getIdcarga() ) ;
    	return entity;
	}
	
    private VhcDaacuota createEntity() {
    	VhcDaacuota entity = new VhcDaacuota();
		entity.setIddaacuota( null ) ;
		entity.setIdanio( VhcAnioJpaTest.getInitEntity().getIdanio() ) ;
		entity.setPeriodoanio( 200 ) ;
		entity.setPeriodomes( 200 ) ;
		entity.setFechainicio( java.time.LocalDateTime.parse("2002-05-21T02:46:52") ) ;
		entity.setFechafin( java.time.LocalDateTime.parse("2002-05-21T02:46:52") ) ;
		entity.setDaacuota( java.math.BigDecimal.valueOf(20000.77) ) ;
		entity.setMarcaarchivo( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setReddistribucionarchivo( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setVersionarchivo( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setAniomyarchivo( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setBodymodelcpos( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setIdcarga( LogCargaJpaTest.getInitEntity().getIdcarga() ) ;
    	return entity;
    }


    private Object getEntityKey(VhcDaacuota entity) {
    	return entity.getIddaacuota();
    }

    @Test
    public void testFind() {
    	VhcDaacuota e = find(VhcDaacuota.class, getEntityKey(getInitEntity()) );
		assertNotNull(e);
    }
    
    @Test
    public void testPersistFind() {
    	VhcDaacuota entity = createEntity();
    	Object key = getEntityKey(entity);

    	// if entity doesn't exist yet
    	if ( find(VhcDaacuota.class, key) == null ) {

	    	// Create with 'persist'
    		persistAndRefresh(entity);
    	
			// Find
			VhcDaacuota entity2 = find(VhcDaacuota.class, key);
			assertNotNull(entity2);
        
			// Remove (use only if no risk of referential integrity constraint violation)
			// findAndRemove(VhcDaacuota.class, key);			
			// assertNull(find(VhcDaacuota.class, key));
		}
    }

    @Test
    public void testMergeFind() {
    	VhcDaacuota entity = createEntity();
    	Object key = getEntityKey(entity);

    	// Create or update with 'merge'
    	mergeAndRefresh(entity);
    	
    	// Find
    	VhcDaacuota entity2 = find(VhcDaacuota.class, key);
        assertNotNull(entity2);
        
		// Remove (use only if no risk of referential integrity constraint violation)
		// findAndRemove(VhcDaacuota.class, key);			
        // assertNull(find(VhcDaacuota.class, key));
    }

}
