/*
 * Created on 2026-02-11 ( 11:29:05 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.entities;

import static junit.framework.TestCase.assertNotNull;

import com.organizame.reportes.entities.tooling.JpaTest;
import org.junit.Test;

public class VhcIncentivoJpaTest extends JpaTest {

    public static VhcIncentivo getInitEntity() {
    	VhcIncentivo entity = new VhcIncentivo();
		entity.setIdincentivo( null ) ;
		entity.setIdanio( VhcAnioJpaTest.getInitEntity().getIdanio() ) ;
		entity.setPeriodoanio( 100 ) ;
		entity.setPeriodomes( 100 ) ;
		entity.setFechainicio( java.time.LocalDateTime.parse("2001-05-21T01:46:52") ) ;
		entity.setFechafin( java.time.LocalDateTime.parse("2001-05-21T01:46:52") ) ;
		entity.setPreciolista( java.math.BigDecimal.valueOf(10000.77) ) ;
		entity.setContadodescuento( java.math.BigDecimal.valueOf(10000.77) ) ;
		entity.setContadoparticipaciondistribuidores( java.math.BigDecimal.valueOf(10000.77) ) ;
		entity.setContadototaldescuentos( java.math.BigDecimal.valueOf(10000.77) ) ;
		entity.setContadoprecio( java.math.BigDecimal.valueOf(10000.77) ) ;
		entity.setContadosegurogratis( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		entity.setContadomantenimientogratis( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		entity.setFinanciamientodescuentopromocional( java.math.BigDecimal.valueOf(10000.77) ) ;
		entity.setFinanciamientoparticipaciondistribuidores( java.math.BigDecimal.valueOf(10000.77) ) ;
		entity.setFinanciamientototaldescuentos( java.math.BigDecimal.valueOf(10000.77) ) ;
		entity.setFinanciamientopreciopromocional( java.math.BigDecimal.valueOf(10000.77) ) ;
		entity.setFinanciamientotasadesde( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		entity.setFinanciamientosegurogratis( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		entity.setFinanciamientomantenimientogratis( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		entity.setFinanciamientoalternodescuentopromocional( java.math.BigDecimal.valueOf(10000.77) ) ;
		entity.setFinanciamientoalternoparticipaciondistribuidores( java.math.BigDecimal.valueOf(10000.77) ) ;
		entity.setFinanciamientoalternototaldescuentos( java.math.BigDecimal.valueOf(10000.77) ) ;
		entity.setFinanciamientoalternopreciopromocional( java.math.BigDecimal.valueOf(10000.77) ) ;
		entity.setFinanciamientoalternotasadesde( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		entity.setFinanciamientoalternosegurogratis( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		entity.setMesessinintereses( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		entity.setMesessininteresesprecio( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		entity.setMarcaarchivo( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		entity.setModeloarchivo( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		entity.setVersionarchivo( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		entity.setAnioarchivo( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		entity.setIdcarga( null ) ;
    	return entity;
	}
	
    private VhcIncentivo createEntity() {
    	VhcIncentivo entity = new VhcIncentivo();
		entity.setIdincentivo( null ) ;
		entity.setIdanio( VhcAnioJpaTest.getInitEntity().getIdanio() ) ;
		entity.setPeriodoanio( 200 ) ;
		entity.setPeriodomes( 200 ) ;
		entity.setFechainicio( java.time.LocalDateTime.parse("2002-05-21T02:46:52") ) ;
		entity.setFechafin( java.time.LocalDateTime.parse("2002-05-21T02:46:52") ) ;
		entity.setPreciolista( java.math.BigDecimal.valueOf(20000.77) ) ;
		entity.setContadodescuento( java.math.BigDecimal.valueOf(20000.77) ) ;
		entity.setContadoparticipaciondistribuidores( java.math.BigDecimal.valueOf(20000.77) ) ;
		entity.setContadototaldescuentos( java.math.BigDecimal.valueOf(20000.77) ) ;
		entity.setContadoprecio( java.math.BigDecimal.valueOf(20000.77) ) ;
		entity.setContadosegurogratis( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setContadomantenimientogratis( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setFinanciamientodescuentopromocional( java.math.BigDecimal.valueOf(20000.77) ) ;
		entity.setFinanciamientoparticipaciondistribuidores( java.math.BigDecimal.valueOf(20000.77) ) ;
		entity.setFinanciamientototaldescuentos( java.math.BigDecimal.valueOf(20000.77) ) ;
		entity.setFinanciamientopreciopromocional( java.math.BigDecimal.valueOf(20000.77) ) ;
		entity.setFinanciamientotasadesde( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setFinanciamientosegurogratis( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setFinanciamientomantenimientogratis( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setFinanciamientoalternodescuentopromocional( java.math.BigDecimal.valueOf(20000.77) ) ;
		entity.setFinanciamientoalternoparticipaciondistribuidores( java.math.BigDecimal.valueOf(20000.77) ) ;
		entity.setFinanciamientoalternototaldescuentos( java.math.BigDecimal.valueOf(20000.77) ) ;
		entity.setFinanciamientoalternopreciopromocional( java.math.BigDecimal.valueOf(20000.77) ) ;
		entity.setFinanciamientoalternotasadesde( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setFinanciamientoalternosegurogratis( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setMesessinintereses( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setMesessininteresesprecio( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setMarcaarchivo( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setModeloarchivo( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setVersionarchivo( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setAnioarchivo( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setIdcarga( null ) ;
    	return entity;
    }


    private Object getEntityKey(VhcIncentivo entity) {
    	return entity.getIdincentivo();
    }

    @Test
    public void testFind() {
    	VhcIncentivo e = find(VhcIncentivo.class, getEntityKey(getInitEntity()) );
		assertNotNull(e);
    }
    
    @Test
    public void testPersistFind() {
    	VhcIncentivo entity = createEntity();
    	Object key = getEntityKey(entity);

    	// if entity doesn't exist yet
    	if ( find(VhcIncentivo.class, key) == null ) {

	    	// Create with 'persist'
    		persistAndRefresh(entity);
    	
			// Find
			VhcIncentivo entity2 = find(VhcIncentivo.class, key);
			assertNotNull(entity2);
        
			// Remove (use only if no risk of referential integrity constraint violation)
			// findAndRemove(VhcIncentivo.class, key);			
			// assertNull(find(VhcIncentivo.class, key));
		}
    }

    @Test
    public void testMergeFind() {
    	VhcIncentivo entity = createEntity();
    	Object key = getEntityKey(entity);

    	// Create or update with 'merge'
    	mergeAndRefresh(entity);
    	
    	// Find
    	VhcIncentivo entity2 = find(VhcIncentivo.class, key);
        assertNotNull(entity2);
        
		// Remove (use only if no risk of referential integrity constraint violation)
		// findAndRemove(VhcIncentivo.class, key);			
        // assertNull(find(VhcIncentivo.class, key));
    }

}
