/*
 * Created on 2026-02-11 ( 11:29:05 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.entities;

import static junit.framework.TestCase.assertNotNull;

import com.organizame.reportes.entities.tooling.JpaTest;
import org.junit.Test;

public class VhcModeloJpaTest extends JpaTest {

    public static VhcModelo getInitEntity() {
    	VhcModelo entity = new VhcModelo();
		entity.setIdmodelo( null ) ;
		entity.setNombre( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		entity.setIdmarca( VhcMarcaJpaTest.getInitEntity().getIdmarca() ) ;
		entity.setNombretrim( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		entity.setClave( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
    	return entity;
	}
	
    private VhcModelo createEntity() {
    	VhcModelo entity = new VhcModelo();
		entity.setIdmodelo( null ) ;
		entity.setNombre( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setIdmarca( VhcMarcaJpaTest.getInitEntity().getIdmarca() ) ;
		entity.setNombretrim( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setClave( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
    	return entity;
    }


    private Object getEntityKey(VhcModelo entity) {
    	return entity.getIdmodelo();
    }

    @Test
    public void testFind() {
    	VhcModelo e = find(VhcModelo.class, getEntityKey(getInitEntity()) );
		assertNotNull(e);
    }
    
    @Test
    public void testPersistFind() {
    	VhcModelo entity = createEntity();
    	Object key = getEntityKey(entity);

    	// if entity doesn't exist yet
    	if ( find(VhcModelo.class, key) == null ) {

	    	// Create with 'persist'
    		persistAndRefresh(entity);
    	
			// Find
			VhcModelo entity2 = find(VhcModelo.class, key);
			assertNotNull(entity2);
        
			// Remove (use only if no risk of referential integrity constraint violation)
			// findAndRemove(VhcModelo.class, key);			
			// assertNull(find(VhcModelo.class, key));
		}
    }

    @Test
    public void testMergeFind() {
    	VhcModelo entity = createEntity();
    	Object key = getEntityKey(entity);

    	// Create or update with 'merge'
    	mergeAndRefresh(entity);
    	
    	// Find
    	VhcModelo entity2 = find(VhcModelo.class, key);
        assertNotNull(entity2);
        
		// Remove (use only if no risk of referential integrity constraint violation)
		// findAndRemove(VhcModelo.class, key);			
        // assertNull(find(VhcModelo.class, key));
    }

}
