/*
 * Created on 2026-02-11 ( 11:29:05 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.entities;

import static junit.framework.TestCase.assertNotNull;

import com.organizame.reportes.entities.tooling.JpaTest;
import org.junit.Test;

public class VhcReembolsoJpaTest extends JpaTest {

    public static VhcReembolso getInitEntity() {
    	VhcReembolso entity = new VhcReembolso();
		entity.setIdreembolso( null ) ;
		entity.setIdanio( VhcAnioJpaTest.getInitEntity().getIdanio() ) ;
		entity.setBodymodelcpos( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		entity.setVersionarchivo( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		entity.setAniomyarchivo( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		entity.setFechainicio( java.time.LocalDateTime.parse("2001-05-21T01:46:52") ) ;
		entity.setFechafin( java.time.LocalDateTime.parse("2001-05-21T01:46:52") ) ;
		entity.setPreciolista( java.math.BigDecimal.valueOf(10000.77) ) ;
		entity.setContadodescuento( java.math.BigDecimal.valueOf(10000.77) ) ;
		entity.setContadoreembolso( java.math.BigDecimal.valueOf(10000.77) ) ;
		entity.setOfertaprincipaldescuento( java.math.BigDecimal.valueOf(10000.77) ) ;
		entity.setOfertaprincipalreembolso( java.math.BigDecimal.valueOf(10000.77) ) ;
		entity.setOfertaalternadescuento( java.math.BigDecimal.valueOf(10000.77) ) ;
		entity.setOfertaalternareembolso( java.math.BigDecimal.valueOf(10000.77) ) ;
		entity.setIdcarga( LogCargaJpaTest.getInitEntity().getIdcarga() ) ;
    	return entity;
	}
	
    private VhcReembolso createEntity() {
    	VhcReembolso entity = new VhcReembolso();
		entity.setIdreembolso( null ) ;
		entity.setIdanio( VhcAnioJpaTest.getInitEntity().getIdanio() ) ;
		entity.setBodymodelcpos( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setVersionarchivo( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setAniomyarchivo( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setFechainicio( java.time.LocalDateTime.parse("2002-05-21T02:46:52") ) ;
		entity.setFechafin( java.time.LocalDateTime.parse("2002-05-21T02:46:52") ) ;
		entity.setPreciolista( java.math.BigDecimal.valueOf(20000.77) ) ;
		entity.setContadodescuento( java.math.BigDecimal.valueOf(20000.77) ) ;
		entity.setContadoreembolso( java.math.BigDecimal.valueOf(20000.77) ) ;
		entity.setOfertaprincipaldescuento( java.math.BigDecimal.valueOf(20000.77) ) ;
		entity.setOfertaprincipalreembolso( java.math.BigDecimal.valueOf(20000.77) ) ;
		entity.setOfertaalternadescuento( java.math.BigDecimal.valueOf(20000.77) ) ;
		entity.setOfertaalternareembolso( java.math.BigDecimal.valueOf(20000.77) ) ;
		entity.setIdcarga( LogCargaJpaTest.getInitEntity().getIdcarga() ) ;
    	return entity;
    }


    private Object getEntityKey(VhcReembolso entity) {
    	return entity.getIdreembolso();
    }

    @Test
    public void testFind() {
    	VhcReembolso e = find(VhcReembolso.class, getEntityKey(getInitEntity()) );
		assertNotNull(e);
    }
    
    @Test
    public void testPersistFind() {
    	VhcReembolso entity = createEntity();
    	Object key = getEntityKey(entity);

    	// if entity doesn't exist yet
    	if ( find(VhcReembolso.class, key) == null ) {

	    	// Create with 'persist'
    		persistAndRefresh(entity);
    	
			// Find
			VhcReembolso entity2 = find(VhcReembolso.class, key);
			assertNotNull(entity2);
        
			// Remove (use only if no risk of referential integrity constraint violation)
			// findAndRemove(VhcReembolso.class, key);			
			// assertNull(find(VhcReembolso.class, key));
		}
    }

    @Test
    public void testMergeFind() {
    	VhcReembolso entity = createEntity();
    	Object key = getEntityKey(entity);

    	// Create or update with 'merge'
    	mergeAndRefresh(entity);
    	
    	// Find
    	VhcReembolso entity2 = find(VhcReembolso.class, key);
        assertNotNull(entity2);
        
		// Remove (use only if no risk of referential integrity constraint violation)
		// findAndRemove(VhcReembolso.class, key);			
        // assertNull(find(VhcReembolso.class, key));
    }

}
