/*
 * Created on 2026-02-11 ( 11:29:05 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.entities;

import static junit.framework.TestCase.assertNotNull;

import com.organizame.reportes.entities.tooling.JpaTest;
import org.junit.Test;

public class VhcVersionJpaTest extends JpaTest {

    public static VhcVersion getInitEntity() {
    	VhcVersion entity = new VhcVersion();
		entity.setIdversion( null ) ;
		entity.setNombre( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
		entity.setIdmodelo( VhcModeloJpaTest.getInitEntity().getIdmodelo() ) ;
		entity.setClave( "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ) ;
    	return entity;
	}
	
    private VhcVersion createEntity() {
    	VhcVersion entity = new VhcVersion();
		entity.setIdversion( null ) ;
		entity.setNombre( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
		entity.setIdmodelo( VhcModeloJpaTest.getInitEntity().getIdmodelo() ) ;
		entity.setClave( "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" ) ;
    	return entity;
    }


    private Object getEntityKey(VhcVersion entity) {
    	return entity.getIdversion();
    }

    @Test
    public void testFind() {
    	VhcVersion e = find(VhcVersion.class, getEntityKey(getInitEntity()) );
		assertNotNull(e);
    }
    
    @Test
    public void testPersistFind() {
    	VhcVersion entity = createEntity();
    	Object key = getEntityKey(entity);

    	// if entity doesn't exist yet
    	if ( find(VhcVersion.class, key) == null ) {

	    	// Create with 'persist'
    		persistAndRefresh(entity);
    	
			// Find
			VhcVersion entity2 = find(VhcVersion.class, key);
			assertNotNull(entity2);
        
			// Remove (use only if no risk of referential integrity constraint violation)
			// findAndRemove(VhcVersion.class, key);			
			// assertNull(find(VhcVersion.class, key));
		}
    }

    @Test
    public void testMergeFind() {
    	VhcVersion entity = createEntity();
    	Object key = getEntityKey(entity);

    	// Create or update with 'merge'
    	mergeAndRefresh(entity);
    	
    	// Find
    	VhcVersion entity2 = find(VhcVersion.class, key);
        assertNotNull(entity2);
        
		// Remove (use only if no risk of referential integrity constraint violation)
		// findAndRemove(VhcVersion.class, key);			
        // assertNull(find(VhcVersion.class, key));
    }

}
