/*
 * Created on 2025-11-07 ( 16:16:33 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.repositories;

import com.organizame.reportes.persistence.entities.ISANTarifa;
import org.springframework.data.jpa.repository.JpaRepository;


public interface ISANTarifaRepository extends JpaRepository<ISANTarifa, byte[]> {


}
