/*
 * Created on 2025-11-07 ( 16:16:33 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.repositories;

import org.springframework.data.repository.PagingAndSortingRepository;

import com.organizame.reportes.persistence.entities.VhcGrupomarca;

/**
 * Spring Data JPA repository for entity "VhcGrupomarca" <br> 
 * 
 * This repository extends PagingAndSortingRepository interface <br>
 * so it provides by default all the basic CRUD operations : <br>
 *   findById, findAll, save, delete, etc <br> 
 * with pagination and sorting : <br>
 *   findAll(Pageable), findAll(Sort)<br>
 * 
 * This repository can be extended by adding specific "finders" methods<br>
 * To do so, see the "predicates conventions" for "derived query methods" in Spring Data documentation
 * 
 * @author Telosys
 *
 */
public interface VhcGrupomarcaRepository extends PagingAndSortingRepository<VhcGrupomarca, byte[]> {

	// Insert specific finders here 

	//List<VhcGrupomarca> findByXxx(String xxx);

	//List<VhcGrupomarca> findByXxxStartingWith(String xxx);

	//List<VhcGrupomarca> findByXxxContaining(String xxx);

	//List<VhcGrupomarca> findByYyy(BigDecimal yyy);

	//List<VhcGrupomarca> findByXxxContainingAndYyy(String xxx, BigDecimal yyy);
}
