/*
 * Created on 2025-11-07 ( 16:16:34 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package com.organizame.reportes.persistence.repositories;

import com.organizame.reportes.persistence.entities.VhcMarca;
import com.organizame.reportes.persistence.entities.VhcModeloperiodoindustria;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.PagingAndSortingRepository;

import com.organizame.reportes.persistence.entities.VhcMarcaperiodo;
import org.springframework.data.repository.query.Param;

import java.util.List;

/**
 * Spring Data JPA repository for entity "VhcMarcaperiodo" <br> 
 * 
 * This repository extends PagingAndSortingRepository interface <br>
 * so it provides by default all the basic CRUD operations : <br>
 *   findById, findAll, save, delete, etc <br> 
 * with pagination and sorting : <br>
 *   findAll(Pageable), findAll(Sort)<br>
 * 
 * This repository can be extended by adding specific "finders" methods<br>
 * To do so, see the "predicates conventions" for "derived query methods" in Spring Data documentation
 * 
 * @author Telosys
 *
 */
public interface VhcMarcaperiodoRepository extends PagingAndSortingRepository<VhcMarcaperiodo, byte[]> {

    @Query("""
                select v 
                from VhcMarcaperiodo v
                where v.vhcmarca = :marca and  
                v.periodoanio = :anio and v.periodomes between :desde and :hasta
                order by v.periodoanio, v.periodomes
            """)
    List<VhcMarcaperiodo> findTotalUltimosMeses(
            @Param("marca") VhcMarca marca,
            @Param("anio") int anio,
            @Param("desde") int desde,
            @Param("hasta") int hasta
    );
}
